///////////////////////////////////////////////////////////////////////////////
//  Fermilab National Accelerator Laboratory
///////////////////////////////////////////////////////////////////////////////
// Description: 
//   QickEmu-driven testbench for QICK project — Verilator compatible.
//   Replaces Xilinx VIPs with PULP Platform AXI VIPs.
//   Dynamically replays AXI transactions and loads memories from QickEmu.
//////////////////////////////////////////////////////////////////////////////

`timescale 1ns/1fs

`include "_qproc_defines.svh"

// <<<<<<<<<<<< XILINX VIP PACKAGES
// import axi_vip_pkg::*;
// import axi_mst_0_pkg::*;
// ============
`include "axi/typedef.svh"
`include "axi/assign.svh"
// >>>>>>>>>>>> PULP PLATFORM AXI VIP

// +++++++++++++ ADD PULP PLATFORM AXI RAND MASTER TYPEDEFS
localparam time         ApplTime          =  100ns;
localparam time         TestTime          =  0ns;

typedef axi_test::axi_lite_rand_master #(
   // AXI interface parameters
   .AW ( 32'd8               ), // Axi Address Width
   .DW ( 32'd32              ), // Axi Data Width
   // Stimuli application and test time
   .TA ( ApplTime            ),
   .TT ( TestTime            ),
   .MIN_ADDR ( 32'h0000_0000 ),
   .MAX_ADDR ( 32'hffff_ffff ),
   .MAX_READ_TXNS  ( 1 ),
   .MAX_WRITE_TXNS ( 1 ),
   .AX_MIN_WAIT_CYCLES   ( 0   ),
   .AX_MAX_WAIT_CYCLES   ( 0   ),
   .W_MIN_WAIT_CYCLES    ( 0   ),
   .W_MAX_WAIT_CYCLES    ( 0   ),
   .RESP_MIN_WAIT_CYCLES ( 0   ),
   .RESP_MAX_WAIT_CYCLES ( 0   )
) rand_lite_master_addr8_data32_t;

typedef axi_test::axi_lite_rand_master #(
   // AXI interface parameters
   .AW ( 32'd6               ), // Axi Address Width
   .DW ( 32'd32              ), // Axi Data Width
   // Stimuli application and test time
   .TA ( ApplTime            ),
   .TT ( TestTime            ),
   .MIN_ADDR ( 32'h0000_0000 ),
   .MAX_ADDR ( 32'hffff_ffff ),
   .MAX_READ_TXNS  ( 1 ),
   .MAX_WRITE_TXNS ( 1 ),
   .AX_MIN_WAIT_CYCLES   ( 0   ),
   .AX_MAX_WAIT_CYCLES   ( 0   ),
   .W_MIN_WAIT_CYCLES    ( 0   ),
   .W_MAX_WAIT_CYCLES    ( 0   ),
   .RESP_MIN_WAIT_CYCLES ( 0   ),
   .RESP_MAX_WAIT_CYCLES ( 0   )
) rand_lite_master_addr6_data32_t;

// +++++++++++++

localparam real T_TCLK          =  1.162;      // Half Clock Period for tProc Dispatcher (430MHz)
localparam real T_CCLK          =    2.5;      // Half Clock Period for tProc Core (200MHz)
localparam real T_SCLK          =    5.0;      // Half Clock Period for PS & AXI (100MHz)

// localparam real T_SG_CLK        =  0.833;  // Half Clock Period for Signal Gens (600MHz — ZCU216 RFDC)
localparam real T_SG_CLK        =  0.8346688;  // Half Clock Period for Signal Gens (600MHz — ZCU216 RFDC)

// localparam real T_RO_CLK        =  1.627;      // Half Clock Period for Readout (307.2MHz)
localparam real T_RO_CLK        =  1.62760416; // Half Clock Period for Readout (307.2MHz — ZCU216 RFDC)

// TPROC PARAMETERS
`define GEN_SYNC         1
`define DUAL_CORE        0
`define IO_CTRL          1
`define DEBUG            3
`define TNET             0
`define QCOM             0
`define CUSTOM_PERIPH    2
`define LFSR             1
`define DIVIDER          1
`define ARITH            1
`define TIME_READ        1
`define FIFO_DEPTH       8
`define PMEM_AW          12 
`define DMEM_AW          14 
`define WMEM_AW          11
`define REG_AW           4 
`define IN_PORT_QTY      1
`define OUT_TRIG_QTY     1
`define OUT_DPORT_QTY    1
`define OUT_DPORT_DW     8
`define OUT_WPORT_QTY    5 

module QICKEmu_harness ();

// Emulator flag to conditionally instantiate 
// behavioral models in place of VHDL/Xilinx IP.
// Valid values: 0 for synthesis (default), non-zero for emulation.
parameter EMULATOR = 0;

string TEST_OUT_CONNECTION = "TEST_OUT_LOOPBACK";     // Connect DAC/ADC in Loopback

localparam N_DDS_SG = 16;
localparam N_DDS_RO = 8;

//----------------------------------------------------
// QickEmu Configuration
//----------------------------------------------------
// EMU_DIR is the directory containing memory dumps and axi_replay.txt
// generated by QickEmu.prepare() / export_vivado_files().
//
// Override via plusargs:
//   +EMU_DIR=<path>       — alternate directory for TB inputs/outputs
//   +TEST_RUN_NS=<int>    — override TEST_RUN_TIME (ns)
//   +RO_AVG_LEN=<int>     — override averaged-readout drain length
//   +RO_DEC_LEN=<int>     — override decimated-readout drain length
//   +TRACE                — enable VCD dump to obj_dir/waveform.vcd
string EMU_DIR       = "../artifacts";
time   TEST_RUN_TIME = 1us;
int    ro_avg_len    = 1;
int    ro_dec_len    = 32'h039A;
int    mr_len        = 0;          // max ro_clk rows to log into mr_out.csv (0 = disabled)


//----------------------------------------------------
// Address Routing (ZCU216 default AddrMap; override via export_vivado_files())
//----------------------------------------------------
// AVG_BASE_HI == TPROC_BASE is intentional — AVG_BASE_HI is an exclusive upper
// bound, so the last avgbuf slot ends at 0x4025FFFF and tproc starts at
// 0x40260000 with no overlap.
// DEFAULT ZCU216 ADDR MAP (see zcu216_addr_map.csv):
// localparam integer TPROC_BASE  = 40'h40260000;
// localparam integer SG_BASE_LO  = 40'h40020000;
// localparam integer SG_BASE_HI  = 40'h40120000;
// localparam integer AVG_BASE_LO = 40'h40130000;
// localparam integer AVG_BASE_HI = 40'h40260000;
// QICKEMU_DUT Address Map
localparam integer TPROC_BASE  = 40'h400260000;
localparam integer SG_BASE_LO  = 40'h4001C0000;  // 1 gen IP(s)
localparam integer SG_BASE_HI  = 40'h4001D0000;
localparam integer AVG_BASE_LO = 40'h400060000;  // 1 avgbuf IP(s)
localparam integer AVG_BASE_HI = 40'h400070000;

// VIP Agents

// <<<<<<<<<<<< XILINX AXI VIP
// axi_mst_0_mst_t     axi_mst_tproc_agent;
// axi_mst_0_mst_t     axi_mst_sg_agent;
// axi_mst_0_mst_t     axi_mst_avg_agent;
// ============
rand_lite_master_addr8_data32_t axi_mst_tproc_agent;
rand_lite_master_addr6_data32_t axi_mst_sg_agent;
rand_lite_master_addr6_data32_t axi_mst_avg_agent;
// >>>>>>>>>>>> PULP PLATFORM AXI VIP


// AXI Master VIP variables
// <<<<<<<<<<<< XILINX AXI VIP
// xil_axi_prot_t  prot        = 0;
// xil_axi_resp_t  resp;
// ============
axi_pkg::prot_t prot = 0;
axi_pkg::resp_t resp;
// >>>>>>>>>>>> PULP PLATFORM AXI VIP

// ++++++++++++ TELL VERILATOR TO LOG SIGNALS IN VCD FILE (opt-in via +TRACE)
initial begin
   #1;
   if ($test$plusargs("TRACE")) begin
      string vcd_file;
      vcd_file = {EMU_DIR, "/waveform.vcd"};
      $dumpfile(vcd_file);
      $dumpvars(0, tb_qick_emu_verilator);
      $display("### TRACE Enabled: VCD dump enabled. Output file: %s", vcd_file);
   end
end
// ++++++++++++

//////////////////////////////////////////////////////////////////////////
//  CLK Generation
logic          c_clk, t_clk, s_ps_dma_aclk;

logic [4:0]    dac_fs_gen;
logic          dac_fs, sg_clk;

logic [4:0]    adc_fs_gen;
logic          adc_fs, ro_clk;

initial begin
  t_clk = 1'b0;
  forever # (T_TCLK*1.0ns) t_clk = ~t_clk;
end

initial begin
  c_clk = 1'b0;
  forever # (T_CCLK*1.0ns) c_clk = ~c_clk;
end

initial begin
  s_ps_dma_aclk = 1'b0;
  #0.5ns
  forever # (T_SCLK*1.0ns) s_ps_dma_aclk = ~s_ps_dma_aclk;
end

initial begin
   dac_fs_gen = 'd0;
   forever # (T_SG_CLK*1.0ns/N_DDS_SG) dac_fs_gen = dac_fs_gen + 'd1;
end
assign dac_fs  = dac_fs_gen[0];
assign sg_clk  = dac_fs_gen[4];

initial begin
   adc_fs_gen = 'd0;
   forever # (T_RO_CLK*1.0ns/N_DDS_RO) adc_fs_gen = adc_fs_gen + 'd1;
end
assign adc_fs  = adc_fs_gen[0];
assign ro_clk  = adc_fs_gen[3];


//////////////////////////////////////////////////////////////////////////
//  RST Generation
logic rst_ni;
assign s_ps_dma_aresetn  = rst_ni;

wire  s_ps_dma_aresetn;

//////////////////////////////////////////////////////////////////////////

reg [255 :0]       s_dma_axis_tdata_i   ;
reg                s_dma_axis_tlast_i   ;
reg                s_dma_axis_tvalid_i  ;
reg                m_dma_axis_tready_i  ;
wire [63 :0]       port_0_dt_i          ;
reg [63 :0]        port_1_dt_i          ;


// The emu TB holds these m{1..7}_axis_tready high so the tProc dispatcher's
// unused wave ports don't back-pressure the core.
reg                m1_axis_tready   =1   ;
reg                m2_axis_tready   =1   ;
reg                m3_axis_tready   =1   ;

reg                m5_axis_tready   =1   ;
reg                m6_axis_tready   =1   ;
reg                m7_axis_tready   =1   ;

wire               s_dma_axis_tready_o  ;
wire [255 :0]      m_dma_axis_tdata_o   ;
wire               m_dma_axis_tlast_o   ;
wire               m_dma_axis_tvalid_o  ;

// tProc Interface
wire [167:0]       m1_axis_tdata        ;
wire               m1_axis_tvalid       ;
wire [167:0]       m2_axis_tdata        ;
wire               m2_axis_tvalid       ;
wire [167:0]       m3_axis_tdata        ;
wire               m3_axis_tvalid       ;

wire [167:0]       m5_axis_tdata        ;
wire               m5_axis_tvalid       ;
wire [167:0]       m6_axis_tdata        ;
wire               m6_axis_tvalid       ;
wire [167:0]       m7_axis_tdata        ;
wire               m7_axis_tvalid       ;

wire               trigger_0;

wire [`OUT_DPORT_DW-1:0]         port_0_dt_o, port_1_dt_o, port_2_dt_o, port_3_dt_o;


// QNET Peripheral
wire                qnet_en_o   ;
wire  [4 :0]        qnet_op_o   ;
wire  [31:0]        qnet_a_dt_o ;
wire  [31:0]        qnet_b_dt_o ;
wire  [31:0]        qnet_c_dt_o ;
wire  [31:0]        qnet_d_dt_o ;
reg                 qnet_rdy_i      ;
reg  [31 :0]        qnet_dt_i [2]   ;

// QCOM Peripheral
wire                qcom_en_o   ;
wire  [4 :0]        qcom_op_o   ;
wire  [31:0]        qcom_dt_o   ;
reg                 qcom_rdy_i      ;
reg  [31 :0]        qcom_dt_i [2]   ;
reg                 qcom_vld_i      ;
reg                 qcom_flag_i     ;

reg  [31 :0]        qp1_dt_i [2]   ;
reg  [31 :0]        qp2_dt_i [2]   ;

wire                periph_en_o   ;
wire  [4 :0]        periph_op_o   ;
wire  [31:0]        periph_a_dt_o ;
wire  [31:0]        periph_b_dt_o ;
wire  [31:0]        periph_c_dt_o ;
wire  [31:0]        periph_d_dt_o ;

reg                periph_rdy_i    ;
reg  [31 :0]       periph_dt_i [2] ;


// reg    s0_axis_tvalid;
reg s1_axis_tvalid ;

// reg [15:0] waves, wtime;
// reg [31:0] axi_dt;


reg proc_start_i, proc_stop_i ;
reg core_start_i, core_stop_i ;
reg time_rst_i, time_init_i;

reg  [47:0] offset_dt_i ;
wire [47:0] t_time_abs_o ;
reg time_updt_i;

wire [31:0] ps_debug_do;

// Q Peripheral A loopback
wire qp1_en_o;
reg qp1_en_r;
reg [31:0] qp1_a_dt_r, qp1_b_dt_r;
wire [31:0] qp1_a_dt_o, qp1_b_dt_o, qp1_c_dt_o, qp1_d_dt_o;
always_ff @ (posedge c_clk) begin 
   qp1_en_r     <= qp1_en_o;
   qp1_a_dt_r   <= qp1_a_dt_o;
   qp1_b_dt_r   <= qp1_b_dt_o;
end
  
assign qp1_rdy_i     = ~qp1_en_r;
assign qp1_dt_i[0]   = qp1_a_dt_r;
assign qp1_dt_i[1]   = qp1_b_dt_r;
assign qp1_vld_i     = qp1_en_r;

wire port_0_vld, qnet_vld_i, qnet_flag_i, periph_flag_i, ext_flag_i;


// -----------------------------------------------------------------------------
// Readout → tProc feedback path.
//
// The real ZCU216 SoC wires `axis_avg_buffer_0.m2_axis` (one-shot handshake on
// each completed average) into `qick_processor.s0_axis`, so that `DPORT_RD 0`
// (emitted by `read_input(ro_ch=0)` / `read_and_jump`) can sample the
// per-shot I/Q accumulator in a tProc register. The emu TB reproduces that
// link: m2_axis fires once per shot, we latch {acc_q[31:0], acc_i[31:0]}
// and hold it until the next shot replaces it. That way the tProc can read
// the result at any time after the buffer has drained. PORT_L = I, PORT_H = Q.
// -----------------------------------------------------------------------------
wire        avg0_m2_tvalid;
wire [63:0] avg0_m2_tdata;
reg  [63:0] readout_ch0_dt;
reg         readout_ch0_vld;

always_ff @(posedge s_ps_dma_aclk) begin
   if (!s_ps_dma_aresetn) begin
      readout_ch0_dt  <= 64'd0;
      readout_ch0_vld <= 1'b0;
   end
   else if (avg0_m2_tvalid) begin
      readout_ch0_dt  <= avg0_m2_tdata;
      readout_ch0_vld <= 1'b1;
   end
end

assign port_0_dt_i     = readout_ch0_dt;
assign port_0_vld      = readout_ch0_vld;

assign qnet_vld_i      = t_time_abs_o[3]&t_time_abs_o[2]&t_time_abs_o[1] ;
assign qnet_flag_i       = ~t_time_abs_o[5] & ~t_time_abs_o[4] & t_time_abs_o[3] ;
assign periph_flag_i     = ~t_time_abs_o[5] &  t_time_abs_o[4] & t_time_abs_o[3] ;
assign ext_flag_i        =  t_time_abs_o[5] &  t_time_abs_o[4] & t_time_abs_o[3] ;


   // DAC-ADC connections
   logic                      axis_sg_dac_tready;
   logic                      axis_sg_dac_tvalid;
   logic [N_DDS_SG*16-1:0]    axis_sg_dac_tdata;

   logic                      rf_signal_valid;
   logic [N_DDS_RO*16-1:0]    rf_signal_data;

   logic                      axis_adc_ro_tready;
   logic                      axis_adc_ro_tvalid;
   logic [N_DDS_RO*16-1:0]    axis_adc_ro_tdata;


   // // Register ADDRESS
   // parameter REG_TPROC_CTRL      = 0  * 4 ;
   // parameter REG_TPROC_CFG       = 1  * 4 ;
   // parameter REG_MEM_ADDR        = 2  * 4 ;
   // parameter REG_MEM_LEN         = 3  * 4 ;
   // parameter REG_MEM_DT_I        = 4  * 4 ;
   // parameter REG_AXI_W_DT1       = 5  * 4 ;
   // parameter REG_AXI_W_DT2       = 6  * 4 ;
   // parameter REG_CORE_CFG        = 7  * 4 ;
   // parameter REG_AXI_DT_SRC      = 8  * 4 ;
   // parameter REG_MEM_DT_O        = 10  * 4 ;
   // parameter REG_AXI_R_DT1       = 11  * 4 ;
   // parameter REG_AXI_R_DT2       = 12  * 4 ;
   // parameter REG_TIME_USR        = 13  * 4 ;
   // parameter REG_TPROC_STATUS    = 14  * 4 ;
   // parameter REG_TPROC_DEBUG     = 15  * 4 ;


wire sg_s0_axis_aclk = s_ps_dma_aclk;
logic   [31:0]       sg_s0_axis_tdata;
logic                sg_s0_axis_tready;
logic                sg_s0_axis_tvalid;

logic    [63:0]    m0_axis_buf_avg_tdata;
logic              m0_axis_buf_avg_tvalid;
logic              m0_axis_buf_avg_tready;

logic    [31:0]    m1_axis_buf_dec_tdata;
logic              m1_axis_buf_dec_tvalid;
logic              m1_axis_buf_dec_tready;

   //--------------------------------------
   // QICK DUT
   //--------------------------------------

   qick_dut #(
// ++++++++++++ ADD EMULATOR PARAMETER
      .EMULATOR         (1'b1),
// ++++++++++++      
      .N_DDS_SG         (N_DDS_SG        ),
      .N_DDS_RO         (N_DDS_RO        ),
      // tProc Parameters
      .GEN_SYNC         (`GEN_SYNC        ),
      .DUAL_CORE        (`DUAL_CORE       ),
      .IO_CTRL          (`IO_CTRL         ),
      .DEBUG            (`DEBUG           ),
      .TNET             (`TNET            ),
      .QCOM             (`QCOM            ),
      .CUSTOM_PERIPH    (`CUSTOM_PERIPH   ),
      .LFSR             (`LFSR            ),
      .DIVIDER          (`DIVIDER         ),
      .ARITH            (`ARITH           ),
      .TIME_READ        (`TIME_READ       ),
      .FIFO_DEPTH       (`FIFO_DEPTH      ),
      .PMEM_AW          (`PMEM_AW         ),
      .DMEM_AW          (`DMEM_AW         ),
      .WMEM_AW          (`WMEM_AW         ),
      .REG_AW           (`REG_AW          ),
      .IN_PORT_QTY      (`IN_PORT_QTY     ),
      .OUT_TRIG_QTY     (`OUT_TRIG_QTY    ),
      .OUT_DPORT_QTY    (`OUT_DPORT_QTY   ),
      .OUT_DPORT_DW     (`OUT_DPORT_DW    ),
      .OUT_WPORT_QTY    (`OUT_WPORT_QTY   )
   )
   qick_dut (
      // Core, Time and AXI CLK & RST.
      .t_clk               ( t_clk              ) ,
      .t_resetn            ( rst_ni             ) ,
      .c_clk               ( c_clk              ) ,
      .c_resetn            ( rst_ni             ) ,
      .ps_clk              ( s_ps_dma_aclk      ) ,
      .ps_resetn           ( s_ps_dma_aresetn   ) ,
      .sg_clk              ( sg_clk             ) ,
      .sg_resetn           ( rst_ni             ) ,
      .ro_clk              ( ro_clk             ) ,
      .ro_resetn           ( rst_ni             ) ,
      // External Control
      .ext_flag_i          ( ext_flag_i         ) ,
      .proc_start_i        ( proc_start_i       ) ,
      .proc_stop_i         ( proc_stop_i        ) ,
      .core_start_i        ( core_start_i       ) ,
      .core_stop_i         ( core_stop_i        ) ,
      .time_rst_i          ( time_rst_i         ) ,
      .time_init_i         ( time_init_i        ) ,
      .time_updt_i         ( time_updt_i        ) ,
      .time_dt_i           ( offset_dt_i        ) ,
      .t_time_abs_o        ( t_time_abs_o       ) ,
      //QNET
      .qnet_en_o           ( qnet_en_o          ) ,
      .qnet_op_o           ( qnet_op_o          ) ,
      .qnet_a_dt_o         ( qnet_a_dt_o        ) ,
      .qnet_b_dt_o         ( qnet_b_dt_o        ) ,
      .qnet_c_dt_o         ( qnet_c_dt_o        ) ,
      .qnet_rdy_i          ( qnet_rdy_i         ) ,
      .qnet_dt1_i          ( qnet_dt_i[0]       ) ,
      .qnet_dt2_i          ( qnet_dt_i[1]       ) ,
      .qnet_vld_i          ( qnet_vld_i         ) ,
      .qnet_flag_i         ( qnet_flag_i        ) ,
      //QCOM
      .qcom_en_o           ( qcom_en_o          ) ,
      .qcom_op_o           ( qcom_op_o          ) ,
      .qcom_dt_o           ( qcom_dt_o          ) ,
      .qcom_rdy_i          ( qcom_rdy_i         ) ,
      .qcom_dt1_i          ( qcom_dt_i[0]       ) ,
      .qcom_dt2_i          ( qcom_dt_i[1]       ) ,
      .qcom_vld_i          ( qcom_vld_i         ) ,
      .qcom_flag_i         ( qcom_flag_i        ) ,
      // QP1
      .qp1_en_o           ( qp1_en_o          ) ,
      .qp1_op_o           ( qp1_op_o          ) ,
      .qp1_a_dt_o         ( qp1_a_dt_o        ) ,
      .qp1_b_dt_o         ( qp1_b_dt_o        ) ,
      .qp1_c_dt_o         ( qp1_c_dt_o        ) ,
      .qp1_d_dt_o         ( qp1_d_dt_o        ) ,
      .qp1_rdy_i          ( qp1_rdy_i         ) ,
      .qp1_dt1_i          ( qp1_dt_i[0]       ) ,
      .qp1_dt2_i          ( qp1_dt_i[1]       ) ,
      .qp1_vld_i          ( qp1_vld_i         ) ,
      .qp1_flag_i         ( 1'b0              ) ,
      // QP2 (unused in emu TB — tied off)
      .qp2_en_o           ( /*qp2_en_o   */   ) ,
      .qp2_op_o           ( /*qp2_op_o   */   ) ,
      .qp2_a_dt_o         ( /*qp2_a_dt_o */   ) ,
      .qp2_b_dt_o         ( /*qp2_b_dt_o */   ) ,
      .qp2_c_dt_o         ( /*qp2_c_dt_o */   ) ,
      .qp2_d_dt_o         ( /*qp2_d_dt_o */   ) ,
      .qp2_rdy_i          ( 1'b0              ) ,
      .qp2_dt1_i          ( 32'd0             ) ,
      .qp2_dt2_i          ( 32'd0             ) ,
      .qp2_vld_i          ( 1'b0              ) ,
      // DMA AXIS FOR READ AND WRITE MEMORY
      .s_dma_axis_tdata_i   ( s_dma_axis_tdata_i  ) ,
      .s_dma_axis_tlast_i   ( s_dma_axis_tlast_i  ) ,
      .s_dma_axis_tvalid_i  ( s_dma_axis_tvalid_i ) ,
      .s_dma_axis_tready_o  ( s_dma_axis_tready_o ) ,
      .m_dma_axis_tdata_o   ( m_dma_axis_tdata_o  ) ,
      .m_dma_axis_tlast_o   ( m_dma_axis_tlast_o  ) ,
      .m_dma_axis_tvalid_o  ( m_dma_axis_tvalid_o ) ,
      .m_dma_axis_tready_i  ( m_dma_axis_tready_i ) ,
      /// DATA PORT INPUT  
      .s0_axis_tdata        ( port_0_dt_i    ) ,
      .s0_axis_tvalid       ( port_0_vld     ) ,
      .s0_axis_tready       (                ) ,
      .s1_axis_tdata        ( port_1_dt_i    ) ,
      .s1_axis_tvalid       ( s1_axis_tvalid ) ,
      .s1_axis_tready       (                ) ,
      ///// TRIGGERS
      .trig_0_o             ( trigger_0               ),
      // OUT DATA PORTS
      .port_0_dt_o          ( port_0_dt_o             ) ,
      .port_1_dt_o          ( port_1_dt_o             ) ,
      .port_2_dt_o          ( port_2_dt_o             ) ,
      .port_3_dt_o          ( port_3_dt_o             ) ,
      // Debug Signals
      .ps_debug_do          ( ),
      .t_debug_do           ( ),
      .t_fifo_do            ( ),
      .c_time_usr_do        ( ),
      .c_debug_do           ( ),
      .c_time_ref_do        ( ),
      .c_port_do            ( ),
      .c_core_do            ( ),

      // Signal Generator from tProc interface
      .sg_s0_axis_aclk           (sg_s0_axis_aclk        ),
      .sg_s0_axis_aresetn        (s_ps_dma_aresetn       ),
      .sg_s0_axis_tdata          (sg_s0_axis_tdata       ),
      .sg_s0_axis_tvalid         (sg_s0_axis_tvalid      ),
      .sg_s0_axis_tready         (sg_s0_axis_tready      ),

      // Signal Generator to DAC interface
      .axis_sg_dac_tready        (axis_sg_dac_tready     ),
      .axis_sg_dac_tvalid        (axis_sg_dac_tvalid     ),
      .axis_sg_dac_tdata         (axis_sg_dac_tdata      ),

      // ADC to Readout interface
      .axis_adc_ro_tready        (axis_adc_ro_tready     ),
      .axis_adc_ro_tvalid        (axis_adc_ro_tvalid     ),
      .axis_adc_ro_tdata         (axis_adc_ro_tdata      ),

      .axis_ro_mrbuf_tvalid         (axis_ro_mrbuf_tvalid ),
      .axis_ro_mrbuf_tdata          (axis_ro_mrbuf_tdata  ),

      // AXIS Master for averaged output.
      .m0_axis_buf_avg_tready         (1'b1/*m0_axis_tready*/),
      .m0_axis_buf_avg_tvalid         (m0_axis_buf_avg_tvalid),
      .m0_axis_buf_avg_tdata          (m0_axis_buf_avg_tdata ),
      .m0_axis_buf_avg_tlast          (/*m0_axis_tlast*/     ),

      // AXIS Master for decimated output.
      .m1_axis_buf_dec_tready         (m1_axis_buf_dec_tready),
      .m1_axis_buf_dec_tvalid         (m1_axis_buf_dec_tvalid),
      .m1_axis_buf_dec_tdata          (m1_axis_buf_dec_tdata ),
      .m1_axis_buf_dec_tlast          (/*m1_axis_tlast*/     ),

      // AXIS Master for register output.
      //
      // Wired into the `s0_axis` input of `axis_qick_processor` via the
      // `readout_ch0_dt`/`readout_ch0_vld` latch near the top of the TB so
      // that `read_input(ro_ch=0)` / `read_and_jump` can sample per-shot I/Q.
      .m2_axis_buf_reg_tready         (1'b1/*m2_axis_tready*/),
      .m2_axis_buf_reg_tvalid         (avg0_m2_tvalid        ),
      .m2_axis_buf_reg_tdata          (avg0_m2_tdata         )
   );


   //--------------------------------------
   // RF DATA CONVERTER IP (behavioral model — loopback DAC/ADC)
   //--------------------------------------

   // DAC-ADC RF frontend model

   localparam DAC_W = 16;
   logic signed [DAC_W-1:0] dac_data;
   localparam ADC_W = 16;
   logic signed [ADC_W-1:0] adc_sample;
   logic signed [15:0] adc_data;

   model_DAC_ADC #(
      .DAC_W               (DAC_W),
      .ADC_W               (ADC_W),
      .BUFFER_SIZE         (16)
   ) u_model_DAC_ADC (
      .clk_DAC             (dac_fs),
      .dac_sample          (dac_data),

      .clk_ADC             (adc_fs),
      .adc_sample          (adc_sample),

      .mode                (1)   // 0 = ZOH, 1 = linear
   );

   // SG to DAC RF processes 16 samples per clock

   assign axis_sg_dac_tready        = 1'b1;  // DAC always ready to receive samples

   logic [$clog2(N_DDS_SG)-1:0] dac_samp_cnt;
   always @(posedge dac_fs) begin
      if (axis_sg_dac_tvalid) begin
         dac_data       <= axis_sg_dac_tdata[16*dac_samp_cnt +: 16];
         dac_samp_cnt   <= dac_samp_cnt + 'd1;
      end
      else begin
         dac_data       <= 'd0;
         dac_samp_cnt   <= 'd0;
      end
   end


   // ADC RF to RO processes 8 samples per clock

   assign adc_data = $signed(adc_sample);

   logic [$clog2(N_DDS_RO)-1:0] adc_samp_cnt;
   always @(posedge adc_fs) begin
      if (adc_samp_cnt < N_DDS_RO-1) begin
         adc_samp_cnt      <= adc_samp_cnt + 1;
         rf_signal_valid   <= 0;
      end
      else begin
         adc_samp_cnt      <= 0;
         rf_signal_valid   <= 1;
      end
      rf_signal_data[16*adc_samp_cnt +: 16] <= adc_data;
   end


   // Model Transport delay

// <<<<<<<<<<<< VERILATOR INCOMPATIBLE DELAY 
   // NOTE: THESE MUST BE REG TO WORK!!!
   // reg                    rf_signal_valid_dly;
   // reg [N_DDS_RO*16-1:0]  rf_signal_data_dly;
   // always @(*) begin
   //    rf_signal_valid_dly <= #250ns rf_signal_valid;
   //    rf_signal_data_dly  <= #250ns rf_signal_data;
   // end
// ============
   // assign #250ns rf_signal_valid_dly = rf_signal_valid;
   // assign #250ns rf_signal_data_dly  = rf_signal_data;
   localparam RF_DELAY_TIME_NS = 100;
   localparam int RF_DELAY_CYCLES = $ceil(RF_DELAY_TIME_NS / (2.0*T_RO_CLK/N_DDS_RO));
   logic                    rf_signal_valid_dly;
   logic [N_DDS_RO*16-1:0]  rf_signal_data_dly;
   logic [N_DDS_RO*16:0] rf_delay_line [0:RF_DELAY_CYCLES-1];
   always_ff @(posedge adc_fs) begin
      rf_delay_line[0] <= {rf_signal_valid, rf_signal_data};
      for (int i=1; i<RF_DELAY_CYCLES; i++) begin
         rf_delay_line[i] <= rf_delay_line[i-1];
      end
      rf_signal_valid_dly <= rf_delay_line[RF_DELAY_CYCLES-1][N_DDS_RO*16];
      rf_signal_data_dly  <= rf_delay_line[RF_DELAY_CYCLES-1][N_DDS_RO*16-1:0];
   end
// >>>>>>>>>>>> VERILATOR COMPATIBLE CONTINUOUS DELAY


   // //--------------------------------------
   // // WIP: Qubit Emulator
   // //--------------------------------------

   // wire  [7:0]       s_axi_qemu_araddr;
   // wire  [2:0]       s_axi_qemu_arprot;
   // wire              s_axi_qemu_arready;
   // wire              s_axi_qemu_arvalid;
   // wire  [7:0]       s_axi_qemu_awaddr;
   // wire  [2:0]       s_axi_qemu_awprot;
   // wire              s_axi_qemu_awready;
   // wire              s_axi_qemu_awvalid;
   // wire              s_axi_qemu_bready;
   // wire  [1:0]       s_axi_qemu_bresp;
   // wire              s_axi_qemu_bvalid;
   // wire  [31:0]      s_axi_qemu_rdata;
   // wire              s_axi_qemu_rready;
   // wire  [1:0]       s_axi_qemu_rresp;
   // wire              s_axi_qemu_rvalid;
   // wire  [31:0]      s_axi_qemu_wdata;
   // wire              s_axi_qemu_wready;
   // wire  [3:0]       s_axi_qemu_wstrb;
   // wire              s_axi_qemu_wvalid;
   
   // // AXI VIP master address.
   // xil_axi_ulong   QEMU_DDS_BVAL_REG     = 4 * 0;
   // xil_axi_ulong   QEMU_DDS_SLOPE_REG    = 4 * 1;
   // xil_axi_ulong   QEMU_DDS_STEPS_REG    = 4 * 2;
   // xil_axi_ulong   QEMU_DDS_WAIT_REG     = 4 * 3;
   // xil_axi_ulong   QEMU_DDS_FREQ_REG     = 4 * 4;
   // xil_axi_ulong   QEMU_IIR_C0_REG       = 4 * 5;
   // xil_axi_ulong   QEMU_IIR_C1_REG       = 4 * 6;
   // xil_axi_ulong   QEMU_IIR_G_REG        = 4 * 7;
   // xil_axi_ulong   QEMU_OUTSEL_REG       = 4 * 8;
   // xil_axi_ulong   QEMU_PUNCT_ID_REG     = 4 * 9;
   // xil_axi_ulong   QEMU_ADDR_REG         = 4 * 10;
   // xil_axi_ulong   QEMU_WE_REG           = 4 * 11;

   // localparam L = 1;
   // wire              axis_qemu_ro_tvalid;
   // wire [L*2*16-1:0] axis_qemu_ro_tdata;

   // axi_mst_0 u_axi_mst_qemu_0 (
   //    .aclk          (s_ps_dma_aclk       ),
   //    .aresetn       (s_ps_dma_aresetn    ),
   //    .m_axi_araddr  (s_axi_qemu_araddr    ),
   //    .m_axi_arprot  (s_axi_qemu_arprot    ),
   //    .m_axi_arready (s_axi_qemu_arready   ),
   //    .m_axi_arvalid (s_axi_qemu_arvalid   ),
   //    .m_axi_awaddr  (s_axi_qemu_awaddr    ),
   //    .m_axi_awprot  (s_axi_qemu_awprot    ),
   //    .m_axi_awready (s_axi_qemu_awready   ),
   //    .m_axi_awvalid (s_axi_qemu_awvalid   ),
   //    .m_axi_bready  (s_axi_qemu_bready    ),
   //    .m_axi_bresp   (s_axi_qemu_bresp     ),
   //    .m_axi_bvalid  (s_axi_qemu_bvalid    ),
   //    .m_axi_rdata   (s_axi_qemu_rdata     ),
   //    .m_axi_rready  (s_axi_qemu_rready    ),
   //    .m_axi_rresp   (s_axi_qemu_rresp     ),
   //    .m_axi_rvalid  (s_axi_qemu_rvalid    ),
   //    .m_axi_wdata   (s_axi_qemu_wdata     ),
   //    .m_axi_wready  (s_axi_qemu_wready    ),
   //    .m_axi_wstrb   (s_axi_qemu_wstrb     ),
   //    .m_axi_wvalid  (s_axi_qemu_wvalid    )
   // );

   // axis_kidsim_v3 #(
   //    .L                      (L)   // Number of lanes.
   // )
   // u_axis_kidsim_v3 (
   //    // AXI Slave I/F for configuration.
   //    .s_axi_aclk             (s_ps_dma_aclk       ),
   //    .s_axi_aresetn          (s_ps_dma_aresetn    ),
   //    .s_axi_araddr           (s_axi_qemu_araddr   ),
   //    .s_axi_arprot           (s_axi_qemu_arprot   ),
   //    .s_axi_arready          (s_axi_qemu_arready  ),
   //    .s_axi_arvalid          (s_axi_qemu_arvalid  ),
   //    .s_axi_awaddr           (s_axi_qemu_awaddr   ),
   //    .s_axi_awprot           (s_axi_qemu_awprot   ),
   //    .s_axi_awready          (s_axi_qemu_awready  ),
   //    .s_axi_awvalid          (s_axi_qemu_awvalid  ),
   //    .s_axi_bready           (s_axi_qemu_bready   ),
   //    .s_axi_bresp            (s_axi_qemu_bresp    ),
   //    .s_axi_bvalid           (s_axi_qemu_bvalid   ),
   //    .s_axi_rdata            (s_axi_qemu_rdata    ),
   //    .s_axi_rready           (s_axi_qemu_rready   ),
   //    .s_axi_rresp            (s_axi_qemu_rresp    ),
   //    .s_axi_rvalid           (s_axi_qemu_rvalid   ),
   //    .s_axi_wdata            (s_axi_qemu_wdata    ),
   //    .s_axi_wready           (s_axi_qemu_wready   ),
   //    .s_axi_wstrb            (s_axi_qemu_wstrb    ),
   //    .s_axi_wvalid           (s_axi_qemu_wvalid   ),

   //    // Modulation trigger.
   //    .trigger                (trigger_0           ),

   //    // Reset and clock for axis_*.
   //    .aresetn                (s_ps_dma_aresetn    ),
   //    .aclk                   (adc_fs             ),

   //    // s_axis_* for input.
   //    .s_axis_tvalid          (1'b1),
   //    // .s_axis_tdata           ({adc_data_imag,adc_data_real}),   // width: 32*L, should be I/Q from input ADC
   //    .s_axis_tdata           ({16'd0,adc_data}),   // width: 32*L, should be I/Q from input ADC
   //    .s_axis_tlast           (1'b1),

   //    // m_axis_* for output.
   //    .m_axis_tvalid          (axis_qemu_ro_tvalid ),
   //    .m_axis_tdata           (axis_qemu_ro_tdata  ),   // width: 32*L, should be I/Q to output DAC
   //    .m_axis_tlast           ()
   // );


   // Sample RF signal with ADC/RO clock - 8 real samples per RO clock
   // always_ff @(posedge ro_clk) begin
   //    if (TEST_OUT_CONNECTION == "TEST_OUT_LOOPBACK") begin
   //       axis_adc_ro_tvalid                  <= rf_signal_valid_dly;
   //       axis_adc_ro_tdata[N_DDS_RO*16-1:0]  <= rf_signal_data_dly;
   //    end
   //    else if (TEST_OUT_CONNECTION == "TEST_OUT_QEMU") begin
   //       axis_adc_ro_tvalid                  <= axis_qemu_ro_tvalid;
   //       for (int i=0; i<N_DDS_RO; i=i+1) begin
   //          axis_adc_ro_tdata[i*16 +: 16]  <= axis_qemu_ro_tdata[15:0];
   //       end
   //    end
   // end

   logic [2:0] rf_signal_cnt;
   always_ff @(posedge adc_fs) begin
      if (TEST_OUT_CONNECTION == "TEST_OUT_LOOPBACK") begin
         if (rf_signal_cnt == 0) begin
            axis_adc_ro_tvalid                  <= rf_signal_valid_dly;
            axis_adc_ro_tdata[N_DDS_RO*16-1:0]  <= rf_signal_data_dly;
         end
         else begin
         end
         if (rf_signal_valid_dly || axis_adc_ro_tvalid) begin
            rf_signal_cnt  <= rf_signal_cnt + 1;
         end
         else begin
            rf_signal_cnt  <= 0;
         end
      end
   end


   // -----------------------------------------------------------------------------
   // EMU_DIR plusarg.
   //
   // Must run before any $fopen / $readmemh that uses EMU_DIR. Also parses
   // TEST_RUN_NS / RO_AVG_LEN / RO_DEC_LEN plusargs so the notebook driver
   // can sweep these without recompiling.
   // -----------------------------------------------------------------------------
   initial begin
      int t_ns;

      if (!$value$plusargs("EMU_DIR=%s", EMU_DIR))
         $display("### Using default EMU_DIR=%s ###", EMU_DIR);
      else
         $display("### EMU_DIR set to %s via plusarg ###", EMU_DIR);

      if ($value$plusargs("TEST_RUN_NS=%d", t_ns)) begin
         TEST_RUN_TIME = t_ns * 1ns;
         $display("### TEST_RUN_TIME overridden to %0d ns ###", t_ns);
      end

      if ($value$plusargs("RO_AVG_LEN=%d", ro_avg_len))
         $display("### RO_AVG_LEN overridden to %0d via plusarg ###", ro_avg_len);

      if ($value$plusargs("RO_DEC_LEN=%d", ro_dec_len))
         $display("### RO_DEC_LEN overridden to %0d via plusarg ###", ro_dec_len);

      if ($value$plusargs("MR_LEN=%d", mr_len))
         $display("### MR_LEN overridden to %0d via plusarg ###", mr_len);

      $fflush();
   end

   // -----------------------------------------------------------------------------
   // CSV Output Logging.
   //
   // dac_out.csv — one row per sg_clk with axis_sg_dac_tvalid, N_DDS lanes.
   // avg_out.csv — one row per averaged I/Q sample from avg_buffer m0.
   // dec_out.csv — one row per decimated I/Q sample from avg_buffer m1.
   // mr_out.csv  — one row per ro_clk while axis_ro_mrbuf_tvalid, 8 I/Q lanes
   //               (post-downconversion, pre-FIR). Capped by +MR_LEN plusarg.
   // -----------------------------------------------------------------------------
   integer dac_csv_fd;
   integer avg_csv_fd;
   integer dec_csv_fd;
   integer mr_csv_fd;
   int     mr_rows_logged = 0;

   initial begin
      string dac_csv_path;
      string avg_csv_path;
      string dec_csv_path;
      string mr_csv_path;

      #0;  // yield so the plusarg initial block runs first

      dac_csv_path = {EMU_DIR, "/dac_out.csv"};
      avg_csv_path = {EMU_DIR, "/avg_out.csv"};
      dec_csv_path = {EMU_DIR, "/dec_out.csv"};
      mr_csv_path  = {EMU_DIR, "/mr_out.csv"};

      $display("### Opening CSV: %s ###", dac_csv_path);
      dac_csv_fd = $fopen(dac_csv_path, "w");
      avg_csv_fd = $fopen(avg_csv_path, "w");
      dec_csv_fd = $fopen(dec_csv_path, "w");
      mr_csv_fd  = $fopen(mr_csv_path, "w");

      $fwrite(dac_csv_fd, "time_ps");
      for (int i = 0; i < N_DDS_SG; i++) $fwrite(dac_csv_fd, ",s%0d", i);
      $fwrite(dac_csv_fd, "\n");
      $fwrite(avg_csv_fd, "time_ps,I,Q\n");
      $fwrite(dec_csv_fd, "time_ps,I,Q\n");
      $fwrite(mr_csv_fd, "time_ps");
      for (int i = 0; i < 8; i++) $fwrite(mr_csv_fd, ",I%0d,Q%0d", i, i);
      $fwrite(mr_csv_fd, "\n");
   end

   always @(posedge sg_clk) begin
      if (axis_sg_dac_tvalid) begin
         $fwrite(dac_csv_fd, "%0t", $realtime);
         for (int i = 0; i < N_DDS_SG; i++)
            $fwrite(dac_csv_fd, ",%0d", $signed(axis_sg_dac_tdata[16*i +: 16]));
         $fwrite(dac_csv_fd, "\n");
      end
   end

   always @(posedge s_ps_dma_aclk) begin
      if (m0_axis_buf_avg_tvalid)
         $fwrite(avg_csv_fd, "%0t,%0d,%0d\n", $realtime,
                 $signed(m0_axis_buf_avg_tdata[31:0]),
                 $signed(m0_axis_buf_avg_tdata[63:32]));
   end

   always @(posedge s_ps_dma_aclk) begin
      if (m1_axis_buf_dec_tvalid)
         $fwrite(dec_csv_fd, "%0t,%0d,%0d\n", $realtime,
                 $signed(m1_axis_buf_dec_tdata[15:0]),
                 $signed(m1_axis_buf_dec_tdata[31:16]));
   end

   wire              axis_ro_mrbuf_tvalid;
   wire [N_DDS_RO*2*16-1:0] axis_ro_mrbuf_tdata;

   // MR capture: arm on first non-zero mrbuf row after the DAC has started
   // producing valid samples. This skips the ADC → DDC transit-time zeros that
   // otherwise appear at the head of mr_out.csv and cause the first pulse's
   // leading edge to look clipped. `axis_sg_dac_tvalid` lives in the sg_clk
   // domain — 2-FF sync it into ro_clk first. The arming flag is combinational
   // so the row that causes arming is also logged.
   logic mr_dac_valid_sync0 = 1'b0;
   logic mr_dac_valid_sync1 = 1'b0;
   logic mr_dac_seen        = 1'b0;
   logic mr_armed           = 1'b0;
   wire  mr_arm_now = mr_dac_seen && axis_ro_mrbuf_tvalid
                      && (axis_ro_mrbuf_tdata != '0);
   wire  mr_log     = (mr_armed || mr_arm_now) && axis_ro_mrbuf_tvalid
                      && (mr_len > 0) && (mr_rows_logged < mr_len);
   always_ff @(posedge ro_clk) begin
      mr_dac_valid_sync0 <= axis_sg_dac_tvalid;
      mr_dac_valid_sync1 <= mr_dac_valid_sync0;
      if (!mr_dac_seen && mr_dac_valid_sync1) mr_dac_seen <= 1'b1;
      if (!mr_armed && mr_arm_now) mr_armed <= 1'b1;
   end

   always @(posedge ro_clk) begin
      if (mr_log) begin
         $fwrite(mr_csv_fd, "%0t", $realtime);
         for (int i = 0; i < 8; i++)
            $fwrite(mr_csv_fd, ",%0d,%0d",
                    $signed(axis_ro_mrbuf_tdata[16*(2*i)   +: 16]),
                    $signed(axis_ro_mrbuf_tdata[16*(2*i+1) +: 16]));
         $fwrite(mr_csv_fd, "\n");
         mr_rows_logged <= mr_rows_logged + 1;
      end
   end


   //----------------------------------------------------
   // TEST STIMULI — QickEmu replay.
   //----------------------------------------------------

   logic [5:0] AVG_START_REG       = 4 * 0;
   logic [5:0] AVG_ADDR_REG        = 4 * 1;
   logic [5:0] AVG_LEN_REG         = 4 * 2;
   logic [5:0] AVG_DR_START_REG    = 4 * 3;
   logic [5:0] AVG_DR_ADDR_REG     = 4 * 4;
   logic [5:0] AVG_DR_LEN_REG      = 4 * 5;
   logic [5:0] BUF_START_REG       = 4 * 6;
   logic [5:0] BUF_ADDR_REG        = 4 * 7;
   logic [5:0] BUF_LEN_REG         = 4 * 8;
   logic [5:0] BUF_DR_START_REG    = 4 * 9;
   logic [5:0] BUF_DR_ADDR_REG     = 4 * 10;
   logic [5:0] BUF_DR_LEN_REG      = 4 * 11;

   logic [5:0] SG_ADDR_START_ADDR = 6'h00;
   logic [5:0] SG_ADDR_WE         = 6'h04;

   logic         tb_load_mem, tb_load_mem_done;


   initial begin
      #0;  // yield so EMU_DIR plusarg is parsed first

// <<<<<<<<<<<< XILINX VIP PACKAGES

      // // Create agents.
      // axi_mst_tproc_agent  = new("axi_mst_tproc VIP Agent",tb_qick.u_axi_mst_tproc_0.inst.IF);
      // axi_mst_tproc_agent.set_agent_tag("axi_mst_tproc VIP");
      // axi_mst_tproc_agent.start_master();

      // axi_mst_sg_agent   = new("axi_mst_sg_0 VIP Agent",tb_qick.u_axi_mst_sg_0.inst.IF);
      // axi_mst_sg_agent.set_agent_tag("axi_mst_sg_0 VIP");
      // axi_mst_sg_agent.start_master();

      // axi_mst_avg_agent   = new("axi_mst_avg_0 VIP Agent",tb_qick.u_axi_mst_avg_0.inst.IF);
      // axi_mst_avg_agent.set_agent_tag("axi_mst_avg_0 VIP");
      // axi_mst_avg_agent.start_master();

// ============

      // create agents.
      axi_mst_tproc_agent  = new(qick_dut.gen_axi_tproc_emu.axi_mst_tproc_dv_IF,  "axi_mst_tproc VIP Agent" );
      axi_mst_sg_agent     = new(qick_dut.gen_axi_sg_emu.axi_mst_sg_dv_IF,        "axi_mst_sg VIP Agent"    );
      axi_mst_avg_agent    = new(qick_dut.gen_axi_avg_emu.axi_mst_avg_dv_IF,      "axi_mst_avg VIP Agent"   );
      // initialize agent signals to '0.
      axi_mst_tproc_agent.reset();
      axi_mst_sg_agent.reset();
      axi_mst_avg_agent.reset();

// >>>>>>>>>>>> PULP PLATFORM AXI VIP

      $display("*** Start Test ***");

      // INITIAL VALUES
      qnet_dt_i                = '{default:'0} ;
      rst_ni                   = 1'b0;
      s1_axis_tvalid           = 1'b0 ;
      port_1_dt_i              = 0;
      qcom_rdy_i               = 0 ;
      periph_dt_i              = '{default:'0} ;
      qnet_rdy_i               = 0 ;
      qcom_vld_i               = 0 ;
      qcom_flag_i              = 0 ;
      proc_start_i             = 1'b0;
      proc_stop_i              = 1'b0;
      core_start_i             = 1'b0;
      core_stop_i              = 1'b0;
      time_rst_i               = 1'b0;
      time_init_i              = 1'b0;
      time_updt_i              = 1'b0;
      offset_dt_i              = 0 ;

      tb_load_mem              = 1'b0;
      tb_load_mem_done         = 1'b0;

      sg_s0_axis_tvalid        = 0;
      sg_s0_axis_tdata         = 0;

      m1_axis_buf_dec_tready   = 1'b1;
      m_dma_axis_tready_i      = 1'b1;
      s_dma_axis_tdata_i       = 0;
      s_dma_axis_tlast_i       = 0;
      s_dma_axis_tvalid_i      = 0;

      #10ns;

      // Hold Reset
      repeat(16) @ (posedge s_ps_dma_aclk); #0.1ns;
      // Release Reset
      rst_ni = 1'b1;

      #100ns;

      // Load tProc Memories (pmem, wmem, dmem) from EMU_DIR.
      tproc_load_mem_emu(EMU_DIR);

      #1us;

      // Load Signal Generator Envelope Table Memory (sgmem_ch0).
      sg_load_mem_emu(EMU_DIR, 0);

      #1us;

      // Replay captured AXI-Lite writes from QickEmu (axi_replay.txt).
      replay_axi_writes({EMU_DIR, "/axi_replay.txt"});

      $display("### %0t - Start tProc execution ###", $realtime);
      #(TEST_RUN_TIME);
      $display("### %0t - End tProc execution ###", $realtime);


      // READ CAPTURED DATA FROM AVG BUFFER.
      $display("### %0t - Reading avg/dec buffers ###", $realtime);

      @(posedge s_ps_dma_aclk); #0.1;
      axi_mst_avg_agent.write(AVG_DR_LEN_REG,   prot, ro_avg_len,    8'hFF, resp);
      #100ns;
      @(posedge s_ps_dma_aclk); #0.1;
      axi_mst_avg_agent.write(AVG_DR_START_REG, prot, 32'h00000001,  8'hFF, resp);
      #100ns;
      @(posedge s_ps_dma_aclk); #0.1;
      axi_mst_avg_agent.write(AVG_DR_START_REG, prot, 32'h00000000,  8'hFF, resp);
      #1us;

      @(posedge s_ps_dma_aclk); #0.1;
      axi_mst_avg_agent.write(BUF_DR_LEN_REG,   prot, ro_dec_len,    8'hFF, resp);
      #100ns;
      @(posedge s_ps_dma_aclk); #0.1;
      axi_mst_avg_agent.write(BUF_DR_START_REG, prot, 32'h00000001,  8'hFF, resp);
      #100ns;
      @(posedge s_ps_dma_aclk); #0.1;
      axi_mst_avg_agent.write(BUF_DR_START_REG, prot, 32'h00000000,  8'hFF, resp);

      #50us;

      $display("### %0t - Closing CSV files ###", $realtime);
      $fclose(dac_csv_fd);
      $fclose(avg_csv_fd);
      $fclose(dec_csv_fd);
      $fclose(mr_csv_fd);

      $display("*** %0t - End Simulation ***", $realtime);
      $finish();
   end

   //----------------------------------------------------
   // TASKS
   //----------------------------------------------------

   // Load tProc program / waveform / data memories from QickEmu output files.
   task tproc_load_mem_emu(string emu_dir);
      string pmem_file;
      string wmem_file;
      string dmem_file;

      pmem_file = {emu_dir, "/pmem.mem"};
      wmem_file = {emu_dir, "/wmem.mem"};
      dmem_file = {emu_dir, "/dmem.mem"};

      $display("### Loading tproc memories from: %s ###", emu_dir);
      $fflush();

      $readmemh(pmem_file, qick_dut.AXIS_QPROC.QPROC.CORE_0.CORE_MEM.P_MEM.RAM);
      $readmemh(wmem_file, qick_dut.AXIS_QPROC.QPROC.CORE_0.CORE_MEM.W_MEM.RAM);
      $readmemh(dmem_file, qick_dut.AXIS_QPROC.QPROC.CORE_0.CORE_MEM.D_MEM.RAM);

      $display("### VERIFY P_MEM[1] = %h ###", qick_dut.AXIS_QPROC.QPROC.CORE_0.CORE_MEM.P_MEM.RAM[1]);
      $display("### tproc memories loaded ###");
      $fflush();
   endtask

   // Stream a signal generator envelope table into the SG BRAM via sg_s0_axis.
   task sg_load_mem_emu(string emu_dir, int sg_ch);
      string            sg_file;
      integer           fd;
      integer           vali;
      integer           valq;
      bit signed [15:0] ii;
      bit signed [15:0] qq;

      sg_file = $sformatf("%s/sgmem_ch%0d.mem", emu_dir, sg_ch);
      fd = $fopen(sg_file, "r");
      if (fd == 0) begin
         $display("### %0t - SG ch%0d: no envelope file %s ###", $realtime, sg_ch, sg_file);
         return;
      end

      $display("### %0t - Loading SG ch%0d envelope from %s ###", $realtime, sg_ch, sg_file);

      @(posedge s_ps_dma_aclk); #0.1;
      axi_mst_sg_agent.write(SG_ADDR_START_ADDR, prot, 0, 8'hFF, resp);
      #100ns;
      axi_mst_sg_agent.write(SG_ADDR_WE,         prot, 1, 8'hFF, resp);
      #100ns;

      tb_load_mem = 1;
      wait(sg_s0_axis_tready);
      while ($fscanf(fd, "%d,%d", vali, valq) == 2) begin
         ii = vali;
         qq = valq;
         @(posedge sg_s0_axis_aclk);
         sg_s0_axis_tvalid = 1;
         sg_s0_axis_tdata  = {qq, ii};
      end
      $fclose(fd);

      @(posedge sg_s0_axis_aclk);
      sg_s0_axis_tvalid = 0;
      tb_load_mem_done  = 1;
      $display("### %0t - SG ch%0d envelope loaded ###", $realtime, sg_ch);
   endtask

   // Replay QickEmu AXI-Lite write log, one "addr data" hex pair per line.
   task replay_axi_writes(string replay_file);
      integer fd;
      string  line;
      integer addr_val;
      integer data_val;
      integer n_routed = 0;

      fd = $fopen(replay_file, "r");
      if (fd == 0) begin
         $fatal(1, "ERROR: Cannot open AXI replay file: %s", replay_file);
         return;
      end

      while ($fgets(line, fd)) begin
         if (line.len() < 2)        continue;
         if (line.substr(0,0) == "#") continue;
         if ($sscanf(line, "%h %h", addr_val, data_val) == 2) begin
            $display("### replay line #%0d parsed: addr=0x%08X data=0x%08X ###", n_routed, addr_val, data_val);
            $fflush();
            route_and_write(addr_val, data_val);
            n_routed++;
         end else begin
            $display("### replay line skipped (sscanf=0): \"%s\" ###", line);
         end
      end
      $fclose(fd);

      $display("### AXI replay done: %0d transactions replayed ###", n_routed);
      $fflush();
   endtask

   // Dispatch an absolute AXI address to the right VIP agent by address range.
   // Order matters: TPROC exact-range first, then SG range, then AVG range.
   task route_and_write(integer addr, integer data);
      logic [31:0] offset;

      @(posedge s_ps_dma_aclk); #0.1;
      $display("### %0t - Routing AXI write: addr=0x%08X data=0x%08X ###", $realtime, addr, data);
      if (addr >= TPROC_BASE && addr < TPROC_BASE + 32'h10000) begin
         offset = addr - TPROC_BASE;
         axi_mst_tproc_agent.write(offset[7:0], prot, data, 8'hFF, resp);
      end
      else if (addr >= SG_BASE_LO && addr < SG_BASE_HI) begin
         offset = addr & 32'h0000FFFF;
         axi_mst_sg_agent.write(offset[5:0], prot, data, 8'hFF, resp);
      end
      else if (addr >= AVG_BASE_LO && addr < AVG_BASE_HI) begin
         offset = addr & 32'h0000FFFF;
         axi_mst_avg_agent.write(offset[5:0], prot, data, 8'hFF, resp);
      end
      else begin
         $fatal(1, "ERROR: Unrouted AXI write addr=0x%08X data=0x%08X", addr, data);
         $fflush();
      end
   endtask

endmodule
