///////////////////////////////////////////////////////////////////////////////
//  Fermilab National Accelerator Laboratory
///////////////////////////////////////////////////////////////////////////////
// Description: 
//   QickEmu-driven testbench for QICK project — Verilator compatible.
//   Replaces Xilinx VIPs with PULP Platform AXI VIPs.
//   Dynamically replays AXI transactions and loads memories from QickEmu.
//////////////////////////////////////////////////////////////////////////////

`timescale 1ns/1fs

// <<<<<<<<<<<< XILINX VIP PACKAGES
// import axi_vip_pkg::*;
// import axi_mst_0_pkg::*;
// ============
`include "axi/typedef.svh"
`include "axi/assign.svh"
// >>>>>>>>>>>> PULP PLATFORM AXI VIP

// +++++++++++++ ADD PULP PLATFORM AXI RAND MASTER TYPEDEFS
localparam time         ApplTime          =  100ns;
localparam time         TestTime          =  0ns;

typedef axi_test::axi_lite_rand_master #(
   // AXI interface parameters
   .AW ( 32'd40              ), // Axi Address Width
   .DW ( 32'd32              ), // Axi Data Width
   // Stimuli application and test time
   .TA ( ApplTime            ),
   .TT ( TestTime            ),
   .MIN_ADDR ( 40'h0_0000_0000 ),
   .MAX_ADDR ( 40'hf_ffff_ffff ),
   .MAX_READ_TXNS  ( 1 ),
   .MAX_WRITE_TXNS ( 1 ),
   .AX_MIN_WAIT_CYCLES   ( 0   ),
   .AX_MAX_WAIT_CYCLES   ( 0   ),
   .W_MIN_WAIT_CYCLES    ( 0   ),
   .W_MAX_WAIT_CYCLES    ( 0   ),
   .RESP_MIN_WAIT_CYCLES ( 0   ),
   .RESP_MAX_WAIT_CYCLES ( 0   )
) rand_lite_master_addr40_data32_t;

// +++++++++++++

`define T_TCLK_HALF_PERIOD       1.162ns      // Half Clock Period for tProc Dispatcher (430 MHz)
`define T_CCLK_HALF_PERIOD         2.5ns      // Half Clock Period for tProc Core (200 MHz)
`define T_SCLK_HALF_PERIOD         5.0ns      // Half Clock Period for PS & AXI (100 MHz)

`define T_SG_CLK_HALF_PERIOD     0.834669ns      // Half Clock Period for Signal Gens (599.04 MHz)

`define T_RO_CLK_HALF_PERIOD     1.627604ns      // Half Clock Period for Readout (307.2 MHz)


// TPROC PARAMETERS
`define GEN_SYNC         1
`define DUAL_CORE        0
`define IO_CTRL          1
`define DEBUG            3
`define TNET             0
`define QCOM             0
`define CUSTOM_PERIPH    2
`define LFSR             1
`define DIVIDER          1
`define ARITH            1
`define TIME_READ        1
`define FIFO_DEPTH       8
`define PMEM_AW          12 
`define DMEM_AW          14 
`define WMEM_AW          11
`define REG_AW           4 
`define IN_PORT_QTY      2
`define OUT_TRIG_QTY     17
`define OUT_DPORT_QTY    1
`define OUT_DPORT_DW     8
`define OUT_WPORT_QTY    5 

module QICKEmu_harness ();


string TEST_OUT_CONNECTION = "TEST_OUT_LOOPBACK";     // Connect DAC/ADC in Loopback

localparam N_DDS_SG = 16;
localparam N_DDS_RO = 8;

//----------------------------------------------------
// QickEmu Configuration
//----------------------------------------------------
// EMU_DIR is the directory containing memory dumps and axi_replay.txt
// generated by QickEmu.prepare() / export_vivado_files().
//
// Override via plusargs:
//   +EMU_DIR=<path>       — alternate directory for TB inputs/outputs
//   +TEST_RUN_NS=<int>    — override TEST_RUN_TIME (ns)
//   +PRE_RUN_DELAY_NS=<int> — startup delay before AXI replay/program launch (0-100 ns)
//   +RO_AVG_LEN=<int>     — override averaged-readout drain length
//   +RO_DEC_LEN=<int>     — override decimated-readout drain length
//   +TRACE                — enable VCD dump to obj_dir/waveform.vcd
string EMU_DIR       = "../artifacts";
time   TEST_RUN_TIME = 1000ns;
time   WATCHDOG_TIME = TEST_RUN_TIME + 100us;   // margin for simulation to finish gracefully
time   PRE_RUN_DELAY_TIME = 0ns;
int    ro_avg_len    = 1;
int    ro_dec_len    = 32'h039A;
int    mr_len        = 0;          // max ro_clk rows to log into mr_out.csv (0 = disabled)
int    pre_run_delay_ns = -1;


//----------------------------------------------------
// Address Routing
//----------------------------------------------------

// QICKEMU_DUT Address Map
localparam logic [39:0] TPROC_BASE  = 40'h04_0026_0000;  // qick_processor
localparam logic [39:0] BUF0_BASE   = 40'h04_0006_0000;  // axis_avg_buffer_0
localparam logic [39:0] BUF1_BASE   = 40'h04_0007_0000;  // axis_avg_buffer_1
localparam logic [39:0] BUF2_BASE   = 40'h04_0004_0000;  // axis_avg_buffer_2
localparam logic [39:0] RO1_BASE    = 40'h04_0008_0000;  // axis_readout_v2
localparam logic [39:0] PFB_RO_BASE = 40'h04_0009_0000;  // axis_pfb_readout_v3
localparam logic [39:0] SG0_BASE    = 40'h04_001C_0000;  // axis_signal_gen_v6_0
localparam logic [39:0] SG1_BASE    = 40'h04_001D_0000;  // axis_signal_gen_v6_1
localparam logic [39:0] SG2_BASE    = 40'h04_001E_0000;  // axis_signal_gen_v6_2

// AVG_BUFFER Memory Mapped Registers
logic [5:0] AVG_START_REG       = 4 * 0;
logic [5:0] AVG_ADDR_REG        = 4 * 1;
logic [5:0] AVG_LEN_REG         = 4 * 2;
logic [5:0] AVG_DR_START_REG    = 4 * 3;
logic [5:0] AVG_DR_ADDR_REG     = 4 * 4;
logic [5:0] AVG_DR_LEN_REG      = 4 * 5;
logic [5:0] BUF_START_REG       = 4 * 6;
logic [5:0] BUF_ADDR_REG        = 4 * 7;
logic [5:0] BUF_LEN_REG         = 4 * 8;
logic [5:0] BUF_DR_START_REG    = 4 * 9;
logic [5:0] BUF_DR_ADDR_REG     = 4 * 10;
logic [5:0] BUF_DR_LEN_REG      = 4 * 11;

// Signal Generator Memory Mapped Registers
logic [5:0] SG_ADDR_START_ADDR   = 4 * 0;
logic [5:0] SG_ADDR_WE           = 4 * 1;


// VIP Agents

// <<<<<<<<<<<< XILINX AXI VIP
// axi_mst_0_mst_t     axi_mst_agent;
// ============
rand_lite_master_addr40_data32_t axi_mst_agent;
// >>>>>>>>>>>> PULP PLATFORM AXI VIP


// AXI Master VIP variables
// <<<<<<<<<<<< XILINX AXI VIP
// xil_axi_prot_t  prot        = 0;
// xil_axi_resp_t  resp;
// ============
axi_pkg::prot_t prot = 0;
axi_pkg::resp_t resp;
// >>>>>>>>>>>> PULP PLATFORM AXI VIP


//////////////////////////////////////////////////////////////////////////
//  CLK Generation
logic          c_clk, t_clk, s_ps_dma_aclk;

logic [4:0]    dac_fs_gen=0;
logic          dac_fs, sg_clk;

logic [4:0]    adc_fs_gen=0;
logic          adc_fs, ro_clk;

always #(`T_TCLK_HALF_PERIOD) t_clk = ~t_clk;

always #(`T_CCLK_HALF_PERIOD) c_clk = ~c_clk;

always #(`T_SCLK_HALF_PERIOD) s_ps_dma_aclk = ~s_ps_dma_aclk;

always #(`T_SG_CLK_HALF_PERIOD/N_DDS_SG) dac_fs_gen = dac_fs_gen + 'd1;
assign dac_fs  = dac_fs_gen[0];
assign sg_clk  = dac_fs_gen[4];

always #(`T_RO_CLK_HALF_PERIOD/N_DDS_RO) adc_fs_gen = adc_fs_gen + 'd1;
assign adc_fs  = adc_fs_gen[0];
assign ro_clk  = adc_fs_gen[3];


//////////////////////////////////////////////////////////////////////////
//  RST Generation
logic rst_ni;
assign s_ps_dma_aresetn  = rst_ni;

wire  s_ps_dma_aresetn;

//////////////////////////////////////////////////////////////////////////

reg [255 :0]       s_dma_axis_tdata_i   ;
reg                s_dma_axis_tlast_i   ;
reg                s_dma_axis_tvalid_i  ;
reg                m_dma_axis_tready_i  ;
wire [63 :0]       port_0_dt_i          ;
reg [63 :0]        port_1_dt_i          ;


// The emu TB holds these m{1..7}_axis_tready high so the tProc dispatcher's
// unused wave ports don't back-pressure the core.
reg                m1_axis_tready   =1   ;
reg                m2_axis_tready   =1   ;
reg                m3_axis_tready   =1   ;

reg                m5_axis_tready   =1   ;
reg                m6_axis_tready   =1   ;
reg                m7_axis_tready   =1   ;

wire               s_dma_axis_tready_o  ;
wire [255 :0]      m_dma_axis_tdata_o   ;
wire               m_dma_axis_tlast_o   ;
wire               m_dma_axis_tvalid_o  ;

// tProc Interface
wire [167:0]       m1_axis_tdata        ;
wire               m1_axis_tvalid       ;
wire [167:0]       m2_axis_tdata        ;
wire               m2_axis_tvalid       ;
wire [167:0]       m3_axis_tdata        ;
wire               m3_axis_tvalid       ;

wire [167:0]       m5_axis_tdata        ;
wire               m5_axis_tvalid       ;
wire [167:0]       m6_axis_tdata        ;
wire               m6_axis_tvalid       ;
wire [167:0]       m7_axis_tdata        ;
wire               m7_axis_tvalid       ;

wire [`OUT_DPORT_DW-1:0]         port_0_dt_o, port_1_dt_o, port_2_dt_o, port_3_dt_o;


// // QNET Peripheral
// wire                qnet_en_o   ;
// wire  [4 :0]        qnet_op_o   ;
// wire  [31:0]        qnet_a_dt_o ;
// wire  [31:0]        qnet_b_dt_o ;
// wire  [31:0]        qnet_c_dt_o ;
// wire  [31:0]        qnet_d_dt_o ;
// reg                 qnet_rdy_i      ;
// reg  [31 :0]        qnet_dt_i [2]   ;

// // QCOM Peripheral
// wire                qcom_en_o   ;
// wire  [4 :0]        qcom_op_o   ;
// wire  [31:0]        qcom_dt_o   ;
// reg                 qcom_rdy_i      ;
// reg  [31 :0]        qcom_dt_i [2]   ;
// reg                 qcom_vld_i      ;
// reg                 qcom_flag_i     ;

reg  [31 :0]        qp1_dt_i [2]   ;
reg  [31 :0]        qp2_dt_i [2]   ;

wire                periph_en_o   ;
wire  [4 :0]        periph_op_o   ;
wire  [31:0]        periph_a_dt_o ;
wire  [31:0]        periph_b_dt_o ;
wire  [31:0]        periph_c_dt_o ;
wire  [31:0]        periph_d_dt_o ;

reg                periph_rdy_i    ;
reg  [31 :0]       periph_dt_i [2] ;


// reg    s0_axis_tvalid;
reg s1_axis_tvalid ;

// reg [15:0] waves, wtime;
// reg [31:0] axi_dt;


reg proc_start_i, proc_stop_i ;
reg core_start_i, core_stop_i ;
reg time_rst_i, time_init_i;

reg  [47:0] offset_dt_i ;
wire [47:0] t_time_abs_o ;
reg time_updt_i;

wire [31:0] ps_debug_do;

// Q Peripheral A loopback
wire qp1_en_o;
reg qp1_en_r;
reg [31:0] qp1_a_dt_r, qp1_b_dt_r;
wire [31:0] qp1_a_dt_o, qp1_b_dt_o, qp1_c_dt_o, qp1_d_dt_o;
always_ff @ (posedge c_clk) begin 
   qp1_en_r     <= qp1_en_o;
   qp1_a_dt_r   <= qp1_a_dt_o;
   qp1_b_dt_r   <= qp1_b_dt_o;
end
  
wire qp1_rdy_i, qp1_vld_i, qp1_op_o;

assign qp1_rdy_i     = ~qp1_en_r;
assign qp1_dt_i[0]   = qp1_a_dt_r;
assign qp1_dt_i[1]   = qp1_b_dt_r;
assign qp1_vld_i     = qp1_en_r;

wire port_0_vld, qnet_vld_i, qnet_flag_i, periph_flag_i, ext_flag_i;


assign qnet_vld_i      = t_time_abs_o[3]&t_time_abs_o[2]&t_time_abs_o[1] ;
assign qnet_flag_i       = ~t_time_abs_o[5] & ~t_time_abs_o[4] & t_time_abs_o[3] ;
assign periph_flag_i     = ~t_time_abs_o[5] &  t_time_abs_o[4] & t_time_abs_o[3] ;
assign ext_flag_i        =  t_time_abs_o[5] &  t_time_abs_o[4] & t_time_abs_o[3] ;


   // DAC-ADC connections
   logic                      axis_sg0_dac0_tready;
   logic                      axis_sg0_dac0_tvalid;
   logic [N_DDS_SG*16-1:0]    axis_sg0_dac0_tdata;
   logic                      axis_sg1_dac1_tready;
   logic                      axis_sg1_dac1_tvalid;
   logic [N_DDS_SG*16-1:0]    axis_sg1_dac1_tdata;

   // ++++++++++++ Signal Generator 2 (mux8) --> DAC 2 interface
   logic                      axis_sg2_dac2_tready;
   logic                      axis_sg2_dac2_tvalid;
   logic [N_DDS_SG*16-1:0]    axis_sg2_dac2_tdata;
   // ++++++++++++


   logic                      axis_adc0_ro0_tready;
   logic                      axis_adc0_ro0_tvalid;
   logic [N_DDS_RO*16-1:0]    axis_adc0_ro0_tdata;

   logic                      axis_adc1_ro1_tready;
   logic                      axis_adc1_ro1_tvalid;
   logic [N_DDS_RO*16-1:0]    axis_adc1_ro1_tdata;

   logic                      axis_adc2_ro2_tready;
   logic                      axis_adc2_ro2_tvalid;
   logic [N_DDS_RO*16-1:0]    axis_adc2_ro2_tdata;


   wire sg0_s0_axis_aclk = s_ps_dma_aclk;
   logic   [31:0]          sg0_s0_axis_tdata;
   logic                   sg0_s0_axis_tready;
   logic                   sg0_s0_axis_tvalid;

   wire sg1_s0_axis_aclk = s_ps_dma_aclk;
   logic   [31:0]          sg1_s0_axis_tdata;
   logic                   sg1_s0_axis_tready;
   logic                   sg1_s0_axis_tvalid;

   wire    [63:0]    buf0_m0_axis_avg_tdata  = qick_dut.buf0_m0_axis_avg_tdata;
   wire              buf0_m0_axis_avg_tvalid = qick_dut.buf0_m0_axis_avg_tvalid;
   wire              buf0_m0_axis_avg_tlast  = qick_dut.buf0_m0_axis_avg_tlast;

   wire    [31:0]    buf0_m1_axis_dec_tdata  = qick_dut.buf0_m1_axis_dec_tdata;
   wire              buf0_m1_axis_dec_tvalid = qick_dut.buf0_m1_axis_dec_tvalid;
   wire              buf0_m1_axis_dec_tlast  = qick_dut.buf0_m1_axis_dec_tlast;

   // ++++++++++++ axis_readout_v2 buffer 1 signals
   wire    [63:0]    buf1_m0_axis_avg_tdata  = qick_dut.buf1_m0_axis_avg_tdata;
   wire              buf1_m0_axis_avg_tvalid = qick_dut.buf1_m0_axis_avg_tvalid;
   wire              buf1_m0_axis_avg_tlast  = qick_dut.buf1_m0_axis_avg_tlast;

   wire    [31:0]    buf1_m1_axis_dec_tdata  = qick_dut.buf1_m1_axis_dec_tdata;
   wire              buf1_m1_axis_dec_tvalid = qick_dut.buf1_m1_axis_dec_tvalid;
   wire              buf1_m1_axis_dec_tlast  = qick_dut.buf1_m1_axis_dec_tlast;

   // ++++++++++++ pfb_readout_v3 buffer 2 signals
   wire    [63:0]    buf2_m0_axis_avg_tdata  = qick_dut.buf2_m0_axis_avg_tdata;
   wire              buf2_m0_axis_avg_tvalid = qick_dut.buf2_m0_axis_avg_tvalid;
   wire              buf2_m0_axis_avg_tlast  = qick_dut.buf2_m0_axis_avg_tlast;

   wire    [31:0]    buf2_m1_axis_dec_tdata  = qick_dut.buf2_m1_axis_dec_tdata;
   wire              buf2_m1_axis_dec_tvalid = qick_dut.buf2_m1_axis_dec_tvalid;
   wire              buf2_m1_axis_dec_tlast  = qick_dut.buf2_m1_axis_dec_tlast;

    //--------------------------------------
   // QICK DUT
   //--------------------------------------

   qick_dut #(
      // ++++++++++++ ADD EMULATOR PARAMETER
      .EMULATOR         (1'b1),
      // ++++++++++++      
      .N_DDS_SG         (N_DDS_SG        ),
      .N_DDS_RO         (N_DDS_RO        ),
      // tProc Parameters
      .GEN_SYNC         (`GEN_SYNC        ),
      .DUAL_CORE        (`DUAL_CORE       ),
      .IO_CTRL          (`IO_CTRL         ),
      .DEBUG            (`DEBUG           ),
      .TNET             (`TNET            ),
      .QCOM             (`QCOM            ),
      .CUSTOM_PERIPH    (`CUSTOM_PERIPH   ),
      .LFSR             (`LFSR            ),
      .DIVIDER          (`DIVIDER         ),
      .ARITH            (`ARITH           ),
      .TIME_READ        (`TIME_READ       ),
      .FIFO_DEPTH       (`FIFO_DEPTH      ),
      .PMEM_AW          (`PMEM_AW         ),
      .DMEM_AW          (`DMEM_AW         ),
      .WMEM_AW          (`WMEM_AW         ),
      .REG_AW           (`REG_AW          ),
      .IN_PORT_QTY      (`IN_PORT_QTY     ),
      .OUT_TRIG_QTY     (`OUT_TRIG_QTY    ),
      .OUT_DPORT_QTY    (`OUT_DPORT_QTY   ),
      .OUT_DPORT_DW     (`OUT_DPORT_DW    ),
      .OUT_WPORT_QTY    (`OUT_WPORT_QTY   )
   )
   qick_dut (
      // Core, Time and AXI CLK & RST.
      .t_clk               ( t_clk              ) ,
      .t_resetn            ( rst_ni             ) ,
      .c_clk               ( c_clk              ) ,
      .c_resetn            ( rst_ni             ) ,
      .ps_clk              ( s_ps_dma_aclk      ) ,
      .ps_resetn           ( s_ps_dma_aresetn   ) ,
      .sg_clk              ( sg_clk             ) ,
      .sg_resetn           ( rst_ni             ) ,
      .ro_clk              ( ro_clk             ) ,
      .ro_resetn           ( rst_ni             ) ,
      // External Control
      .ext_flag_i          ( ext_flag_i         ) ,
      .proc_start_i        ( proc_start_i       ) ,
      .proc_stop_i         ( proc_stop_i        ) ,
      .core_start_i        ( core_start_i       ) ,
      .core_stop_i         ( core_stop_i        ) ,
      .time_rst_i          ( time_rst_i         ) ,
      .time_init_i         ( time_init_i        ) ,
      .time_updt_i         ( time_updt_i        ) ,
      .time_dt_i           ( offset_dt_i        ) ,
      .t_time_abs_o        ( t_time_abs_o       ) ,
      //QNET
      .qnet_en_o           ( /*qnet_en_o*/      ) ,
      .qnet_op_o           ( /*qnet_op_o*/      ) ,
      .qnet_a_dt_o         ( /*qnet_a_dt_o*/    ) ,
      .qnet_b_dt_o         ( /*qnet_b_dt_o*/    ) ,
      .qnet_c_dt_o         ( /*qnet_c_dt_o*/    ) ,
      .qnet_rdy_i          ( 0 /*qnet_rdy_i   */ ) ,
      .qnet_dt1_i          ( 0 /*qnet_dt_i[0] */ ) ,
      .qnet_dt2_i          ( 0 /*qnet_dt_i[1] */ ) ,
      .qnet_vld_i          ( 0 /*qnet_vld_i   */ ) ,
      .qnet_flag_i         ( 0 /*qnet_flag_i  */ ) ,
      //QCOM
      .qcom_en_o           ( /*qcom_en_o*/      ) ,
      .qcom_op_o           ( /*qcom_op_o*/      ) ,
      .qcom_dt_o           ( /*qcom_dt_o*/      ) ,
      .qcom_rdy_i          ( 0 /*qcom_rdy_i   */) ,
      .qcom_dt1_i          ( 0 /*qcom_dt_i[0] */) ,
      .qcom_dt2_i          ( 0 /*qcom_dt_i[1] */) ,
      .qcom_vld_i          ( 0 /*qcom_vld_i   */) ,
      .qcom_flag_i         ( 0 /*qcom_flag_i  */) ,
      // QP1
      .qp1_en_o           ( qp1_en_o          ) ,
      .qp1_op_o           ( qp1_op_o          ) ,
      .qp1_a_dt_o         ( qp1_a_dt_o        ) ,
      .qp1_b_dt_o         ( qp1_b_dt_o        ) ,
      .qp1_c_dt_o         ( qp1_c_dt_o        ) ,
      .qp1_d_dt_o         ( qp1_d_dt_o        ) ,
      .qp1_rdy_i          ( qp1_rdy_i         ) ,
      .qp1_dt1_i          ( qp1_dt_i[0]       ) ,
      .qp1_dt2_i          ( qp1_dt_i[1]       ) ,
      .qp1_vld_i          ( qp1_vld_i         ) ,
      .qp1_flag_i         ( 1'b0              ) ,
      // QP2 (unused in emu TB — tied off)
      .qp2_en_o           ( /*qp2_en_o   */   ) ,
      .qp2_op_o           ( /*qp2_op_o   */   ) ,
      .qp2_a_dt_o         ( /*qp2_a_dt_o */   ) ,
      .qp2_b_dt_o         ( /*qp2_b_dt_o */   ) ,
      .qp2_c_dt_o         ( /*qp2_c_dt_o */   ) ,
      .qp2_d_dt_o         ( /*qp2_d_dt_o */   ) ,
      .qp2_rdy_i          ( 1'b0              ) ,
      .qp2_dt1_i          ( 32'd0             ) ,
      .qp2_dt2_i          ( 32'd0             ) ,
      .qp2_vld_i          ( 1'b0              ) ,
      // DMA AXIS FOR READ AND WRITE MEMORY
      .s_dma_axis_tdata_i   ( s_dma_axis_tdata_i  ) ,
      .s_dma_axis_tlast_i   ( s_dma_axis_tlast_i  ) ,
      .s_dma_axis_tvalid_i  ( s_dma_axis_tvalid_i ) ,
      .s_dma_axis_tready_o  ( s_dma_axis_tready_o ) ,
      .m_dma_axis_tdata_o   ( m_dma_axis_tdata_o  ) ,
      .m_dma_axis_tlast_o   ( m_dma_axis_tlast_o  ) ,
      .m_dma_axis_tvalid_o  ( m_dma_axis_tvalid_o ) ,
      .m_dma_axis_tready_i  ( m_dma_axis_tready_i ) ,
      // TRIGGERS
      .trig_0_o             (                ),
      .trig_1_o             (                ),
      .trig_2_o             (                ),
      .trig_3_o             (                ),
      .trig_4_o             (                ),
      .trig_5_o             (                ),
      .trig_6_o             (                ),
      .trig_7_o             (                ),
      // OUT DATA PORTS
      .port_0_dt_o          ( port_0_dt_o             ) ,
      .port_1_dt_o          ( port_1_dt_o             ) ,
      .port_2_dt_o          ( port_2_dt_o             ) ,
      .port_3_dt_o          ( port_3_dt_o             ) ,
      // Debug Signals
      .ps_debug_do          ( ),
      .t_debug_do           ( ),
      .t_fifo_do            ( ),
      .c_time_usr_do        ( ),
      .c_debug_do           ( ),
      .c_time_ref_do        ( ),
      .c_port_do            ( ),
      .c_core_do            ( ),

      // PS --> Signal Generator 0 Interface
      .sg0_s0_axis_aclk           (sg0_s0_axis_aclk        ),
      .sg0_s0_axis_aresetn        (s_ps_dma_aresetn        ),
      .sg0_s0_axis_tdata          (sg0_s0_axis_tdata       ),
      .sg0_s0_axis_tvalid         (sg0_s0_axis_tvalid      ),
      .sg0_s0_axis_tready         (sg0_s0_axis_tready      ),

      // PS --> Signal Generator 1 Interface
      .sg1_s0_axis_aclk           (sg1_s0_axis_aclk        ),
      .sg1_s0_axis_aresetn        (s_ps_dma_aresetn        ),
      .sg1_s0_axis_tdata          (sg1_s0_axis_tdata       ),
      .sg1_s0_axis_tvalid         (sg1_s0_axis_tvalid      ),
      .sg1_s0_axis_tready         (sg1_s0_axis_tready      ),

      // Signal Generator 0 --> DAC 0 interface
      .axis_sg0_dac0_tready        (axis_sg0_dac0_tready     ),
      .axis_sg0_dac0_tvalid        (axis_sg0_dac0_tvalid     ),
      .axis_sg0_dac0_tdata         (axis_sg0_dac0_tdata      ),

      // Signal Generator 1 --> DAC 1 interface
      .axis_sg1_dac1_tready        (axis_sg1_dac1_tready     ),
      .axis_sg1_dac1_tvalid        (axis_sg1_dac1_tvalid     ),
      .axis_sg1_dac1_tdata         (axis_sg1_dac1_tdata      ),

      // ++++++++++++ Signal Generator 2 (mux8) --> DAC 2 interface
      .axis_sg2_dac2_tready        (axis_sg2_dac2_tready     ),
      .axis_sg2_dac2_tvalid        (axis_sg2_dac2_tvalid     ),
      .axis_sg2_dac2_tdata         (axis_sg2_dac2_tdata      ),
      // ++++++++++++

      // ADC 0 --> Readout 0 Interface

      .axis_adc0_ro0_tready       (axis_adc0_ro0_tready     ),
      .axis_adc0_ro0_tvalid       (axis_adc0_ro0_tvalid     ),
      .axis_adc0_ro0_tdata        (axis_adc0_ro0_tdata      ),

      // ADC 1 --> Readout 1 Interface
      .axis_adc1_ro1_tready       (axis_adc1_ro1_tready     ),
      .axis_adc1_ro1_tvalid       (axis_adc1_ro1_tvalid     ),
      .axis_adc1_ro1_tdata        (axis_adc1_ro1_tdata      ),

      // ADC 2 --> Readout 2 Interface
      .axis_adc2_ro2_tready       (axis_adc2_ro2_tready     ),
      .axis_adc2_ro2_tvalid       (axis_adc2_ro2_tvalid     ),
      .axis_adc2_ro2_tdata        (axis_adc2_ro2_tdata      )

      // // Readout 0 --> MR Buffer 0 Interface
      // .axis_ro0_mrbuf_tvalid       (axis_ro0_mrbuf_tvalid     ),
      // .axis_ro0_mrbuf_tdata        (axis_ro0_mrbuf_tdata      ),

   );


   //--------------------------------------
   // RF DATA CONVERTER IP (behavioral model — loopback DAC/ADC)
   //--------------------------------------

   //--------------------------------------
   // DAC-ADC RF frontend model
   //--------------------------------------

   // SG0 to DAC0 RF processes 16 samples per clock

   localparam DAC0_W = 16;
   localparam ADC0_W = 16;
   // logic signed [ADC0_W-1:0] adc0_sample;
   real dac0_signal_rf;
   real dac0_signal_rf_dly;
   real dac0_delay_buffer [0:RF_DELAY_CYCLES-1];
   int  dac0_write_ptr = 0;
   int  dac0_read_ptr  = 0;

   initial begin
      dac0_signal_rf_dly = 0.0;
      for (int i = 0; i < RF_DELAY_CYCLES; i++) begin
         dac0_delay_buffer[i] = 0.0;
      end
   end

   model_DAC #(
      .DAC_W               (DAC0_W),
      .N_DDS               (N_DDS_SG)
   ) u_model_DAC0 (
      .clk_DAC             (dac_fs),
      .axis_tvalid         (axis_sg0_dac0_tvalid),
      .axis_tdata          (axis_sg0_dac0_tdata),
      .axis_tready         (axis_sg0_dac0_tready),
      .dac_signal_rf       (dac0_signal_rf)
   );

   model_ADC #(
      .ADC_W               (ADC0_W),
      .BUFFER_SIZE         (16),
      .N_DDS               (N_DDS_RO),
      .ADC_NOISE_STD       (0.002)
   ) u_model_ADC0 (
      .clk_DAC             (dac_fs),
      .dac_signal_rf       (dac0_signal_rf_dly),

      .clk_ADC             (adc_fs),
      // .adc_sample          (adc0_sample),

      .axis_tready         (axis_adc0_ro0_tready),
      .axis_tvalid         (axis_adc0_ro0_tvalid),
      .axis_tdata          (axis_adc0_ro0_tdata),

      .mode                (1)   // 0 = ZOH, 1 = linear
   );


   localparam DAC1_W = 16;
   localparam ADC1_W = 16;
   // logic signed [ADC1_W-1:0] adc1_sample;
   real dac1_signal_rf;
   real dac1_signal_rf_dly;

   real dac1_delay_buffer [0:RF_DELAY_CYCLES-1];
   int  dac1_write_ptr = 0;
   int  dac1_read_ptr  = 0;

   initial begin
      dac1_signal_rf_dly = 0.0;
      for (int i = 0; i < RF_DELAY_CYCLES; i++) begin
         dac1_delay_buffer[i] = 0.0;
      end
   end


   model_DAC #(
      .DAC_W               (DAC1_W),
      .N_DDS               (N_DDS_SG)
   ) u_model_DAC1 (
      .clk_DAC             (dac_fs),
      .axis_tvalid         (axis_sg1_dac1_tvalid),
      .axis_tdata          (axis_sg1_dac1_tdata),
      .axis_tready         (axis_sg1_dac1_tready),
      .dac_signal_rf       (dac1_signal_rf)
   );

   model_ADC #(
      .ADC_W               (ADC1_W),
      .BUFFER_SIZE         (16),
      .N_DDS               (N_DDS_RO)
   ) u_model_ADC1 (
      .clk_DAC             (dac_fs),
      .dac_signal_rf       (dac1_signal_rf_dly),

      .clk_ADC             (adc_fs),
      // .adc_sample          (adc1_sample),

      .axis_tready         (axis_adc1_ro1_tready),
      .axis_tvalid         (axis_adc1_ro1_tvalid),
      .axis_tdata          (axis_adc1_ro1_tdata),

      .mode                (1)   // 0 = ZOH, 1 = linear
   );

   // SG1 to DAC1 RF processes 16 samples per clock


   // ++++++++++++ SG2 (mux8) to DAC2 model — capture-only, no ADC loopback path.
   localparam DAC2_W = 16;
   real dac2_signal_rf;

   model_DAC #(
      .DAC_W               (DAC2_W),
      .N_DDS               (N_DDS_SG)
   ) u_model_DAC2 (
      .clk_DAC             (dac_fs),
      .axis_tvalid         (axis_sg2_dac2_tvalid),
      .axis_tdata          (axis_sg2_dac2_tdata),
      .axis_tready         (axis_sg2_dac2_tready),
      .dac_signal_rf       (dac2_signal_rf)
   );
   // ++++++++++++

   model_ADC #(
      .ADC_W               (ADC0_W),
      .BUFFER_SIZE         (16),
      .N_DDS               (N_DDS_RO),
      .ADC_NOISE_STD       (0.002)
   ) u_model_ADC2 (
      .clk_DAC             (dac_fs),
      // .dac_signal_rf       (dac2_signal_rf_dly),
      .dac_signal_rf       (dac2_signal_rf),

      .clk_ADC             (adc_fs),
      // .adc_sample          (),

      .axis_tready         (axis_adc2_ro2_tready),
      .axis_tvalid         (axis_adc2_ro2_tvalid),
      .axis_tdata          (axis_adc2_ro2_tdata),

      .mode                (1)   // 0 = ZOH, 1 = linear
   );



   // Model transport delay between DAC0 and ADC0.

   localparam RF_DELAY_TIME_NS = 100;
   localparam int RF_DELAY_CYCLES = $ceil(RF_DELAY_TIME_NS / (2.0*`T_SG_CLK_HALF_PERIOD/N_DDS_SG));

   always @(posedge dac_fs) begin
      dac0_delay_buffer[dac0_write_ptr] <= dac0_signal_rf;
      if (dac0_write_ptr == RF_DELAY_CYCLES - 1) begin
         dac0_write_ptr <= 0;
      end else begin
         dac0_write_ptr <= dac0_write_ptr + 1;
      end
      dac0_signal_rf_dly <= dac0_delay_buffer[dac0_read_ptr];
      if (dac0_read_ptr == RF_DELAY_CYCLES - 1) begin
         dac0_read_ptr <= 0;
      end else begin
         dac0_read_ptr <= dac0_read_ptr + 1;
      end
   end

   // Model transport delay between DAC1 and ADC1.

   always @(posedge dac_fs) begin
      dac1_delay_buffer[dac1_write_ptr] <= dac1_signal_rf;
      if (dac1_write_ptr == RF_DELAY_CYCLES - 1) begin
         dac1_write_ptr <= 0;
      end else begin
         dac1_write_ptr <= dac1_write_ptr + 1;
      end
      dac1_signal_rf_dly <= dac1_delay_buffer[dac1_read_ptr];
      if (dac1_read_ptr == RF_DELAY_CYCLES - 1) begin
         dac1_read_ptr <= 0;
      end else begin
         dac1_read_ptr <= dac1_read_ptr + 1;
      end
   end

   // //--------------------------------------
   // // WIP: Qubit Emulator
   // //--------------------------------------

   // wire  [7:0]       s_axi_qemu_araddr;
   // wire  [2:0]       s_axi_qemu_arprot;
   // wire              s_axi_qemu_arready;
   // wire              s_axi_qemu_arvalid;
   // wire  [7:0]       s_axi_qemu_awaddr;
   // wire  [2:0]       s_axi_qemu_awprot;
   // wire              s_axi_qemu_awready;
   // wire              s_axi_qemu_awvalid;
   // wire              s_axi_qemu_bready;
   // wire  [1:0]       s_axi_qemu_bresp;
   // wire              s_axi_qemu_bvalid;
   // wire  [31:0]      s_axi_qemu_rdata;
   // wire              s_axi_qemu_rready;
   // wire  [1:0]       s_axi_qemu_rresp;
   // wire              s_axi_qemu_rvalid;
   // wire  [31:0]      s_axi_qemu_wdata;
   // wire              s_axi_qemu_wready;
   // wire  [3:0]       s_axi_qemu_wstrb;
   // wire              s_axi_qemu_wvalid;
   
   // // AXI VIP master address.
   // xil_axi_ulong   QEMU_DDS_BVAL_REG     = 4 * 0;
   // xil_axi_ulong   QEMU_DDS_SLOPE_REG    = 4 * 1;
   // xil_axi_ulong   QEMU_DDS_STEPS_REG    = 4 * 2;
   // xil_axi_ulong   QEMU_DDS_WAIT_REG     = 4 * 3;
   // xil_axi_ulong   QEMU_DDS_FREQ_REG     = 4 * 4;
   // xil_axi_ulong   QEMU_IIR_C0_REG       = 4 * 5;
   // xil_axi_ulong   QEMU_IIR_C1_REG       = 4 * 6;
   // xil_axi_ulong   QEMU_IIR_G_REG        = 4 * 7;
   // xil_axi_ulong   QEMU_OUTSEL_REG       = 4 * 8;
   // xil_axi_ulong   QEMU_PUNCT_ID_REG     = 4 * 9;
   // xil_axi_ulong   QEMU_ADDR_REG         = 4 * 10;
   // xil_axi_ulong   QEMU_WE_REG           = 4 * 11;

   // localparam L = 1;
   // wire              axis_qemu_ro_tvalid;
   // wire [L*2*16-1:0] axis_qemu_ro_tdata;

   // axi_mst_0 u_axi_mst_qemu_0 (
   //    .aclk          (s_ps_dma_aclk       ),
   //    .aresetn       (s_ps_dma_aresetn    ),
   //    .m_axi_araddr  (s_axi_qemu_araddr    ),
   //    .m_axi_arprot  (s_axi_qemu_arprot    ),
   //    .m_axi_arready (s_axi_qemu_arready   ),
   //    .m_axi_arvalid (s_axi_qemu_arvalid   ),
   //    .m_axi_awaddr  (s_axi_qemu_awaddr    ),
   //    .m_axi_awprot  (s_axi_qemu_awprot    ),
   //    .m_axi_awready (s_axi_qemu_awready   ),
   //    .m_axi_awvalid (s_axi_qemu_awvalid   ),
   //    .m_axi_bready  (s_axi_qemu_bready    ),
   //    .m_axi_bresp   (s_axi_qemu_bresp     ),
   //    .m_axi_bvalid  (s_axi_qemu_bvalid    ),
   //    .m_axi_rdata   (s_axi_qemu_rdata     ),
   //    .m_axi_rready  (s_axi_qemu_rready    ),
   //    .m_axi_rresp   (s_axi_qemu_rresp     ),
   //    .m_axi_rvalid  (s_axi_qemu_rvalid    ),
   //    .m_axi_wdata   (s_axi_qemu_wdata     ),
   //    .m_axi_wready  (s_axi_qemu_wready    ),
   //    .m_axi_wstrb   (s_axi_qemu_wstrb     ),
   //    .m_axi_wvalid  (s_axi_qemu_wvalid    )
   // );

   // axis_kidsim_v3 #(
   //    .L                      (L)   // Number of lanes.
   // )
   // u_axis_kidsim_v3 (
   //    // AXI Slave I/F for configuration.
   //    .s_axi_aclk             (s_ps_dma_aclk       ),
   //    .s_axi_aresetn          (s_ps_dma_aresetn    ),
   //    .s_axi_araddr           (s_axi_qemu_araddr   ),
   //    .s_axi_arprot           (s_axi_qemu_arprot   ),
   //    .s_axi_arready          (s_axi_qemu_arready  ),
   //    .s_axi_arvalid          (s_axi_qemu_arvalid  ),
   //    .s_axi_awaddr           (s_axi_qemu_awaddr   ),
   //    .s_axi_awprot           (s_axi_qemu_awprot   ),
   //    .s_axi_awready          (s_axi_qemu_awready  ),
   //    .s_axi_awvalid          (s_axi_qemu_awvalid  ),
   //    .s_axi_bready           (s_axi_qemu_bready   ),
   //    .s_axi_bresp            (s_axi_qemu_bresp    ),
   //    .s_axi_bvalid           (s_axi_qemu_bvalid   ),
   //    .s_axi_rdata            (s_axi_qemu_rdata    ),
   //    .s_axi_rready           (s_axi_qemu_rready   ),
   //    .s_axi_rresp            (s_axi_qemu_rresp    ),
   //    .s_axi_rvalid           (s_axi_qemu_rvalid   ),
   //    .s_axi_wdata            (s_axi_qemu_wdata    ),
   //    .s_axi_wready           (s_axi_qemu_wready   ),
   //    .s_axi_wstrb            (s_axi_qemu_wstrb    ),
   //    .s_axi_wvalid           (s_axi_qemu_wvalid   ),

   //    // Modulation trigger.
   //    .trigger                (trigger_0           ),

   //    // Reset and clock for axis_*.
   //    .aresetn                (s_ps_dma_aresetn    ),
   //    .aclk                   (adc_fs             ),

   //    // s_axis_* for input.
   //    .s_axis_tvalid          (1'b1),
   //    // .s_axis_tdata           ({adc_data_imag,adc_data_real}),   // width: 32*L, should be I/Q from input ADC
   //    .s_axis_tdata           ({16'd0,adc_data}),   // width: 32*L, should be I/Q from input ADC
   //    .s_axis_tlast           (1'b1),

   //    // m_axis_* for output.
   //    .m_axis_tvalid          (axis_qemu_ro_tvalid ),
   //    .m_axis_tdata           (axis_qemu_ro_tdata  ),   // width: 32*L, should be I/Q to output DAC
   //    .m_axis_tlast           ()
   // );



   // SIMULATION WATCHDOG
   initial begin
      #1;
      $display("WATCHDOG Enabled: Simulation will terminate after %0d ns", WATCHDOG_TIME);
      #(WATCHDOG_TIME);
      $fatal(1, "WATCHDOG: Simulation time limit reached. Terminating.");
   end


   // ++++++++++++ TELL VERILATOR TO LOG SIGNALS IN VCD FILE (opt-in via +TRACE)
   initial begin
      #1;
      if ($test$plusargs("TRACE")) begin
         string vcd_file;
         vcd_file = {EMU_DIR, "/waveform.vcd"};
         $dumpfile(vcd_file);
         // $dumpvars(0, tb_qick_emu_verilator);
         $dumpvars(0, QICKEmu_harness);
         $display("### TRACE Enabled: VCD dump enabled. Output file: %s", vcd_file);
      end
   end
   // ++++++++++++

   // -----------------------------------------------------------------------------
   // EMU_DIR plusarg.
   //
   // Must run before any $fopen / $readmemh that uses EMU_DIR. Also parses
   // TEST_RUN_NS / RO_AVG_LEN / RO_DEC_LEN plusargs so the notebook driver
   // can sweep these without recompiling.
   // -----------------------------------------------------------------------------
   initial begin
      int t_ns;
      int d_ns;

      if (!$value$plusargs("EMU_DIR=%s", EMU_DIR))
         $display("### Using default EMU_DIR=%s ###", EMU_DIR);
      else
         $display("### EMU_DIR set to %s via plusarg ###", EMU_DIR);

      if ($value$plusargs("TEST_RUN_NS=%d", t_ns)) begin
         TEST_RUN_TIME = t_ns * 1ns;
         $display("### TEST_RUN_TIME overridden to %0d ns ###", t_ns);
      end

      if ($value$plusargs("PRE_RUN_DELAY_NS=%d", d_ns)) begin
         if (d_ns < 0) d_ns = 0;
         if (d_ns > 100) d_ns = 100;
         pre_run_delay_ns = d_ns;
         $display("### PRE_RUN_DELAY_NS overridden to %0d ns ###", pre_run_delay_ns);
      end
      else begin
         pre_run_delay_ns = $urandom_range(0, 100);
         $display("### PRE_RUN_DELAY_NS randomized to %0d ns ###", pre_run_delay_ns);
      end
      PRE_RUN_DELAY_TIME = pre_run_delay_ns * 1ns;

      if ($value$plusargs("RO_AVG_LEN=%d", ro_avg_len))
         $display("### RO_AVG_LEN overridden to %0d via plusarg ###", ro_avg_len);

      if ($value$plusargs("RO_DEC_LEN=%d", ro_dec_len))
         $display("### RO_DEC_LEN overridden to %0d via plusarg ###", ro_dec_len);

      if ($value$plusargs("MR_LEN=%d", mr_len))
         $display("### MR_LEN overridden to %0d via plusarg ###", mr_len);

      $fflush();
   end

   // -----------------------------------------------------------------------------
   // CSV Output Logging.
   //
   // dacN_out.csv — one row per sg_clk with axis_sg0_dacN_tvalid, N_DDS lanes.
   // avgN_out.csv — one row per averaged I/Q sample from avgN_buffer m0.
   // decN_out.csv — one row per decimated I/Q sample from avgN_buffer m1.
   // mr_out.csv  — one row per ro_clk while axis_ro0_mrbuf_tvalid, 8 I/Q lanes
   //               (post-downconversion, pre-FIR). Capped by +MR_LEN plusarg.
   // -----------------------------------------------------------------------------
   integer dac0_csv_fd;
   integer dac1_csv_fd;
   integer dac2_csv_fd;   // ++++++++++++ mux8 SG2 -> DAC2 capture
   integer avg0_csv_fd;
   integer avg1_csv_fd;   // ++++++++++++ axis_readout_v2 buffer 1
   integer avg2_csv_fd;   // ++++++++++++ axis_avg_buffer_2 (PFB v3 downstream)
   integer dec0_csv_fd;
   integer dec1_csv_fd;   // ++++++++++++ axis_readout_v2 buffer 1
   integer dec2_csv_fd;   // ++++++++++++ axis_avg_buffer_2 (PFB v3 downstream)
   integer mr_csv_fd;
   int     mr_rows_logged = 0;

   initial begin
      string dac0_csv_path;
      string dac1_csv_path;
      string dac2_csv_path;
      string avg0_csv_path;
      string avg1_csv_path;   // ++++++++++++ axis_readout_v2 buffer 1
      string avg2_csv_path;   // ++++++++++++ axis_avg_buffer_2 (PFB v3 downstream)
      string dec0_csv_path;
      string dec1_csv_path;   // ++++++++++++ axis_readout_v2 buffer 1
      string dec2_csv_path;
      string mr_csv_path;

      // Print times in ps
      $timeformat(-12, 3);

      #0;  // yield so the plusarg initial block runs first

      dac0_csv_path = {EMU_DIR, "/dac_out_ch0.csv"};
      dac1_csv_path = {EMU_DIR, "/dac_out_ch1.csv"};
      dac2_csv_path = {EMU_DIR, "/dac_out_ch2.csv"};   // ++++++++++++ mux8 SG2 -> DAC2 capture
      avg0_csv_path = {EMU_DIR, "/avg_out_ch0.csv"};
      avg1_csv_path = {EMU_DIR, "/avg_out_ch1.csv"};   // ++++++++++++ axis_readout_v2 buffer 1
      avg2_csv_path = {EMU_DIR, "/avg_out_ch2.csv"};   // ++++++++++++ axis_avg_buffer_2 (PFB v3 downstream)
      dec0_csv_path = {EMU_DIR, "/dec_out_ch0.csv"};
      dec1_csv_path = {EMU_DIR, "/dec_out_ch1.csv"};   // ++++++++++++ axis_readout_v2 buffer 1
      dec2_csv_path = {EMU_DIR, "/dec_out_ch2.csv"};   // ++++++++++++ axis_avg_buffer_2 (PFB v3 downstream)
      mr_csv_path  = {EMU_DIR, "/mr_out.csv"};

      dac0_csv_fd = $fopen(dac0_csv_path, "w");
      dac1_csv_fd = $fopen(dac1_csv_path, "w");
      dac2_csv_fd = $fopen(dac2_csv_path, "w");   // ++++++++++++ mux8 SG2 -> DAC2 capture
      avg0_csv_fd = $fopen(avg0_csv_path, "w");
      avg1_csv_fd = $fopen(avg1_csv_path, "w");   // ++++++++++++ axis_readout_v2 buffer 1
      avg2_csv_fd = $fopen(avg2_csv_path, "w");   // ++++++++++++ axis_avg_buffer_2 (PFB v3 downstream)
      dec0_csv_fd = $fopen(dec0_csv_path, "w");
      dec1_csv_fd = $fopen(dec1_csv_path, "w");   // ++++++++++++ axis_readout_v2 buffer 1
      dec2_csv_fd = $fopen(dec2_csv_path, "w");   // ++++++++++++ axis_avg_buffer_2 (PFB v3 downstream)
      mr_csv_fd  = $fopen(mr_csv_path, "w");

      // Signal Generators
      $fwrite(dac0_csv_fd, "time_ps");
      for (int i = 0; i < N_DDS_SG; i++) $fwrite(dac0_csv_fd, ",s%0d", i);
      $fwrite(dac0_csv_fd, "\n");
      $fwrite(dac1_csv_fd, "time_ps");
      for (int i = 0; i < N_DDS_SG; i++) $fwrite(dac1_csv_fd, ",s%0d", i);
      $fwrite(dac1_csv_fd, "\n");
      $fwrite(dac2_csv_fd, "time_ps");   // ++++++++++++ mux8 SG2 -> DAC2 capture
      for (int i = 0; i < N_DDS_SG; i++) $fwrite(dac2_csv_fd, ",s%0d", i);   // ++++++++++++ mux8 SG2 -> DAC2 capture
      $fwrite(dac2_csv_fd, "\n");   // ++++++++++++ mux8 SG2 -> DAC2 capture

      // Readouts
      $fwrite(avg0_csv_fd, "time_ps,I,Q\n");
      $fwrite(dec0_csv_fd, "time_ps,I,Q\n");
      $fwrite(avg1_csv_fd, "time_ps,I,Q\n");
      $fwrite(dec1_csv_fd, "time_ps,I,Q\n");
      $fwrite(avg2_csv_fd, "time_ps,I,Q\n");   // ++++++++++++ axis_avg_buffer_2 (PFB v3 downstream)
      $fwrite(dec2_csv_fd, "time_ps,I,Q\n");   // ++++++++++++ axis_avg_buffer_2 (PFB v3 downstream)

      // MR Buffer
      $fwrite(mr_csv_fd, "time_ps");
      for (int i = 0; i < 8; i++) $fwrite(mr_csv_fd, ",I%0d,Q%0d", i, i);
      $fwrite(mr_csv_fd, "\n");
   end

   always @(posedge sg_clk) begin
      if (axis_sg0_dac0_tvalid) begin
         $fwrite(dac0_csv_fd, "%0t", $realtime);
         for (int i = 0; i < N_DDS_SG; i++)
            $fwrite(dac0_csv_fd, ",%0d", $signed(axis_sg0_dac0_tdata[16*i +: 16]));
         $fwrite(dac0_csv_fd, "\n");
      end
   end

   always @(posedge sg_clk) begin
      if (axis_sg1_dac1_tvalid) begin
         $fwrite(dac1_csv_fd, "%0t", $realtime);
         for (int i = 0; i < N_DDS_SG; i++)
            $fwrite(dac1_csv_fd, ",%0d", $signed(axis_sg1_dac1_tdata[16*i +: 16]));
         $fwrite(dac1_csv_fd, "\n");
      end
   end

   // ++++++++++++ mux8 SG2 -> DAC2 capture logging
   always @(posedge sg_clk) begin
      if (axis_sg2_dac2_tvalid) begin
         $fwrite(dac2_csv_fd, "%0t", $realtime);
         for (int i = 0; i < N_DDS_SG; i++)
            $fwrite(dac2_csv_fd, ",%0d", $signed(axis_sg2_dac2_tdata[16*i +: 16]));
         $fwrite(dac2_csv_fd, "\n");
      end
   end
   // ++++++++++++ mux8 SG2 -> DAC2 capture logging

   always @(posedge s_ps_dma_aclk) begin
      if (buf0_m0_axis_avg_tvalid)
         $fwrite(avg0_csv_fd, "%0t,%0d,%0d\n", $realtime,
                 $signed(buf0_m0_axis_avg_tdata[31:0]),
                 $signed(buf0_m0_axis_avg_tdata[63:32]));
   end

   always @(posedge s_ps_dma_aclk) begin
      if (buf0_m1_axis_dec_tvalid)
         $fwrite(dec0_csv_fd, "%0t,%0d,%0d\n", $realtime,
                 $signed(buf0_m1_axis_dec_tdata[15:0]),
                 $signed(buf0_m1_axis_dec_tdata[31:16]));
   end

   // ++++++++++++ axis_readout_v2 buffer 1 CSV logging (ch1)
   always @(posedge s_ps_dma_aclk) begin
      if (buf1_m0_axis_avg_tvalid)
         $fwrite(avg1_csv_fd, "%0t,%0d,%0d\n", $realtime,
                 $signed(buf1_m0_axis_avg_tdata[31:0]),
                 $signed(buf1_m0_axis_avg_tdata[63:32]));
   end

   always @(posedge s_ps_dma_aclk) begin
      if (buf1_m1_axis_dec_tvalid)
         $fwrite(dec1_csv_fd, "%0t,%0d,%0d\n", $realtime,
                 $signed(buf1_m1_axis_dec_tdata[15:0]),
                 $signed(buf1_m1_axis_dec_tdata[31:16]));
   end
   // ++++++++++++

   // ++++++++++++ axis_avg_buffer_2 CSV logging (PFB v3 downstream)
   always @(posedge s_ps_dma_aclk) begin
      if (buf2_m0_axis_avg_tvalid)
         $fwrite(avg2_csv_fd, "%0t,%0d,%0d\n", $realtime,
               $signed(buf2_m0_axis_avg_tdata[31:0]),
               $signed(buf2_m0_axis_avg_tdata[63:32]));
   end

   always @(posedge s_ps_dma_aclk) begin
      if (buf2_m1_axis_dec_tvalid)
         $fwrite(dec2_csv_fd, "%0t,%0d,%0d\n", $realtime,
               $signed(buf2_m1_axis_dec_tdata[15:0]),
               $signed(buf2_m1_axis_dec_tdata[31:16]));
   end
   // ++++++++++++

   wire                     axis_ro0_mrbuf_tvalid   = qick_dut.axis_ro0_mrbuf_tvalid;
   wire [N_DDS_RO*2*16-1:0] axis_ro0_mrbuf_tdata    = qick_dut.axis_ro0_mrbuf_tdata;

   // MR capture: arm on first non-zero mrbuf row after the DAC has started
   // producing valid samples. This skips the ADC → DDC transit-time zeros that
   // otherwise appear at the head of mr_out.csv and cause the first pulse's
   // leading edge to look clipped. `axis_sg0_dac0_tvalid` lives in the sg_clk
   // domain — 2-FF sync it into ro_clk first. The arming flag is combinational
   // so the row that causes arming is also logged.
   logic mr_dac_valid_sync0 = 1'b0;
   logic mr_dac_valid_sync1 = 1'b0;
   logic mr_dac_seen        = 1'b0;
   logic mr_armed           = 1'b0;
   wire  mr_arm_now = mr_dac_seen && axis_ro0_mrbuf_tvalid
                      && (axis_ro0_mrbuf_tdata != '0);
   wire  mr_log     = (mr_armed || mr_arm_now) && axis_ro0_mrbuf_tvalid
                      && (mr_len > 0) && (mr_rows_logged < mr_len);

   always_ff @(posedge ro_clk) begin
      mr_dac_valid_sync0 <= axis_sg0_dac0_tvalid;
      mr_dac_valid_sync1 <= mr_dac_valid_sync0;
      if (!mr_dac_seen && mr_dac_valid_sync1) mr_dac_seen <= 1'b1;
      if (!mr_armed && mr_arm_now) mr_armed <= 1'b1;
   end

   always @(posedge ro_clk) begin
      if (mr_log) begin
         $fwrite(mr_csv_fd, "%0t", $realtime);
         for (int i = 0; i < 8; i++)
            $fwrite(mr_csv_fd, ",%0d,%0d",
                    $signed(axis_ro0_mrbuf_tdata[16*(2*i)   +: 16]),
                    $signed(axis_ro0_mrbuf_tdata[16*(2*i+1) +: 16]));
         $fwrite(mr_csv_fd, "\n");
         mr_rows_logged <= mr_rows_logged + 1;
      end
   end


   //----------------------------------------------------
   // TEST STIMULI — QickEmu replay.
   //----------------------------------------------------

   logic         tb_sg_load_mem, tb_sg_load_mem_done;
   logic         tb_buf_read_mem, tb_buf_read_mem_done;


   initial begin
      #0;  // yield so EMU_DIR plusarg is parsed first

// <<<<<<<<<<<< XILINX VIP PACKAGES

      // // Create agents.
      // axi_mst_tproc_agent  = new("axi_mst_tproc VIP Agent",tb_qick.u_axi_mst_tproc_0.inst.IF);
      // axi_mst_tproc_agent.set_agent_tag("axi_mst_tproc VIP");
      // axi_mst_tproc_agent.start_master();

      // axi_mst_sg_agent   = new("axi_mst_sg_0 VIP Agent",tb_qick.u_axi_mst_sg_0.inst.IF);
      // axi_mst_sg_agent.set_agent_tag("axi_mst_sg_0 VIP");
      // axi_mst_sg_agent.start_master();

      // axi_mst_avg_agent   = new("axi_mst_avg_0 VIP Agent",tb_qick.u_axi_mst_avg_0.inst.IF);
      // axi_mst_avg_agent.set_agent_tag("axi_mst_avg_0 VIP");
      // axi_mst_avg_agent.start_master();

// ============

      // create agents.
      axi_mst_agent  = new(qick_dut.axi_mst_IF,    "axi_mst VIP Agent" );

      // initialize agent signals to '0.
      axi_mst_agent.reset();

      // Workaround to fix tracing of AXI interface in Verilator
      qick_dut.axi_mst_IF.ar_addr  = 0;
      qick_dut.axi_mst_IF.ar_prot   = 0;
      qick_dut.axi_mst_IF.ar_valid = 0;
      // qick_dut.axi_mst_IF.ar_ready = 0;
      qick_dut.axi_mst_IF.aw_addr  = 0;
      qick_dut.axi_mst_IF.aw_prot   = 0;
      qick_dut.axi_mst_IF.aw_valid = 0;
      // qick_dut.axi_mst_IF.aw_ready = 0;
      qick_dut.axi_mst_IF.b_resp   = 0;
      qick_dut.axi_mst_IF.b_valid  = 0;
      // qick_dut.axi_mst_IF.b_ready = 0;
      // qick_dut.axi_mst_IF.r_resp   = 0;
      // qick_dut.axi_mst_IF.r_valid  = 0;
      // qick_dut.axi_mst_IF.r_data   = 0;
      qick_dut.axi_mst_IF.r_ready = 0;
      qick_dut.axi_mst_IF.w_data   = 0;
      qick_dut.axi_mst_IF.w_strb   = 0;
      qick_dut.axi_mst_IF.w_valid = 0;
      // qick_dut.axi_mst_IF.w_ready = 0;

// >>>>>>>>>>>> PULP PLATFORM AXI VIP

      $display("%0t - Start Emulation", $realtime);

      // INITIAL VALUES
      rst_ni                   = 1'b0;

      s1_axis_tvalid           = 1'b0;

      port_1_dt_i              = 0;
      periph_dt_i              = '{default:'0} ;

      proc_start_i             = 1'b0;
      proc_stop_i              = 1'b0;
      core_start_i             = 1'b0;
      core_stop_i              = 1'b0;
      time_rst_i               = 1'b0;
      time_init_i              = 1'b0;
      time_updt_i              = 1'b0;
      offset_dt_i              = 0 ;

      tb_sg_load_mem           = 1'b0;
      tb_sg_load_mem_done      = 1'b0;

      tb_buf_read_mem          = 1'b0;
      tb_buf_read_mem_done     = 1'b0;

      sg0_s0_axis_tvalid       = 0;
      sg0_s0_axis_tdata        = 0;
      sg1_s0_axis_tvalid       = 0;
      sg1_s0_axis_tdata        = 0;

      m_dma_axis_tready_i      = 1'b1;
      s_dma_axis_tdata_i       = 0;
      s_dma_axis_tlast_i       = 0;
      s_dma_axis_tvalid_i      = 0;

      #10ns;

      // Hold Reset
      repeat(16) @ (posedge s_ps_dma_aclk); #0.1ns;
      // Release Reset
      rst_ni = 1'b1;

      #100ns;

      // Load tProc Memories (pmem, wmem, dmem) from EMU_DIR.
      $display("%0t - Load tProc Memories", $realtime);
      tproc_load_mem_emu(EMU_DIR);

      #1us;

      // Load Signal Generator Envelope Table Memories.
      $display("%0t - Load SGs Envelope Table Memories", $realtime);
      tb_sg_load_mem = 1'b1;

      sg_load_mem(EMU_DIR);

      tb_sg_load_mem_done = 1'b1;
      
      #1us;

      $display("%0t - Applying pre-run startup delay of %0d ns", $realtime, pre_run_delay_ns);
      #(PRE_RUN_DELAY_TIME);

      // Replay captured AXI-Lite writes from QickEmu (axi_replay.txt).
      $display("%0t - Replaying AXI Writes from axi_replay.txt", $realtime);
      replay_axi_writes({EMU_DIR, "/axi_replay.txt"});


      $display("%0t - Start tProc execution", $realtime);
      $fflush();
      fork
         begin
            forever begin
               #10us;
               $display("   %0t - tProc execution in progress", $realtime);
               $fflush();
            end
         end

         begin
            #(TEST_RUN_TIME);
         end
      join_any
      disable fork;
      $display("%0t - End tProc execution", $realtime);


      $display("%0t - Read Average and Decimation Buffers", $realtime);
      tb_buf_read_mem = 1'b1;

      read_avg_dec_buffers(0);
      read_avg_dec_buffers(1);
      read_avg_dec_buffers(2);

      #50us;

      tb_buf_read_mem_done = 1'b1;

      $display("%0t - Closing CSV files", $realtime);
      $fclose(dac0_csv_fd);
      $fclose(dac1_csv_fd);
      $fclose(dac2_csv_fd);   // ++++++++++++ mux8 SG2 -> DAC2 capture
      $fclose(avg0_csv_fd);
      $fclose(avg1_csv_fd);   // ++++++++++++ axis_readout_v2 buffer 1
      $fclose(avg2_csv_fd);   // ++++++++++++ axis_avg_buffer_2 (PFB v3 downstream)
      $fclose(dec0_csv_fd);
      $fclose(dec1_csv_fd);   // ++++++++++++ axis_readout_v2 buffer 1
      $fclose(dec2_csv_fd);   // ++++++++++++ axis_avg_buffer_2 (PFB v3 downstream)
      $fclose(mr_csv_fd);

      $display("%0t - End Emulation", $realtime);
      $finish();
   end

   //----------------------------------------------------
   // TASKS
   //----------------------------------------------------

   task read_avg_dec_buffers(int ro_ch = 0);
      logic [39:0]      buf_base;

      $display("### %0t - Task read_avg_dec_buffers() channel %0d start ###", $realtime(), ro_ch);
      $fflush();

      if (ro_ch >= 3) begin
         $fatal(1, "ERROR: Invalid channel number %0d for read_avg_dec_buffers() task", ro_ch);
         $finish;
      end

      if (ro_ch == 0) begin
         buf_base = BUF0_BASE;
      end
      else if (ro_ch == 1) begin
         buf_base = BUF1_BASE;
      end
      else if (ro_ch == 2) begin
         buf_base = BUF2_BASE;
      end

      @(posedge s_ps_dma_aclk); #0.1;
      axi_mst_agent.write(buf_base + AVG_DR_LEN_REG,   prot, ro_avg_len,    8'hFF, resp);
      #100ns;
      @(posedge s_ps_dma_aclk); #0.1;
      axi_mst_agent.write(buf_base + AVG_DR_START_REG, prot, 32'h00000001,  8'hFF, resp);
      #100ns;
      @(posedge s_ps_dma_aclk); #0.1;
      axi_mst_agent.write(buf_base + AVG_DR_START_REG, prot, 32'h00000000,  8'hFF, resp);


      @(posedge s_ps_dma_aclk); #0.1;
      axi_mst_agent.write(buf_base + BUF_DR_LEN_REG,   prot, ro_dec_len,    8'hFF, resp);
      #100ns;
      @(posedge s_ps_dma_aclk); #0.1;
      axi_mst_agent.write(buf_base + BUF_DR_START_REG, prot, 32'h00000001,  8'hFF, resp);
      #100ns;
      @(posedge s_ps_dma_aclk); #0.1;
      axi_mst_agent.write(buf_base + BUF_DR_START_REG, prot, 32'h00000000,  8'hFF, resp);

      $display("### %0t - Task read_avg_dec_buffers() channel %0d end ###", $realtime(), ro_ch);
      $fflush();
   endtask

   // Load tProc program / waveform / data memories from QickEmu output files.
   task tproc_load_mem_emu(string emu_dir);
      string pmem_file;
      string wmem_file;
      string dmem_file;

      pmem_file = {emu_dir, "/pmem.mem"};
      wmem_file = {emu_dir, "/wmem.mem"};
      dmem_file = {emu_dir, "/dmem.mem"};

      $display("### %0t - Loading tproc memories from: %s ###", $realtime(), emu_dir);
      $fflush();

      $readmemh(pmem_file, qick_dut.AXIS_QPROC.QPROC.CORE_0.CORE_MEM.P_MEM.RAM);
      $readmemh(wmem_file, qick_dut.AXIS_QPROC.QPROC.CORE_0.CORE_MEM.W_MEM.RAM);
      $readmemh(dmem_file, qick_dut.AXIS_QPROC.QPROC.CORE_0.CORE_MEM.D_MEM.RAM);

      $display("   ### VERIFY P_MEM[1] = %h ###", qick_dut.AXIS_QPROC.QPROC.CORE_0.CORE_MEM.P_MEM.RAM[1]);
      $display("### %0t - tproc memories loaded ###", $realtime());
      $fflush();
   endtask

   // Stream a signal generator envelope table into the SG BRAM via sg_s0_axis.
   // task sg_load_mem(string emu_dir, int sg_ch);
   task sg_load_mem(string emu_dir);
      string            sg_file;
      integer           fd;
      integer           vali;
      integer           valq;
      bit signed [15:0] ii;
      bit signed [15:0] qq;
      logic [39:0]      sg_base;

      $display("### %0t - Task sg_load_mem() start ###", $realtime());
      $fflush();

      for (int sg_ch = 0; sg_ch < 2; sg_ch++) begin

         if (sg_ch == 0) begin
            sg0_s0_axis_tvalid = 0;
            sg0_s0_axis_tdata  = 0;
            sg_base = SG0_BASE;
         end else if (sg_ch == 1) begin
            sg1_s0_axis_tvalid = 0;
            sg1_s0_axis_tdata  = 0;
            sg_base = SG1_BASE;
         end

         sg_file = $sformatf("%s/sgmem_ch%0d.mem", emu_dir, sg_ch);
         fd = $fopen(sg_file, "r");
         if (fd == 0) begin
            $display("   ### %0t - SG ch%0d: no envelope file %s ###", $realtime, sg_ch, sg_file);
            continue;
         end

         $display("   ### %0t - Loading SG ch%0d envelope from %s ###", $realtime, sg_ch, sg_file);

         // Use single agent with router - addresses are automatically routed
         @(posedge s_ps_dma_aclk); #0.1;
         axi_mst_agent.write(sg_base + SG_ADDR_START_ADDR, prot, 0, 8'hFF, resp);
         #100ns;
         axi_mst_agent.write(sg_base + SG_ADDR_WE,         prot, 1, 8'hFF, resp);
         #100ns;

         if (sg_ch == 0) begin
            wait (sg0_s0_axis_tready);
         end else if (sg_ch == 1) begin
            wait (sg1_s0_axis_tready);
         end

         while ($fscanf(fd, "%d,%d", vali, valq) == 2) begin
            ii = vali;
            qq = valq;
            if (sg_ch == 0) begin
               @(posedge sg0_s0_axis_aclk);
               sg0_s0_axis_tvalid    = 1;
               sg0_s0_axis_tdata     = {qq,ii};
            end else if (sg_ch == 1) begin
               @(posedge sg1_s0_axis_aclk);
               sg1_s0_axis_tvalid    = 1;
               sg1_s0_axis_tdata     = {qq,ii};
            end
         end
         $fclose(fd);

         if (sg_ch == 0) begin
            @(posedge sg0_s0_axis_aclk);
            sg0_s0_axis_tvalid    = 0;
         end else if (sg_ch == 1) begin
            @(posedge sg1_s0_axis_aclk);
            sg1_s0_axis_tvalid    = 0;
         end

         $display("   ### %0t - SG ch%0d envelope loaded ###", $realtime, sg_ch);
      end
      $display("### %0t - Task sg_load_mem() end ###", $realtime());
   endtask

   // Replay QickEmu AXI-Lite write log, one "addr data" hex pair per line.
   task replay_axi_writes(string replay_file);
      integer fd;
      string  line;
      logic [39:0] addr_val;
      logic [31:0] data_val;
      integer n_routed = 0;

      fd = $fopen(replay_file, "r");
      if (fd == 0) begin
         $fatal(1, "ERROR: Cannot open AXI replay file: %s", replay_file);
         return;
      end

      $display("### %0t - Task replay_axi_writes() start ###", $realtime());
      $fflush();

      while ($fgets(line, fd)) begin
         if (line.len() < 2)        continue;
         if (line.substr(0,0) == "#") continue;
         if ($sscanf(line, "%h %h", addr_val, data_val) == 2) begin
            $display("   ### replay line #%0d parsed: addr=0x%08X data=0x%08X ###", n_routed, addr_val, data_val);
            $fflush();
            route_and_write(addr_val, data_val);
            n_routed++;
         end else begin
            $display("   ### replay line skipped (sscanf=0): \"%s\" ###", line);
            $fflush();
         end
      end
      $fclose(fd);

      $display("### %0t - AXI replay done: %0d transactions replayed ###", $realtime(), n_routed);
      $fflush();
   endtask

   // Dispatch an absolute AXI address to the router.
   // The router automatically routes transactions based on the address.
   task route_and_write(logic [39:0] addr, logic [31:0] data);
      logic [39:0] offset;

      @(posedge s_ps_dma_aclk); #0.1;
      $display("### %0t - Routing AXI write: addr=0x%08X data=0x%08X ###", $realtime, addr, data);
      
      // Use single agent with router - addresses are automatically routed
      // The router will route transactions to the correct slave based on the address
      offset = addr;
      axi_mst_agent.write(offset, prot, data, 8'hFF, resp);
   endtask

endmodule
