// TPROC PARAMETERS
`define GEN_SYNC         1
`define DUAL_CORE        0
`define IO_CTRL          1
`define DEBUG            3
`define TNET             0
`define QCOM             0
`define CUSTOM_PERIPH    2
`define LFSR             1
`define DIVIDER          1
`define ARITH            1
`define TIME_READ        1
`define FIFO_DEPTH       8
`define PMEM_AW          12 
`define DMEM_AW          14 
`define WMEM_AW          11
`define REG_AW           4 
`define IN_PORT_QTY      1
`define OUT_TRIG_QTY     1
`define OUT_DPORT_QTY    1
`define OUT_DPORT_DW     8
`define OUT_WPORT_QTY    5 

// qick_dut: wrapper module that exposes AXIS_QPROC ports and keeps the AXI link internal
module qick_dut(
   // Core, Time and AXI CLK & RST. (match AXIS_QPROC port names)
   input  logic                t_clk_i,
   input  logic                t_resetn,
   input  logic                c_clk_i,
   input  logic                c_resetn,
   input  logic                ps_clk_i,
   input  logic                ps_resetn,
   // External Control
   input  logic                ext_flag_i,
   input  logic                proc_start_i,
   input  logic                proc_stop_i,
   input  logic                core_start_i,
   input  logic                core_stop_i,
   input  logic                time_rst_i,
   input  logic                time_init_i,
   input  logic                time_updt_i,
   input  logic        [31:0]  time_dt_i,
   output logic        [47:0]  t_time_abs_o,
   output logic                pulse_sync_o,
   // QNET
   output logic                qnet_en_o,
   output logic        [4:0]   qnet_op_o,
   output logic       [31:0]   qnet_a_dt_o,
   output logic       [31:0]   qnet_b_dt_o,
   output logic       [31:0]   qnet_c_dt_o,
   input  logic                qnet_rdy_i,
   input  logic       [31:0]   qnet_dt1_i,
   input  logic       [31:0]   qnet_dt2_i,
   input  logic                qnet_vld_i,
   input  logic                qnet_flag_i,
   // QCOM
   output logic                qcom_en_o,
   output logic        [4:0]   qcom_op_o,
   output logic       [31:0]   qcom_dt_o,
   input  logic                qcom_rdy_i,
   input  logic       [31:0]   qcom_dt1_i,
   input  logic       [31:0]   qcom_dt2_i,
   input  logic                qcom_vld_i,
   input  logic                qcom_flag_i,
   // QP1
   output logic                qp1_en_o,
   output logic        [4:0]   qp1_op_o,
   output logic       [31:0]   qp1_a_dt_o,
   output logic       [31:0]   qp1_b_dt_o,
   output logic       [31:0]   qp1_c_dt_o,
   output logic       [31:0]   qp1_d_dt_o,
   input  logic                qp1_rdy_i,
   input  logic       [31:0]   qp1_dt1_i,
   input  logic       [31:0]   qp1_dt2_i,
   input  logic                qp1_vld_i,
   input  logic                qp1_flag_i,
   // QP2
   output logic                qp2_en_o,
   output logic        [4:0]   qp2_op_o,
   output logic       [31:0]   qp2_a_dt_o,
   output logic       [31:0]   qp2_b_dt_o,
   output logic       [31:0]   qp2_c_dt_o,
   output logic       [31:0]   qp2_d_dt_o,
   input  logic                qp2_rdy_i,
   input  logic       [31:0]   qp2_dt1_i,
   input  logic       [31:0]   qp2_dt2_i,
   input  logic                qp2_vld_i,
   // DMA AXIS FOR READ AND WRITE MEMORY
   input  logic       [255:0]  s_dma_axis_tdata_i,
   input  logic                s_dma_axis_tlast_i,
   input  logic                s_dma_axis_tvalid_i,
   output logic               s_dma_axis_tready_o,
   output logic       [255:0]  m_dma_axis_tdata_o,
   output logic               m_dma_axis_tlast_o,
   output logic               m_dma_axis_tvalid_o,
   input  logic                m_dma_axis_tready_i,
   // AXIS DATA in
   input  logic       [63:0]   s0_axis_tdata,
   input  logic                s0_axis_tvalid,
   output logic               s0_axis_tready,
   input  logic       [63:0]   s1_axis_tdata,
   input  logic                s1_axis_tvalid,
   output logic               s1_axis_tready,
   input  logic       [63:0]   s2_axis_tdata,
   input  logic                s2_axis_tvalid,
   output logic               s2_axis_tready,
   input  logic       [63:0]   s3_axis_tdata,
   input  logic                s3_axis_tvalid,
   output logic               s3_axis_tready,
   input  logic       [63:0]   s4_axis_tdata,
   input  logic                s4_axis_tvalid,
   output logic               s4_axis_tready,
   input  logic       [63:0]   s5_axis_tdata,
   input  logic                s5_axis_tvalid,
   output logic               s5_axis_tready,
   input  logic       [63:0]   s6_axis_tdata,
   input  logic                s6_axis_tvalid,
   output logic               s6_axis_tready,
   input  logic       [63:0]   s7_axis_tdata,
   input  logic                s7_axis_tvalid,
   output logic               s7_axis_tready,
   input  logic       [63:0]   s8_axis_tdata,
   input  logic                s8_axis_tvalid,
   output logic               s8_axis_tready,
   input  logic       [63:0]   s9_axis_tdata,
   input  logic                s9_axis_tvalid,
   output logic               s9_axis_tready,
   input  logic       [63:0]   s10_axis_tdata,
   input  logic                s10_axis_tvalid,
   output logic               s10_axis_tready,
   input  logic       [63:0]   s11_axis_tdata,
   input  logic                s11_axis_tvalid,
   output logic               s11_axis_tready,
   input  logic       [63:0]   s12_axis_tdata,
   input  logic                s12_axis_tvalid,
   output logic               s12_axis_tready,
   input  logic       [63:0]   s13_axis_tdata,
   input  logic                s13_axis_tvalid,
   output logic               s13_axis_tready,
   input  logic       [63:0]   s14_axis_tdata,
   input  logic                s14_axis_tvalid,
   output logic               s14_axis_tready,
   input  logic       [63:0]   s15_axis_tdata,
   input  logic                s15_axis_tvalid,
   output logic               s15_axis_tready,
   // OUT WAVE PORTS
   output logic       [167:0]  m0_axis_tdata,
   output logic               m0_axis_tvalid,
   input  logic                m0_axis_tready,
   output logic       [167:0]  m1_axis_tdata,
   output logic               m1_axis_tvalid,
   input  logic                m1_axis_tready,
   output logic       [167:0]  m2_axis_tdata,
   output logic               m2_axis_tvalid,
   input  logic                m2_axis_tready,
   output logic       [167:0]  m3_axis_tdata,
   output logic               m3_axis_tvalid,
   input  logic                m3_axis_tready,
   output logic       [167:0]  m4_axis_tdata,
   output logic               m4_axis_tvalid,
   input  logic                m4_axis_tready,
   output logic       [167:0]  m5_axis_tdata,
   output logic               m5_axis_tvalid,
   input  logic                m5_axis_tready,
   output logic       [167:0]  m6_axis_tdata,
   output logic               m6_axis_tvalid,
   input  logic                m6_axis_tready,
   output logic       [167:0]  m7_axis_tdata,
   output logic               m7_axis_tvalid,
   input  logic                m7_axis_tready,
   output logic       [167:0]  m8_axis_tdata,
   output logic               m8_axis_tvalid,
   input  logic                m8_axis_tready,
   output logic       [167:0]  m9_axis_tdata,
   output logic               m9_axis_tvalid,
   input  logic                m9_axis_tready,
   output logic       [167:0]  m10_axis_tdata,
   output logic               m10_axis_tvalid,
   input  logic                m10_axis_tready,
   output logic       [167:0]  m11_axis_tdata,
   output logic               m11_axis_tvalid,
   input  logic                m11_axis_tready,
   output logic       [167:0]  m12_axis_tdata,
   output logic               m12_axis_tvalid,
   input  logic                m12_axis_tready,
   output logic       [167:0]  m13_axis_tdata,
   output logic               m13_axis_tvalid,
   input  logic                m13_axis_tready,
   output logic       [167:0]  m14_axis_tdata,
   output logic               m14_axis_tvalid,
   input  logic                m14_axis_tready,
   output logic       [167:0]  m15_axis_tdata,
   output logic               m15_axis_tvalid,
   input  logic                m15_axis_tready,
   ///// TRIGGERS
   output logic               trig_0_o,
   output logic               trig_1_o,
   output logic               trig_2_o,
   output logic               trig_3_o,
   output logic               trig_4_o,
   output logic               trig_5_o,
   output logic               trig_6_o,
   output logic               trig_7_o,
   output logic               trig_8_o,
   output logic               trig_9_o,
   output logic               trig_10_o,
   output logic               trig_11_o,
   output logic               trig_12_o,
   output logic               trig_13_o,
   output logic               trig_14_o,
   output logic               trig_15_o,
   output logic               trig_16_o,
   output logic               trig_17_o,
   output logic               trig_18_o,
   output logic               trig_19_o,
   output logic               trig_20_o,
   output logic               trig_21_o,
   output logic               trig_22_o,
   output logic               trig_23_o,
   output logic               trig_24_o,
   output logic               trig_25_o,
   output logic               trig_26_o,
   output logic               trig_27_o,
   output logic               trig_28_o,
   output logic               trig_29_o,
   output logic               trig_30_o,
   output logic               trig_31_o,
   // OUT DATA PORTS
   output logic       [3:0]    port_0_dt_o,
   output logic       [3:0]    port_1_dt_o,
   output logic       [3:0]    port_2_dt_o,
   output logic       [3:0]    port_3_dt_o,
   // Debug Signals
   output logic       [31:0]   ps_debug_do,
   output logic       [31:0]   t_debug_do,
   output logic       [31:0]   t_fifo_do,
   output logic       [31:0]   c_time_usr_do,
   output logic       [31:0]   c_debug_do,
   output logic       [31:0]   c_time_ref_do,
   output logic       [31:0]   c_proc_do,
   output logic       [31:0]   c_port_do,
   output logic       [31:0]   c_core_do
);

   // Internal AXI-Lite wires (kept inside qick_dut)
   logic  [7:0]    s_axi_awaddr;
   logic  [2:0]    s_axi_awprot;
   logic           s_axi_awvalid;
   logic           s_axi_awready;
   logic  [31:0]   s_axi_wdata;
   logic  [3:0]    s_axi_wstrb;
   logic           s_axi_wvalid;
   logic           s_axi_wready;
   logic  [1:0]    s_axi_bresp;
   logic           s_axi_bvalid;
   logic           s_axi_bready;
   logic  [7:0]    s_axi_araddr;
   logic  [2:0]    s_axi_arprot;
   logic           s_axi_arvalid;
   logic           s_axi_arready;
   logic  [31:0]   s_axi_rdata;
   logic  [1:0]    s_axi_rresp;
   logic           s_axi_rvalid;
   logic           s_axi_rready;

   // Instantiate Axi Master for tproc (connect to internal s_axi_* wires)
   axi_mst_0 u_axi_mst_tproc_0 (
      .aclk          (ps_clk_i     ),
      .aresetn       (ps_resetn    ),
      .m_axi_araddr  (s_axi_araddr ),
      .m_axi_arprot  (s_axi_arprot ),
      .m_axi_arready (s_axi_arready),
      .m_axi_arvalid (s_axi_arvalid),
      .m_axi_awaddr  (s_axi_awaddr ),
      .m_axi_awprot  (s_axi_awprot ),
      .m_axi_awready (s_axi_awready),
      .m_axi_awvalid (s_axi_awvalid),
      .m_axi_bready  (s_axi_bready ),
      .m_axi_bresp   (s_axi_bresp  ),
      .m_axi_bvalid  (s_axi_bvalid ),
      .m_axi_rdata   (s_axi_rdata  ),
      .m_axi_rready  (s_axi_rready ),
      .m_axi_rresp   (s_axi_rresp  ),
      .m_axi_rvalid  (s_axi_rvalid ),
      .m_axi_wdata   (s_axi_wdata  ),
      .m_axi_wready  (s_axi_wready ),
      .m_axi_wstrb   (s_axi_wstrb  ),
      .m_axi_wvalid  (s_axi_wvalid )
   );

   // Instantiate Axis Qick Processor and connect AXI ports to internal wires
   axis_qick_processor #(
      .DUAL_CORE           (  `DUAL_CORE        ) ,
      .GEN_SYNC            (  `GEN_SYNC         ) ,
      .IO_CTRL             (  `IO_CTRL          ) ,
      .DEBUG               (  `DEBUG            ) ,
      .TNET                (  `TNET             ) ,
      .QCOM                (  `QCOM             ) ,
      .CUSTOM_PERIPH       (  `CUSTOM_PERIPH    ) ,
      .LFSR                (  `LFSR             ) ,
      .DIVIDER             (  `DIVIDER          ) ,
      .ARITH               (  `ARITH            ) ,
      .TIME_READ           (  `TIME_READ        ) ,
      .FIFO_DEPTH          (  `FIFO_DEPTH       ) ,
      .PMEM_AW             (  `PMEM_AW          ) ,
      .DMEM_AW             (  `DMEM_AW          ) ,
      .WMEM_AW             (  `WMEM_AW          ) ,
      .REG_AW              (  `REG_AW           ) ,
      .IN_PORT_QTY         (  `IN_PORT_QTY      ) ,
      .OUT_TRIG_QTY        (  `OUT_TRIG_QTY     ) ,
      .OUT_DPORT_QTY       (  `OUT_DPORT_QTY    ) ,
      .OUT_DPORT_DW        (  `OUT_DPORT_DW     ) , 
      .OUT_WPORT_QTY       (  `OUT_WPORT_QTY    ) 
   ) AXIS_QPROC (
      .t_clk_i             ( t_clk_i              ),
      .t_resetn            ( t_resetn             ),
      .c_clk_i             ( c_clk_i              ),
      .c_resetn            ( c_resetn             ),
      .ps_clk_i            ( ps_clk_i             ),
      .ps_resetn           ( ps_resetn            ),
      // External Control
      .ext_flag_i          ( ext_flag_i           ),
      .proc_start_i        ( proc_start_i         ),
      .proc_stop_i         ( proc_stop_i          ),
      .core_start_i        ( core_start_i         ),
      .core_stop_i         ( core_stop_i          ),
      .time_rst_i          ( time_rst_i           ),
      .time_init_i         ( time_init_i          ),
      .time_updt_i         ( time_updt_i          ),
      .time_dt_i           ( time_dt_i            ),
      .t_time_abs_o        ( t_time_abs_o         ),
      .pulse_sync_o        ( pulse_sync_o         ),
      //QNET
      .qnet_en_o           ( qnet_en_o            ),
      .qnet_op_o           ( qnet_op_o            ),
      .qnet_a_dt_o         ( qnet_a_dt_o          ),
      .qnet_b_dt_o         ( qnet_b_dt_o          ),
      .qnet_c_dt_o         ( qnet_c_dt_o          ),
      .qnet_rdy_i          ( qnet_rdy_i           ),
      .qnet_dt1_i          ( qnet_dt1_i           ),
      .qnet_dt2_i          ( qnet_dt2_i           ),
      .qnet_vld_i          ( qnet_vld_i           ),
      .qnet_flag_i         ( qnet_flag_i          ),
      //QCOM
      .qcom_en_o           ( qcom_en_o            ),
      .qcom_op_o           ( qcom_op_o            ),
      .qcom_dt_o           ( qcom_dt_o            ),
      .qcom_rdy_i          ( qcom_rdy_i           ),
      .qcom_dt1_i          ( qcom_dt1_i           ),
      .qcom_dt2_i          ( qcom_dt2_i           ),
      .qcom_vld_i          ( qcom_vld_i           ),
      .qcom_flag_i         ( qcom_flag_i          ),
      // QP1
      .qp1_en_o            ( qp1_en_o             ),
      .qp1_op_o            ( qp1_op_o             ),
      .qp1_a_dt_o          ( qp1_a_dt_o           ),
      .qp1_b_dt_o          ( qp1_b_dt_o           ),
      .qp1_c_dt_o          ( qp1_c_dt_o           ),
      .qp1_d_dt_o          ( qp1_d_dt_o           ),
      .qp1_rdy_i           ( qp1_rdy_i            ),
      .qp1_dt1_i           ( qp1_dt1_i            ),
      .qp1_dt2_i           ( qp1_dt2_i            ),
      .qp1_vld_i           ( qp1_vld_i            ),
      .qp1_flag_i          ( qp1_flag_i           ),
      // QP2
      .qp2_en_o            ( qp2_en_o             ),
      .qp2_op_o            ( qp2_op_o             ),
      .qp2_a_dt_o          ( qp2_a_dt_o           ),
      .qp2_b_dt_o          ( qp2_b_dt_o           ),
      .qp2_c_dt_o          ( qp2_c_dt_o           ),
      .qp2_d_dt_o          ( qp2_d_dt_o           ),
      .qp2_rdy_i           ( qp2_rdy_i            ),
      .qp2_dt1_i           ( qp2_dt1_i            ),
      .qp2_dt2_i           ( qp2_dt2_i            ),
      .qp2_vld_i           ( qp2_vld_i            ),
      // DMA AXIS FOR READ AND WRITE MEMORY
      .s_dma_axis_tdata_i   ( s_dma_axis_tdata_i   ),
      .s_dma_axis_tlast_i   ( s_dma_axis_tlast_i   ),
      .s_dma_axis_tvalid_i  ( s_dma_axis_tvalid_i  ),
      .s_dma_axis_tready_o  ( s_dma_axis_tready_o  ),
      .m_dma_axis_tdata_o   ( m_dma_axis_tdata_o   ),
      .m_dma_axis_tlast_o   ( m_dma_axis_tlast_o   ),
      .m_dma_axis_tvalid_o  ( m_dma_axis_tvalid_o  ),
      .m_dma_axis_tready_i  ( m_dma_axis_tready_i  ),
      // AXI-Lite DATA Slave I/F (connected internally)
      .s_axi_awaddr         ( s_axi_awaddr[7:0]    ),
      .s_axi_awprot         ( s_axi_awprot         ),
      .s_axi_awvalid        ( s_axi_awvalid        ),
      .s_axi_awready        ( s_axi_awready        ),
      .s_axi_wdata          ( s_axi_wdata          ),
      .s_axi_wstrb          ( s_axi_wstrb          ),
      .s_axi_wvalid         ( s_axi_wvalid         ),
      .s_axi_wready         ( s_axi_wready         ),
      .s_axi_bresp          ( s_axi_bresp          ),
      .s_axi_bvalid         ( s_axi_bvalid         ),
      .s_axi_bready         ( s_axi_bready         ),
      .s_axi_araddr         ( s_axi_araddr[7:0]    ),
      .s_axi_arprot         ( s_axi_arprot         ),
      .s_axi_arvalid        ( s_axi_arvalid        ),
      .s_axi_arready        ( s_axi_arready        ),
      .s_axi_rdata          ( s_axi_rdata          ),
      .s_axi_rresp          ( s_axi_rresp          ),
      .s_axi_rvalid         ( s_axi_rvalid         ),
      .s_axi_rready         ( s_axi_rready         ),
      // DATA IN PORTS
      .s0_axis_tdata        ( s0_axis_tdata        ),
      .s0_axis_tvalid       ( s0_axis_tvalid       ),
      .s0_axis_tready       ( s0_axis_tready       ),
      .s1_axis_tdata        ( s1_axis_tdata        ),
      .s1_axis_tvalid       ( s1_axis_tvalid       ),
      .s1_axis_tready       ( s1_axis_tready       ),
      .s2_axis_tdata        ( s2_axis_tdata        ),
      .s2_axis_tvalid       ( s2_axis_tvalid       ),
      .s2_axis_tready       ( s2_axis_tready       ),
      .s3_axis_tdata        ( s3_axis_tdata        ),
      .s3_axis_tvalid       ( s3_axis_tvalid       ),
      .s3_axis_tready       ( s3_axis_tready       ),
      .s4_axis_tdata        ( s4_axis_tdata        ),
      .s4_axis_tvalid       ( s4_axis_tvalid       ),
      .s4_axis_tready       ( s4_axis_tready       ),
      .s5_axis_tdata        ( s5_axis_tdata        ),
      .s5_axis_tvalid       ( s5_axis_tvalid       ),
      .s5_axis_tready       ( s5_axis_tready       ),
      .s6_axis_tdata        ( s6_axis_tdata        ),
      .s6_axis_tvalid       ( s6_axis_tvalid       ),
      .s6_axis_tready       ( s6_axis_tready       ),
      .s7_axis_tdata        ( s7_axis_tdata        ),
      .s7_axis_tvalid       ( s7_axis_tvalid       ),
      .s7_axis_tready       ( s7_axis_tready       ),
      .s8_axis_tdata        ( s8_axis_tdata        ),
      .s8_axis_tvalid       ( s8_axis_tvalid       ),
      .s8_axis_tready       ( s8_axis_tready       ),
      .s9_axis_tdata        ( s9_axis_tdata        ),
      .s9_axis_tvalid       ( s9_axis_tvalid       ),
      .s9_axis_tready       ( s9_axis_tready       ),
      .s10_axis_tdata       ( s10_axis_tdata       ),
      .s10_axis_tvalid      ( s10_axis_tvalid      ),
      .s10_axis_tready      ( s10_axis_tready      ),
      .s11_axis_tdata       ( s11_axis_tdata       ),
      .s11_axis_tvalid      ( s11_axis_tvalid      ),
      .s11_axis_tready      ( s11_axis_tready      ),
      .s12_axis_tdata       ( s12_axis_tdata       ),
      .s12_axis_tvalid      ( s12_axis_tvalid      ),
      .s12_axis_tready      ( s12_axis_tready      ),
      .s13_axis_tdata       ( s13_axis_tdata       ),
      .s13_axis_tvalid      ( s13_axis_tvalid      ),
      .s13_axis_tready      ( s13_axis_tready      ),
      .s14_axis_tdata       ( s14_axis_tdata       ),
      .s14_axis_tvalid      ( s14_axis_tvalid      ),
      .s14_axis_tready      ( s14_axis_tready      ),
      .s15_axis_tdata       ( s15_axis_tdata       ),
      .s15_axis_tvalid      ( s15_axis_tvalid      ),
      .s15_axis_tready      ( s15_axis_tready      ),
      // OUT WAVE PORTS
      .m0_axis_tdata        ( m0_axis_tdata        ),
      .m0_axis_tvalid       ( m0_axis_tvalid       ),
      .m0_axis_tready       ( m0_axis_tready       ),
      .m1_axis_tdata        ( m1_axis_tdata        ),
      .m1_axis_tvalid       ( m1_axis_tvalid       ),
      .m1_axis_tready       ( m1_axis_tready       ),
      .m2_axis_tdata        ( m2_axis_tdata        ),
      .m2_axis_tvalid       ( m2_axis_tvalid       ),
      .m2_axis_tready       ( m2_axis_tready       ),
      .m3_axis_tdata        ( m3_axis_tdata        ),
      .m3_axis_tvalid       ( m3_axis_tvalid       ),
      .m3_axis_tready       ( m3_axis_tready       ),
      .m4_axis_tdata        ( m4_axis_tdata        ),
      .m4_axis_tvalid       ( m4_axis_tvalid       ),
      .m4_axis_tready       ( m4_axis_tready       ),
      .m5_axis_tdata        ( m5_axis_tdata        ),
      .m5_axis_tvalid       ( m5_axis_tvalid       ),
      .m5_axis_tready       ( m5_axis_tready       ),
      .m6_axis_tdata        ( m6_axis_tdata        ),
      .m6_axis_tvalid       ( m6_axis_tvalid       ),
      .m6_axis_tready       ( m6_axis_tready       ),
      .m7_axis_tdata        ( m7_axis_tdata        ),
      .m7_axis_tvalid       ( m7_axis_tvalid       ),
      .m7_axis_tready       ( m7_axis_tready       ),
      .m8_axis_tdata        ( m8_axis_tdata        ),
      .m8_axis_tvalid       ( m8_axis_tvalid       ),
      .m8_axis_tready       ( m8_axis_tready       ),
      .m9_axis_tdata        ( m9_axis_tdata        ),
      .m9_axis_tvalid       ( m9_axis_tvalid       ),
      .m9_axis_tready       ( m9_axis_tready       ),
      .m10_axis_tdata       ( m10_axis_tdata       ),
      .m10_axis_tvalid      ( m10_axis_tvalid      ),
      .m10_axis_tready      ( m10_axis_tready      ),
      .m11_axis_tdata       ( m11_axis_tdata       ),
      .m11_axis_tvalid      ( m11_axis_tvalid      ),
      .m11_axis_tready      ( m11_axis_tready      ),
      .m12_axis_tdata       ( m12_axis_tdata       ),
      .m12_axis_tvalid      ( m12_axis_tvalid      ),
      .m12_axis_tready      ( m12_axis_tready      ),
      .m13_axis_tdata       ( m13_axis_tdata       ),
      .m13_axis_tvalid      ( m13_axis_tvalid      ),
      .m13_axis_tready      ( m13_axis_tready      ),
      .m14_axis_tdata       ( m14_axis_tdata       ),
      .m14_axis_tvalid      ( m14_axis_tvalid      ),
      .m14_axis_tready      ( m14_axis_tready      ),
      .m15_axis_tdata       ( m15_axis_tdata       ),
      .m15_axis_tvalid      ( m15_axis_tvalid      ),
      .m15_axis_tready      ( m15_axis_tready      ),
      ///// TRIGGERS
      .trig_0_o             ( trig_0_o             ),
      .trig_1_o             ( trig_1_o             ),
      .trig_2_o             ( trig_2_o             ),
      .trig_3_o             ( trig_3_o             ),
      .trig_4_o             ( trig_4_o             ),
      .trig_5_o             ( trig_5_o             ),
      .trig_6_o             ( trig_6_o             ),
      .trig_7_o             ( trig_7_o             ),
      .trig_8_o             ( trig_8_o             ),
      .trig_9_o             ( trig_9_o             ),
      .trig_10_o            ( trig_10_o            ),
      .trig_11_o            ( trig_11_o            ),
      .trig_12_o            ( trig_12_o            ),
      .trig_13_o            ( trig_13_o            ),
      .trig_14_o            ( trig_14_o            ),
      .trig_15_o            ( trig_15_o            ),
      .trig_16_o            ( trig_16_o            ),
      .trig_17_o            ( trig_17_o            ),
      .trig_18_o            ( trig_18_o            ),
      .trig_19_o            ( trig_19_o            ),
      .trig_20_o            ( trig_20_o            ),
      .trig_21_o            ( trig_21_o            ),
      .trig_22_o            ( trig_22_o            ),
      .trig_23_o            ( trig_23_o            ),
      .trig_24_o            ( trig_24_o            ),
      .trig_25_o            ( trig_25_o            ),
      .trig_26_o            ( trig_26_o            ),
      .trig_27_o            ( trig_27_o            ),
      .trig_28_o            ( trig_28_o            ),
      .trig_29_o            ( trig_29_o            ),
      .trig_30_o            ( trig_30_o            ),
      .trig_31_o            ( trig_31_o            ),
      // OUT DATA
      .port_0_dt_o          ( port_0_dt_o          ),
      .port_1_dt_o          ( port_1_dt_o          ),
      .port_2_dt_o          ( port_2_dt_o          ),
      .port_3_dt_o          ( port_3_dt_o          ),
      // Debug Signals
      .ps_debug_do          ( ps_debug_do          ),
      .t_debug_do           ( t_debug_do           ),
      .t_fifo_do            ( t_fifo_do            ),
      .c_time_usr_do        ( c_time_usr_do        ),
      .c_debug_do           ( c_debug_do           ),
      .c_time_ref_do        ( c_time_ref_do        ),
      .c_proc_do            ( c_proc_do            ),
      .c_port_do            ( c_port_do            ),
      .c_core_do            ( c_core_do            )
   );

endmodule
