///////////////////////////////////////////////////////////////////////////////
//  Fermilab National Accelerator Laboratory
///////////////////////////////////////////////////////////////////////////////
// Description:
//   QickEmu-driven testbench for QICK project — Vivado/Xilinx-IP compatible.
//   Adapted from tb_qick.sv: keeps all real Xilinx RTL blocks but replaces
//   hardcoded VIP transactions with file-based replay from QickEmu.prepare().
//
// Required input files (generated by QickEmu.prepare() + export_vivado_files()):
//   EMU_DIR/pmem.mem         — tproc program memory  (hex, $readmemh)
//   EMU_DIR/wmem.mem         — tproc wave memory     (hex, $readmemh)
//   EMU_DIR/sgmem_ch{N}.mem  — SG envelope table     (signed decimal I,Q CSV)
//   EMU_DIR/axi_replay.txt   — AXI-Lite replay log   (hex addr/data pairs)
//
// Python workflow:
//   from qick_emu import QickEmu
//   emu = QickEmu("qick_config.json")
//   soc = emu.make_soc(memdir="emulator/")
//   soc.tproc.set_lfsr_cfg(2)
//   emu.prepare(prog, soc, memdir="emulator/")
//   emu.export_vivado_files(memdir="emulator/")   # generates axi_replay.txt
//
// Then set EMU_DIR to your "emulator/" directory and simulate.
//////////////////////////////////////////////////////////////////////////////

`timescale 1ns/1fs

`include "_qproc_defines.svh"

import axi_vip_pkg::*;
import axi_mst_0_pkg::*;

// Clock half-periods (ns)
real T_TCLK   =  1.162;   // 430   MHz  tProc dispatcher
real T_CCLK   =    2.5;   // 200   MHz  tProc core
real T_SCLK   =    5.0;   // 100   MHz  PS / AXI
real T_SG_CLK =  0.8346688;   // 600   MHz  signal generator
real T_RO_CLK =  1.62760416;   // 307.2 MHz  readout

// TPROC parameters — must match firmware build
`define GEN_SYNC         1
`define DUAL_CORE        0
`define IO_CTRL          1
`define DEBUG            3
`define TNET             0
`define QCOM             0
`define CUSTOM_PERIPH    2
`define LFSR             1
`define DIVIDER          1
`define ARITH            1
`define TIME_READ        1
`define FIFO_DEPTH       8
`define PMEM_AW          12
`define DMEM_AW          14
`define WMEM_AW          11
`define REG_AW           4
`define IN_PORT_QTY      1
`define OUT_TRIG_QTY     1
`define OUT_DPORT_QTY    1
`define OUT_DPORT_DW     8
`define OUT_WPORT_QTY    5

module tb_qick_emu ();

//----------------------------------------------------
// QickEmu Configuration
//----------------------------------------------------
// Directory containing QickEmu-generated files.
// Can be an absolute path or relative to the Vivado sim run directory.
string EMU_DIR       = "../../../../src/tb";

// How long to let tproc run after AXI replay completes.
// The AXI replay includes the PROC_START command; this is additional wait time.
time   TEST_RUN_TIME = 100us;

// ===========================================================================
// Address Routing Parameters
//
// Must match the base addresses assigned by AddrMap.from_qick_config().
// To get the correct values for your board config, run:
//
//   python3 -c "
//   import json, sys
//   sys.path.insert(0, 'emulator/software/source')
//   cfg = json.load(open('emulator/notebooks/qick_config_216.json'))
//   addr = 0x40000000
//   def add(n,t): global addr; print(f'{n:40s} {t:30s} 0x{addr:08X}'); addr+=0x10000
//   if 'ddr4_buf' in cfg: add(cfg['ddr4_buf']['fullpath'], cfg['ddr4_buf']['type'])
//   if 'mr_buf'   in cfg: add(cfg['mr_buf']['fullpath'],   cfg['mr_buf']['type'])
//   [add(g['fullpath'],g['type']) for g in cfg.get('gens',[])]
//   [(add(r['ro_fullpath'],r['ro_type']),add(r['avgbuf_fullpath'],r['avgbuf_type'])) for r in cfg.get('readouts',[])]
//   [add(t.get('fullpath','qick_processor_0'),t['type']) for t in cfg.get('tprocs',[])]
//   "
//
// Default values below are for ZCU216 HMC demo (qick_config_216.json).
// ===========================================================================

// tproc: qick_processor_0
localparam integer TPROC_BASE  = 32'h40260000;

// Signal generators: all gen IPs occupy a contiguous region.
// Any AXI write to [SG_BASE_LO, SG_BASE_HI) is routed to axi_mst_sg_agent.
// NOTE: tb only instantiates ONE signal gen VIP. Multi-gen writes all drive the
//       same VIP with their per-IP register offset (addr & 0xFFFF).
localparam integer SG_BASE_LO  = 32'h40020000;  // axis_signal_gen_v6_0
localparam integer SG_BASE_HI  = 32'h40120000;  // first non-gen address

// Avg/decim buffers: all avgbuf IPs occupy a contiguous region.
// Any AXI write to [AVG_BASE_LO, AVG_BASE_HI) is routed to axi_mst_avg_agent.
localparam integer AVG_BASE_LO = 32'h40130000;  // axis_avg_buffer_0
localparam integer AVG_BASE_HI = 32'h40260000;  // first non-avgbuf address

//----------------------------------------------------
// VIP Agents
//----------------------------------------------------
axi_mst_0_mst_t  axi_mst_tproc_agent;
axi_mst_0_mst_t  axi_mst_sg_agent;
axi_mst_0_mst_t  axi_mst_avg_agent;
axi_mst_0_mst_t  axi_mst_qemu_agent;

// AXI VIP common variables
xil_axi_prot_t  prot    = 0;
reg [31:0]      data_wr = 32'h12345678;
reg [31:0]      data;
xil_axi_resp_t  resp;

//----------------------------------------------------
// CLK Generation
//----------------------------------------------------
logic c_clk, t_clk, s_ps_dma_aclk;

logic [4:0] dac_fs_gen;
logic       dac_fs, sg_clk;

logic [4:0] adc_fs_gen;
logic       adc_fs, ro_clk;

initial begin t_clk = 1'b0; forever #(T_TCLK*1.0ns) t_clk = ~t_clk; end
initial begin c_clk = 1'b0; forever #(T_CCLK*1.0ns) c_clk = ~c_clk; end
initial begin
   s_ps_dma_aclk = 1'b0;
   #0.5ns;
   forever #(T_SCLK*1.0ns) s_ps_dma_aclk = ~s_ps_dma_aclk;
end

initial begin dac_fs_gen = 'd0; forever #(T_SG_CLK*1.0ns/N_DDS) dac_fs_gen = dac_fs_gen + 'd1; end
assign dac_fs = dac_fs_gen[0];
assign sg_clk = dac_fs_gen[4];

initial begin adc_fs_gen = 'd0; forever #(T_RO_CLK*1.0ns/8.0) adc_fs_gen = adc_fs_gen + 'd1; end
assign adc_fs = adc_fs_gen[0];
assign ro_clk = adc_fs_gen[3];

//----------------------------------------------------
// Reset
//----------------------------------------------------
logic rst_ni;
wire  s_ps_dma_aresetn;
assign s_ps_dma_aresetn = rst_ni;

//----------------------------------------------------
// Signal Declarations
//----------------------------------------------------
reg [255:0]  s_dma_axis_tdata_i;
reg          s_dma_axis_tlast_i;
reg          s_dma_axis_tvalid_i;
reg          m_dma_axis_tready_i;
wire [63:0]  port_0_dt_i;
reg  [63:0]  port_1_dt_i;

logic        m0_axis_tready;
reg          m1_axis_tready = 1;
reg          m2_axis_tready = 1;
reg          m3_axis_tready = 1;
reg          m5_axis_tready = 1;
reg          m6_axis_tready = 1;
reg          m7_axis_tready = 1;

wire         s_dma_axis_tready_o;
wire [255:0] m_dma_axis_tdata_o;
wire         m_dma_axis_tlast_o;
wire         m_dma_axis_tvalid_o;

// tProc wave outputs
wire [167:0] m1_axis_tdata, m2_axis_tdata, m3_axis_tdata;
wire         m1_axis_tvalid, m2_axis_tvalid, m3_axis_tvalid;
wire [167:0] m5_axis_tdata, m6_axis_tdata, m7_axis_tdata;
wire         m5_axis_tvalid, m6_axis_tvalid, m7_axis_tvalid;

wire trigger_0;
wire [`OUT_DPORT_DW-1:0] port_0_dt_o, port_1_dt_o, port_2_dt_o, port_3_dt_o;

// SG CDC path
wire  [167:0] tproc_sgcdc_0_axis_tdata;
wire          tproc_sgcdc_0_axis_tvalid;
logic         tproc_sgcdc_0_axis_tready;
wire  [167:0] sgcdc_sgt_0_axis_tdata;
wire          sgcdc_sgt_0_axis_tvalid;
logic         sgcdc_sgt_0_axis_tready;
wire  [159:0] sgt_sg_0_axis_tdata;
wire          sgt_sg_0_axis_tvalid;
logic         sgt_sg_0_axis_tready;

// RO CDC path
wire  [167:0] tproc_rocdc_0_axis_tdata;
wire          tproc_rocdc_0_axis_tvalid;
logic         tproc_rocdc_0_axis_tready;
wire  [167:0] rocdc_rot_0_axis_tdata;
wire          rocdc_rot_0_axis_tvalid;
logic         rocdc_rot_0_axis_tready;
wire  [87:0]  rot_ro_0_axis_tdata;
wire          rot_ro_0_axis_tvalid;
logic         rot_ro_0_axis_tready;

// QNet/QCom/Periph
wire         qnet_en_o;
wire  [4:0]  qnet_op_o;
wire  [31:0] qnet_a_dt_o, qnet_b_dt_o, qnet_c_dt_o, qnet_d_dt_o;
reg          qnet_rdy_i;
reg  [31:0]  qnet_dt_i [2];
reg          qcom_rdy_i, qp2_rdy_i;
reg  [31:0]  qcom_dt_i [2];
wire         periph_en_o;
wire  [4:0]  periph_op_o;
wire  [31:0] periph_a_dt_o, periph_b_dt_o, periph_c_dt_o, periph_d_dt_o;
reg          periph_rdy_i;
reg  [31:0]  periph_dt_i [2];
reg  [31:0]  qp1_dt_i [2];
reg  [31:0]  qp2_dt_i [2];

reg  s0_axis_tvalid, s1_axis_tvalid;
reg  [15:0] waves, wtime;
reg  [31:0] axi_dt;

reg  proc_start_i, proc_stop_i;
reg  core_start_i, core_stop_i;
reg  time_rst_i, time_init_i, time_updt_i;
reg  [47:0] offset_dt_i;
wire [47:0] t_time_abs_o;
wire [31:0] ps_debug_do;

// QP1 loopback
wire         qp1_en_o;
reg          qp1_en_r;
reg  [31:0]  qp1_a_dt_r, qp1_b_dt_r;
wire [31:0]  qp1_a_dt_o, qp1_b_dt_o, qp1_c_dt_o, qp1_d_dt_o;
always_ff @(posedge c_clk) begin
   qp1_en_r   <= qp1_en_o;
   qp1_a_dt_r <= qp1_a_dt_o;
   qp1_b_dt_r <= qp1_b_dt_o;
end
assign qp1_rdy_i   = ~qp1_en_r;
assign qp1_dt_i[0] = qp1_a_dt_r;
assign qp1_dt_i[1] = qp1_b_dt_r;
assign qp1_vld_i   = qp1_en_r;

wire port_0_vld, qnet_vld_i, qnet_flag_i, periph_flag_i, ext_flag_i;
assign port_0_dt_i   = port_1_dt_o;
assign port_0_vld    = port_0_dt_o[0];
assign qnet_vld_i    = t_time_abs_o[3] & t_time_abs_o[2] & t_time_abs_o[1];
assign qnet_flag_i   = ~t_time_abs_o[5] & ~t_time_abs_o[4] &  t_time_abs_o[3];
assign periph_flag_i = ~t_time_abs_o[5] &  t_time_abs_o[4] &  t_time_abs_o[3];
assign ext_flag_i    =  t_time_abs_o[5] &  t_time_abs_o[4] &  t_time_abs_o[3];

// DAC/ADC connections
logic                axis_sg_dac_tready;
logic                axis_sg_dac_tvalid;
logic [N_DDS*16-1:0] axis_sg_dac_tdata;
logic                rf_signal_valid;
logic [8*16-1:0]     rf_signal_data;
logic                axis_adc_ro_tready;
logic                axis_adc_ro_tvalid;
logic [8*16-1:0]     axis_adc_ro_tdata;

// SG envelope load signals
wire   sg_s0_axis_aclk = s_ps_dma_aclk;
logic  [31:0] sg_s0_axis_tdata;
logic         sg_s0_axis_tready;
logic         sg_s0_axis_tvalid;
logic         tb_load_mem, tb_load_mem_done;

// Avg buffer DEC output readiness
logic m1_axis_buf_dec_tready;

//----------------------------------------------------
// TPROC AXI-Lite wires + register address offsets
//----------------------------------------------------
wire [7:0]  s_axi_tproc_awaddr;   wire [2:0]  s_axi_tproc_awprot;
wire        s_axi_tproc_awvalid;  wire        s_axi_tproc_awready;
wire [31:0] s_axi_tproc_wdata;    wire [3:0]  s_axi_tproc_wstrb;
wire        s_axi_tproc_wvalid;   wire        s_axi_tproc_wready;
wire  [1:0] s_axi_tproc_bresp;    wire        s_axi_tproc_bvalid;
wire        s_axi_tproc_bready;
wire [7:0]  s_axi_tproc_araddr;   wire [2:0]  s_axi_tproc_arprot;
wire        s_axi_tproc_arvalid;  wire        s_axi_tproc_arready;
wire  [31:0] s_axi_tproc_rdata;   wire  [1:0] s_axi_tproc_rresp;
wire         s_axi_tproc_rvalid;  wire        s_axi_tproc_rready;

parameter REG_TPROC_CTRL   = 0  * 4;
parameter REG_TPROC_CFG    = 1  * 4;
parameter REG_MEM_ADDR     = 2  * 4;
parameter REG_MEM_LEN      = 3  * 4;
parameter REG_MEM_DT_I     = 4  * 4;
parameter REG_AXI_W_DT1    = 5  * 4;
parameter REG_AXI_W_DT2    = 6  * 4;
parameter REG_CORE_CFG     = 7  * 4;
parameter REG_AXI_DT_SRC   = 8  * 4;
parameter REG_MEM_DT_O     = 10 * 4;
parameter REG_AXI_R_DT1    = 11 * 4;
parameter REG_AXI_R_DT2    = 12 * 4;
parameter REG_TIME_USR     = 13 * 4;
parameter REG_TPROC_STATUS = 14 * 4;
parameter REG_TPROC_DEBUG  = 15 * 4;

axi_mst_0 u_axi_mst_tproc_0 (
   .aclk          (s_ps_dma_aclk       ),
   .aresetn       (s_ps_dma_aresetn    ),
   .m_axi_araddr  (s_axi_tproc_araddr  ),
   .m_axi_arprot  (s_axi_tproc_arprot  ),
   .m_axi_arready (s_axi_tproc_arready ),
   .m_axi_arvalid (s_axi_tproc_arvalid ),
   .m_axi_awaddr  (s_axi_tproc_awaddr  ),
   .m_axi_awprot  (s_axi_tproc_awprot  ),
   .m_axi_awready (s_axi_tproc_awready ),
   .m_axi_awvalid (s_axi_tproc_awvalid ),
   .m_axi_bready  (s_axi_tproc_bready  ),
   .m_axi_bresp   (s_axi_tproc_bresp   ),
   .m_axi_bvalid  (s_axi_tproc_bvalid  ),
   .m_axi_rdata   (s_axi_tproc_rdata   ),
   .m_axi_rready  (s_axi_tproc_rready  ),
   .m_axi_rresp   (s_axi_tproc_rresp   ),
   .m_axi_rvalid  (s_axi_tproc_rvalid  ),
   .m_axi_wdata   (s_axi_tproc_wdata   ),
   .m_axi_wready  (s_axi_tproc_wready  ),
   .m_axi_wstrb   (s_axi_tproc_wstrb   ),
   .m_axi_wvalid  (s_axi_tproc_wvalid  )
);

//----------------------------------------------------
// AXIS QICK PROCESSOR
//----------------------------------------------------
axis_qick_processor #(
   .DUAL_CORE      ( `DUAL_CORE     ),
   .GEN_SYNC       ( `GEN_SYNC      ),
   .IO_CTRL        ( `IO_CTRL       ),
   .DEBUG          ( `DEBUG         ),
   .TNET           ( `TNET          ),
   .QCOM           ( `QCOM          ),
   .CUSTOM_PERIPH  ( `CUSTOM_PERIPH ),
   .LFSR           ( `LFSR          ),
   .DIVIDER        ( `DIVIDER       ),
   .ARITH          ( `ARITH         ),
   .TIME_READ      ( `TIME_READ     ),
   .FIFO_DEPTH     ( `FIFO_DEPTH    ),
   .PMEM_AW        ( `PMEM_AW       ),
   .DMEM_AW        ( `DMEM_AW       ),
   .WMEM_AW        ( `WMEM_AW       ),
   .REG_AW         ( `REG_AW        ),
   .IN_PORT_QTY    ( `IN_PORT_QTY   ),
   .OUT_TRIG_QTY   ( `OUT_TRIG_QTY  ),
   .OUT_DPORT_QTY  ( `OUT_DPORT_QTY ),
   .OUT_DPORT_DW   ( `OUT_DPORT_DW  ),
   .OUT_WPORT_QTY  ( `OUT_WPORT_QTY )
) AXIS_QPROC (
   .t_clk_i             ( t_clk              ),
   .t_resetn            ( rst_ni             ),
   .c_clk_i             ( c_clk              ),
   .c_resetn            ( rst_ni             ),
   .ps_clk_i            ( s_ps_dma_aclk      ),
   .ps_resetn           ( s_ps_dma_aresetn   ),
   .ext_flag_i          ( ext_flag_i         ),
   .proc_start_i        ( proc_start_i       ),
   .proc_stop_i         ( proc_stop_i        ),
   .core_start_i        ( core_start_i       ),
   .core_stop_i         ( core_stop_i        ),
   .time_rst_i          ( time_rst_i         ),
   .time_init_i         ( time_init_i        ),
   .time_updt_i         ( time_updt_i        ),
   .time_dt_i           ( offset_dt_i        ),
   .t_time_abs_o        ( t_time_abs_o       ),
   .qnet_en_o           ( qnet_en_o          ),
   .qnet_op_o           ( qnet_op_o          ),
   .qnet_a_dt_o         ( qnet_a_dt_o        ),
   .qnet_b_dt_o         ( qnet_b_dt_o        ),
   .qnet_c_dt_o         ( qnet_c_dt_o        ),
   .qnet_rdy_i          ( qnet_rdy_i         ),
   .qnet_dt1_i          ( qnet_dt_i[0]       ),
   .qnet_dt2_i          ( qnet_dt_i[1]       ),
   .qnet_vld_i          ( qnet_vld_i         ),
   .qnet_flag_i         ( qnet_flag_i        ),
   .qcom_en_o           ( qcom_en_o          ),
   .qcom_op_o           ( qcom_op_o          ),
   .qcom_dt_o           ( qcom_dt_o          ),
   .qcom_rdy_i          ( qcom_rdy_i         ),
   .qcom_dt1_i          ( qcom_dt_i[0]       ),
   .qcom_dt2_i          ( qcom_dt_i[1]       ),
   .qcom_vld_i          ( qcom_vld_i         ),
   .qcom_flag_i         ( qcom_flag_i        ),
   .qp1_en_o            ( qp1_en_o           ),
   .qp1_op_o            ( qp1_op_o           ),
   .qp1_a_dt_o          ( qp1_a_dt_o         ),
   .qp1_b_dt_o          ( qp1_b_dt_o         ),
   .qp1_c_dt_o          ( qp1_c_dt_o         ),
   .qp1_d_dt_o          ( qp1_d_dt_o         ),
   .qp1_rdy_i           ( qp1_rdy_i          ),
   .qp1_dt1_i           ( qp1_dt_i[0]        ),
   .qp1_dt2_i           ( qp1_dt_i[1]        ),
   .qp1_vld_i           ( qp1_vld_i          ),
   .qp1_flag_i          ( qp1_flag_i         ),
   .qp2_en_o            (                    ),
   .qp2_op_o            (                    ),
   .qp2_a_dt_o          (                    ),
   .qp2_b_dt_o          (                    ),
   .qp2_c_dt_o          (                    ),
   .qp2_d_dt_o          (                    ),
   .qp2_rdy_i           (                    ),
   .qp2_dt1_i           (                    ),
   .qp2_dt2_i           (                    ),
   .qp2_vld_i           (                    ),
   .s_dma_axis_tdata_i  ( s_dma_axis_tdata_i  ),
   .s_dma_axis_tlast_i  ( s_dma_axis_tlast_i  ),
   .s_dma_axis_tvalid_i ( s_dma_axis_tvalid_i ),
   .s_dma_axis_tready_o ( s_dma_axis_tready_o ),
   .m_dma_axis_tdata_o  ( m_dma_axis_tdata_o  ),
   .m_dma_axis_tlast_o  ( m_dma_axis_tlast_o  ),
   .m_dma_axis_tvalid_o ( m_dma_axis_tvalid_o ),
   .m_dma_axis_tready_i ( m_dma_axis_tready_i ),
   .s_axi_awaddr        ( s_axi_tproc_awaddr[7:0] ),
   .s_axi_awprot        ( s_axi_tproc_awprot      ),
   .s_axi_awvalid       ( s_axi_tproc_awvalid     ),
   .s_axi_awready       ( s_axi_tproc_awready     ),
   .s_axi_wdata         ( s_axi_tproc_wdata       ),
   .s_axi_wstrb         ( s_axi_tproc_wstrb       ),
   .s_axi_wvalid        ( s_axi_tproc_wvalid      ),
   .s_axi_wready        ( s_axi_tproc_wready      ),
   .s_axi_bresp         ( s_axi_tproc_bresp       ),
   .s_axi_bvalid        ( s_axi_tproc_bvalid      ),
   .s_axi_bready        ( s_axi_tproc_bready      ),
   .s_axi_araddr        ( s_axi_tproc_araddr[7:0] ),
   .s_axi_arprot        ( s_axi_tproc_arprot      ),
   .s_axi_arvalid       ( s_axi_tproc_arvalid     ),
   .s_axi_arready       ( s_axi_tproc_arready     ),
   .s_axi_rdata         ( s_axi_tproc_rdata       ),
   .s_axi_rresp         ( s_axi_tproc_rresp       ),
   .s_axi_rvalid        ( s_axi_tproc_rvalid      ),
   .s_axi_rready        ( s_axi_tproc_rready      ),
   .s0_axis_tdata       ( port_0_dt_i    ),
   .s0_axis_tvalid      ( port_0_vld     ),
   .s1_axis_tdata       ( port_1_dt_i    ),
   .s1_axis_tvalid      ( s1_axis_tvalid ),
   .s2_axis_tdata       ( 64'd2 ), .s2_axis_tvalid ( 1'b0 ),
   .s3_axis_tdata       ( 64'd3 ), .s3_axis_tvalid ( 1'b0 ),
   .s4_axis_tdata       ( 64'd4 ), .s4_axis_tvalid ( 1'b0 ),
   .s5_axis_tdata       ( 64'd5 ), .s5_axis_tvalid ( 1'b0 ),
   .s6_axis_tdata       ( 64'd6 ), .s6_axis_tvalid ( 1'b0 ),
   .s7_axis_tdata       ( 64'd7 ), .s7_axis_tvalid ( 1'b0 ),
   .m0_axis_tdata       ( tproc_sgcdc_0_axis_tdata  ),
   .m0_axis_tvalid      ( tproc_sgcdc_0_axis_tvalid ),
   .m0_axis_tready      ( tproc_sgcdc_0_axis_tready ),
   .m1_axis_tdata       (                  ),
   .m1_axis_tvalid      (                  ),
   .m1_axis_tready      ( m1_axis_tready   ),
   .m2_axis_tdata       (                  ),
   .m2_axis_tvalid      (                  ),
   .m2_axis_tready      ( m2_axis_tready   ),
   .m3_axis_tdata       (                  ),
   .m3_axis_tvalid      (                  ),
   .m3_axis_tready      ( m3_axis_tready   ),
   .m4_axis_tdata       ( tproc_rocdc_0_axis_tdata  ),
   .m4_axis_tvalid      ( tproc_rocdc_0_axis_tvalid ),
   .m4_axis_tready      ( tproc_rocdc_0_axis_tready ),
   .m5_axis_tdata       (                  ),
   .m5_axis_tvalid      (                  ),
   .m5_axis_tready      ( m5_axis_tready   ),
   .m6_axis_tdata       (                  ),
   .m6_axis_tvalid      (                  ),
   .m6_axis_tready      ( m6_axis_tready   ),
   .m7_axis_tdata       (                  ),
   .m7_axis_tvalid      (                  ),
   .m7_axis_tready      ( m7_axis_tready   ),
   .trig_0_o            ( trigger_0        ),
   .port_0_dt_o         ( port_0_dt_o      ),
   .port_1_dt_o         ( port_1_dt_o      ),
   .port_2_dt_o         ( port_2_dt_o      ),
   .port_3_dt_o         ( port_3_dt_o      ),
   .ps_debug_do         ( ),
   .t_debug_do          ( ),
   .t_fifo_do           ( ),
   .c_time_usr_do       ( ),
   .c_debug_do          ( ),
   .c_time_ref_do       ( ),
   .c_port_do           ( ),
   .c_core_do           ( )
);

//----------------------------------------------------
// SIGNAL GENERATOR PATH
//----------------------------------------------------
wire  [5:0]  s_axi_sg_araddr;   wire [2:0]  s_axi_sg_arprot;
wire         s_axi_sg_arready;  wire        s_axi_sg_arvalid;
wire  [5:0]  s_axi_sg_awaddr;   wire [2:0]  s_axi_sg_awprot;
wire         s_axi_sg_awready;  wire        s_axi_sg_awvalid;
wire         s_axi_sg_bready;   wire  [1:0] s_axi_sg_bresp;
wire         s_axi_sg_bvalid;   wire [31:0] s_axi_sg_rdata;
wire         s_axi_sg_rready;   wire  [1:0] s_axi_sg_rresp;
wire         s_axi_sg_rvalid;   wire [31:0] s_axi_sg_wdata;
wire         s_axi_sg_wready;   wire  [3:0] s_axi_sg_wstrb;
wire         s_axi_sg_wvalid;

// Envelope table access offsets (offset only; base ignored by IP)
xil_axi_ulong SG_ADDR_START_ADDR = 32'h00000000;  // reg 0: envelope start addr
xil_axi_ulong SG_ADDR_WE         = 32'h00000004;  // reg 1: envelope write enable

axi_mst_0 u_axi_mst_sg_0 (
   .aclk          (s_ps_dma_aclk    ),
   .aresetn       (s_ps_dma_aresetn ),
   .m_axi_araddr  (s_axi_sg_araddr  ),
   .m_axi_arprot  (s_axi_sg_arprot  ),
   .m_axi_arready (s_axi_sg_arready ),
   .m_axi_arvalid (s_axi_sg_arvalid ),
   .m_axi_awaddr  (s_axi_sg_awaddr  ),
   .m_axi_awprot  (s_axi_sg_awprot  ),
   .m_axi_awready (s_axi_sg_awready ),
   .m_axi_awvalid (s_axi_sg_awvalid ),
   .m_axi_bready  (s_axi_sg_bready  ),
   .m_axi_bresp   (s_axi_sg_bresp   ),
   .m_axi_bvalid  (s_axi_sg_bvalid  ),
   .m_axi_rdata   (s_axi_sg_rdata   ),
   .m_axi_rready  (s_axi_sg_rready  ),
   .m_axi_rresp   (s_axi_sg_rresp   ),
   .m_axi_rvalid  (s_axi_sg_rvalid  ),
   .m_axi_wdata   (s_axi_sg_wdata   ),
   .m_axi_wready  (s_axi_sg_wready  ),
   .m_axi_wstrb   (s_axi_sg_wstrb   ),
   .m_axi_wvalid  (s_axi_sg_wvalid  )
);

axis_cdcsync_v1 #(.N(1), .B(168)) u_axis_sgcdcsync_v1 (
   .s_axis_aresetn  (rst_ni),
   .s_axis_aclk     (t_clk),
   .s0_axis_tready  (tproc_sgcdc_0_axis_tready),
   .s0_axis_tvalid  (tproc_sgcdc_0_axis_tvalid),
   .s0_axis_tdata   (tproc_sgcdc_0_axis_tdata),
   // unused s1..s15
   .s1_axis_tready  (), .s1_axis_tvalid  (1'b0), .s1_axis_tdata  (168'd0),
   .s2_axis_tready  (), .s2_axis_tvalid  (1'b0), .s2_axis_tdata  (168'd0),
   .s3_axis_tready  (), .s3_axis_tvalid  (1'b0), .s3_axis_tdata  (168'd0),
   .s4_axis_tready  (), .s4_axis_tvalid  (1'b0), .s4_axis_tdata  (168'd0),
   .s5_axis_tready  (), .s5_axis_tvalid  (1'b0), .s5_axis_tdata  (168'd0),
   .s6_axis_tready  (), .s6_axis_tvalid  (1'b0), .s6_axis_tdata  (168'd0),
   .s7_axis_tready  (), .s7_axis_tvalid  (1'b0), .s7_axis_tdata  (168'd0),
   .s8_axis_tready  (), .s8_axis_tvalid  (1'b0), .s8_axis_tdata  (168'd0),
   .s9_axis_tready  (), .s9_axis_tvalid  (1'b0), .s9_axis_tdata  (168'd0),
   .s10_axis_tready (), .s10_axis_tvalid (1'b0), .s10_axis_tdata (168'd0),
   .s11_axis_tready (), .s11_axis_tvalid (1'b0), .s11_axis_tdata (168'd0),
   .s12_axis_tready (), .s12_axis_tvalid (1'b0), .s12_axis_tdata (168'd0),
   .s13_axis_tready (), .s13_axis_tvalid (1'b0), .s13_axis_tdata (168'd0),
   .s14_axis_tready (), .s14_axis_tvalid (1'b0), .s14_axis_tdata (168'd0),
   .s15_axis_tready (), .s15_axis_tvalid (1'b0), .s15_axis_tdata (168'd0),
   .m_axis_aresetn  (rst_ni),
   .m_axis_aclk     (sg_clk),
   .m0_axis_tready  (sgcdc_sgt_0_axis_tready),
   .m0_axis_tvalid  (sgcdc_sgt_0_axis_tvalid),
   .m0_axis_tdata   (sgcdc_sgt_0_axis_tdata),
   // unused m1..m15 left open
   .m1_axis_tready  (1'b1), .m1_axis_tvalid  (), .m1_axis_tdata  (),
   .m2_axis_tready  (1'b1), .m2_axis_tvalid  (), .m2_axis_tdata  (),
   .m3_axis_tready  (1'b1), .m3_axis_tvalid  (), .m3_axis_tdata  (),
   .m4_axis_tready  (1'b1), .m4_axis_tvalid  (), .m4_axis_tdata  (),
   .m5_axis_tready  (1'b1), .m5_axis_tvalid  (), .m5_axis_tdata  (),
   .m6_axis_tready  (1'b1), .m6_axis_tvalid  (), .m6_axis_tdata  (),
   .m7_axis_tready  (1'b1), .m7_axis_tvalid  (), .m7_axis_tdata  (),
   .m8_axis_tready  (1'b1), .m8_axis_tvalid  (), .m8_axis_tdata  (),
   .m9_axis_tready  (1'b1), .m9_axis_tvalid  (), .m9_axis_tdata  (),
   .m10_axis_tready (1'b1), .m10_axis_tvalid (), .m10_axis_tdata (),
   .m11_axis_tready (1'b1), .m11_axis_tvalid (), .m11_axis_tdata (),
   .m12_axis_tready (1'b1), .m12_axis_tvalid (), .m12_axis_tdata (),
   .m13_axis_tready (1'b1), .m13_axis_tvalid (), .m13_axis_tdata (),
   .m14_axis_tready (1'b1), .m14_axis_tvalid (), .m14_axis_tdata (),
   .m15_axis_tready (1'b1), .m15_axis_tvalid (), .m15_axis_tdata ()
);

sg_translator #(.OUT_TYPE(0)) u_sg_translator_0 (
   .aresetn              (1'bx), .aclk (1'bx),
   .s_axis_tdata         (sgcdc_sgt_0_axis_tdata),
   .s_axis_tvalid        (sgcdc_sgt_0_axis_tvalid),
   .s_axis_tready        (sgcdc_sgt_0_axis_tready),
   .m_gen_v6_axis_tdata  (sgt_sg_0_axis_tdata),
   .m_gen_v6_axis_tvalid (sgt_sg_0_axis_tvalid),
   .m_gen_v6_axis_tready (sgt_sg_0_axis_tready),
   .m_int4_axis_tdata    (), .m_int4_axis_tvalid (), .m_int4_axis_tready (),
   .m_mux4_axis_tdata    (), .m_mux4_axis_tvalid (), .m_mux4_axis_tready (),
   .m_readout_axis_tdata (), .m_readout_axis_tvalid (), .m_readout_axis_tready ()
);

localparam N     = 10;
localparam N_DDS = 16;

axis_signal_gen_v6 #(
   .N            (N),
   .N_DDS        (N_DDS),
   .GEN_DDS      ("TRUE"),
   .ENVELOPE_TYPE("COMPLEX")
) u_axis_signal_gen_v6_0 (
   .s_axi_aclk    (s_ps_dma_aclk    ),
   .s_axi_aresetn (s_ps_dma_aresetn ),
   .s_axi_araddr  (s_axi_sg_araddr  ),
   .s_axi_arprot  (s_axi_sg_arprot  ),
   .s_axi_arready (s_axi_sg_arready ),
   .s_axi_arvalid (s_axi_sg_arvalid ),
   .s_axi_awaddr  (s_axi_sg_awaddr  ),
   .s_axi_awprot  (s_axi_sg_awprot  ),
   .s_axi_awready (s_axi_sg_awready ),
   .s_axi_awvalid (s_axi_sg_awvalid ),
   .s_axi_bready  (s_axi_sg_bready  ),
   .s_axi_bresp   (s_axi_sg_bresp   ),
   .s_axi_bvalid  (s_axi_sg_bvalid  ),
   .s_axi_rdata   (s_axi_sg_rdata   ),
   .s_axi_rready  (s_axi_sg_rready  ),
   .s_axi_rresp   (s_axi_sg_rresp   ),
   .s_axi_rvalid  (s_axi_sg_rvalid  ),
   .s_axi_wdata   (s_axi_sg_wdata   ),
   .s_axi_wready  (s_axi_sg_wready  ),
   .s_axi_wstrb   (s_axi_sg_wstrb   ),
   .s_axi_wvalid  (s_axi_sg_wvalid  ),
   .s0_axis_aclk    (s_ps_dma_aclk     ),
   .s0_axis_aresetn (s_ps_dma_aresetn  ),
   .s0_axis_tdata   (sg_s0_axis_tdata  ),
   .s0_axis_tvalid  (sg_s0_axis_tvalid ),
   .s0_axis_tready  (sg_s0_axis_tready ),
   .aresetn         (rst_ni            ),
   .aclk            (sg_clk            ),
   .s1_axis_tdata   (sgt_sg_0_axis_tdata  ),
   .s1_axis_tvalid  (sgt_sg_0_axis_tvalid ),
   .s1_axis_tready  (sgt_sg_0_axis_tready ),
   .m_axis_tready   (axis_sg_dac_tready   ),
   .m_axis_tvalid   (axis_sg_dac_tvalid   ),
   .m_axis_tdata    (axis_sg_dac_tdata    )
);

// Debug: unpack DAC samples
logic signed [15:0] axis_sg_dac_tdata_dbg [0:N_DDS-1];
always @* begin
   for (int i = 0; i < N_DDS; i++)
      axis_sg_dac_tdata_dbg[i] = axis_sg_dac_tdata[16*i +: 16];
end

//----------------------------------------------------
// DAC / ADC model (loopback)
//----------------------------------------------------
localparam DAC_W = 16;
logic signed [DAC_W-1:0] dac_data;
localparam ADC_W = 14;
logic signed [ADC_W-1:0] adc_sample;
logic signed [15:0]      adc_data;

model_DAC_ADC #(.DAC_W(DAC_W), .ADC_W(ADC_W), .BUFFER_SIZE(16)) u_model_DAC_ADC (
   .clk_DAC    (dac_fs),
   .dac_sample (dac_data),
   .clk_ADC    (adc_fs),
   .adc_sample (adc_sample),
   .mode       (1)
);

assign adc_data = $signed(adc_sample);

logic [$clog2(N_DDS)-1:0] dac_samp_cnt;
always @(posedge dac_fs) begin
   if (axis_sg_dac_tvalid) begin
      dac_data     <= axis_sg_dac_tdata[16*dac_samp_cnt +: 16];
      dac_samp_cnt <= dac_samp_cnt + 'd1;
   end else begin
      dac_data     <= 'd0;
      dac_samp_cnt <= 'd0;
   end
end

assign axis_sg_dac_tready = 1'b1;

logic [$clog2(N_DDS)-1:0] adc_samp_cnt;
always @(posedge adc_fs) begin
   if (adc_samp_cnt < 7) begin
      adc_samp_cnt    <= adc_samp_cnt + 1;
      rf_signal_valid <= 0;
   end else begin
      adc_samp_cnt    <= 0;
      rf_signal_valid <= 1;
   end
   rf_signal_data[16*adc_samp_cnt +: 16] <= adc_data;
end

reg rf_signal_valid_dly;
reg [8*16-1:0] rf_signal_data_dly;
always @(*) begin
   rf_signal_valid_dly <= #(10ns) rf_signal_valid;
   rf_signal_data_dly  <= #(10ns) rf_signal_data;
end

//----------------------------------------------------
// Qubit Emulator (axis_kidsim_v3)
//----------------------------------------------------
wire  [7:0]  s_axi_qemu_araddr;   wire [2:0]  s_axi_qemu_arprot;
wire         s_axi_qemu_arready;  wire        s_axi_qemu_arvalid;
wire  [7:0]  s_axi_qemu_awaddr;   wire [2:0]  s_axi_qemu_awprot;
wire         s_axi_qemu_awready;  wire        s_axi_qemu_awvalid;
wire         s_axi_qemu_bready;   wire  [1:0] s_axi_qemu_bresp;
wire         s_axi_qemu_bvalid;   wire [31:0] s_axi_qemu_rdata;
wire         s_axi_qemu_rready;   wire  [1:0] s_axi_qemu_rresp;
wire         s_axi_qemu_rvalid;   wire [31:0] s_axi_qemu_wdata;
wire         s_axi_qemu_wready;   wire  [3:0] s_axi_qemu_wstrb;
wire         s_axi_qemu_wvalid;

localparam L = 1;
wire              axis_qemu_ro_tvalid;
wire [L*2*16-1:0] axis_qemu_ro_tdata;

axi_mst_0 u_axi_mst_qemu_0 (
   .aclk          (s_ps_dma_aclk      ),
   .aresetn       (s_ps_dma_aresetn   ),
   .m_axi_araddr  (s_axi_qemu_araddr  ),
   .m_axi_arprot  (s_axi_qemu_arprot  ),
   .m_axi_arready (s_axi_qemu_arready ),
   .m_axi_arvalid (s_axi_qemu_arvalid ),
   .m_axi_awaddr  (s_axi_qemu_awaddr  ),
   .m_axi_awprot  (s_axi_qemu_awprot  ),
   .m_axi_awready (s_axi_qemu_awready ),
   .m_axi_awvalid (s_axi_qemu_awvalid ),
   .m_axi_bready  (s_axi_qemu_bready  ),
   .m_axi_bresp   (s_axi_qemu_bresp   ),
   .m_axi_bvalid  (s_axi_qemu_bvalid  ),
   .m_axi_rdata   (s_axi_qemu_rdata   ),
   .m_axi_rready  (s_axi_qemu_rready  ),
   .m_axi_rresp   (s_axi_qemu_rresp   ),
   .m_axi_rvalid  (s_axi_qemu_rvalid  ),
   .m_axi_wdata   (s_axi_qemu_wdata   ),
   .m_axi_wready  (s_axi_qemu_wready  ),
   .m_axi_wstrb   (s_axi_qemu_wstrb   ),
   .m_axi_wvalid  (s_axi_qemu_wvalid  )
);

axis_kidsim_v3 #(.L(L)) u_axis_kidsim_v3 (
   .s_axi_aclk    (s_ps_dma_aclk      ),
   .s_axi_aresetn (s_ps_dma_aresetn   ),
   .s_axi_araddr  (s_axi_qemu_araddr  ),
   .s_axi_arprot  (s_axi_qemu_arprot  ),
   .s_axi_arready (s_axi_qemu_arready ),
   .s_axi_arvalid (s_axi_qemu_arvalid ),
   .s_axi_awaddr  (s_axi_qemu_awaddr  ),
   .s_axi_awprot  (s_axi_qemu_awprot  ),
   .s_axi_awready (s_axi_qemu_awready ),
   .s_axi_awvalid (s_axi_qemu_awvalid ),
   .s_axi_bready  (s_axi_qemu_bready  ),
   .s_axi_bresp   (s_axi_qemu_bresp   ),
   .s_axi_bvalid  (s_axi_qemu_bvalid  ),
   .s_axi_rdata   (s_axi_qemu_rdata   ),
   .s_axi_rready  (s_axi_qemu_rready  ),
   .s_axi_rresp   (s_axi_qemu_rresp   ),
   .s_axi_rvalid  (s_axi_qemu_rvalid  ),
   .s_axi_wdata   (s_axi_qemu_wdata   ),
   .s_axi_wready  (s_axi_qemu_wready  ),
   .s_axi_wstrb   (s_axi_qemu_wstrb   ),
   .s_axi_wvalid  (s_axi_qemu_wvalid  ),
   .trigger       (trigger_0          ),
   .aresetn       (s_ps_dma_aresetn   ),
   .aclk          (adc_fs             ),
   .s_axis_tvalid (1'b1               ),
   .s_axis_tdata  ({16'd0, adc_data}  ),
   .s_axis_tlast  (1'b1               ),
   .m_axis_tvalid (axis_qemu_ro_tvalid),
   .m_axis_tdata  (axis_qemu_ro_tdata ),
   .m_axis_tlast  ()
);

//----------------------------------------------------
// READOUT PATH
//----------------------------------------------------
localparam N_DDS_RO = 8;

logic [2:0] rf_signal_cnt;
always_ff @(posedge adc_fs) begin
   if (rf_signal_cnt == 0) begin
      axis_adc_ro_tvalid                    <= rf_signal_valid_dly;
      axis_adc_ro_tdata[N_DDS_RO*16-1:0]   <= rf_signal_data_dly;
   end
   if (rf_signal_valid_dly || axis_adc_ro_tvalid)
      rf_signal_cnt <= rf_signal_cnt + 1;
   else
      rf_signal_cnt <= 0;
end

axis_cdcsync_v1 #(.N(1), .B(168)) u_axis_cdcsync_v1 (
   .s_axis_aresetn  (rst_ni),
   .s_axis_aclk     (t_clk),
   .s0_axis_tready  (tproc_rocdc_0_axis_tready),
   .s0_axis_tvalid  (tproc_rocdc_0_axis_tvalid),
   .s0_axis_tdata   (tproc_rocdc_0_axis_tdata),
   .s1_axis_tready  (), .s1_axis_tvalid  (1'b0), .s1_axis_tdata  (168'd0),
   .s2_axis_tready  (), .s2_axis_tvalid  (1'b0), .s2_axis_tdata  (168'd0),
   .s3_axis_tready  (), .s3_axis_tvalid  (1'b0), .s3_axis_tdata  (168'd0),
   .s4_axis_tready  (), .s4_axis_tvalid  (1'b0), .s4_axis_tdata  (168'd0),
   .s5_axis_tready  (), .s5_axis_tvalid  (1'b0), .s5_axis_tdata  (168'd0),
   .s6_axis_tready  (), .s6_axis_tvalid  (1'b0), .s6_axis_tdata  (168'd0),
   .s7_axis_tready  (), .s7_axis_tvalid  (1'b0), .s7_axis_tdata  (168'd0),
   .s8_axis_tready  (), .s8_axis_tvalid  (1'b0), .s8_axis_tdata  (168'd0),
   .s9_axis_tready  (), .s9_axis_tvalid  (1'b0), .s9_axis_tdata  (168'd0),
   .s10_axis_tready (), .s10_axis_tvalid (1'b0), .s10_axis_tdata (168'd0),
   .s11_axis_tready (), .s11_axis_tvalid (1'b0), .s11_axis_tdata (168'd0),
   .s12_axis_tready (), .s12_axis_tvalid (1'b0), .s12_axis_tdata (168'd0),
   .s13_axis_tready (), .s13_axis_tvalid (1'b0), .s13_axis_tdata (168'd0),
   .s14_axis_tready (), .s14_axis_tvalid (1'b0), .s14_axis_tdata (168'd0),
   .s15_axis_tready (), .s15_axis_tvalid (1'b0), .s15_axis_tdata (168'd0),
   .m_axis_aresetn  (rst_ni),
   .m_axis_aclk     (ro_clk),
   .m0_axis_tready  (rocdc_rot_0_axis_tready),
   .m0_axis_tvalid  (rocdc_rot_0_axis_tvalid),
   .m0_axis_tdata   (rocdc_rot_0_axis_tdata),
   .m1_axis_tready  (1'b1), .m1_axis_tvalid  (), .m1_axis_tdata  (),
   .m2_axis_tready  (1'b1), .m2_axis_tvalid  (), .m2_axis_tdata  (),
   .m3_axis_tready  (1'b1), .m3_axis_tvalid  (), .m3_axis_tdata  (),
   .m4_axis_tready  (1'b1), .m4_axis_tvalid  (), .m4_axis_tdata  (),
   .m5_axis_tready  (1'b1), .m5_axis_tvalid  (), .m5_axis_tdata  (),
   .m6_axis_tready  (1'b1), .m6_axis_tvalid  (), .m6_axis_tdata  (),
   .m7_axis_tready  (1'b1), .m7_axis_tvalid  (), .m7_axis_tdata  (),
   .m8_axis_tready  (1'b1), .m8_axis_tvalid  (), .m8_axis_tdata  (),
   .m9_axis_tready  (1'b1), .m9_axis_tvalid  (), .m9_axis_tdata  (),
   .m10_axis_tready (1'b1), .m10_axis_tvalid (), .m10_axis_tdata (),
   .m11_axis_tready (1'b1), .m11_axis_tvalid (), .m11_axis_tdata (),
   .m12_axis_tready (1'b1), .m12_axis_tvalid (), .m12_axis_tdata (),
   .m13_axis_tready (1'b1), .m13_axis_tvalid (), .m13_axis_tdata (),
   .m14_axis_tready (1'b1), .m14_axis_tvalid (), .m14_axis_tdata (),
   .m15_axis_tready (1'b1), .m15_axis_tvalid (), .m15_axis_tdata ()
);

sg_translator #(.OUT_TYPE(3)) u_ro_translator_0 (
   .aresetn              (1'bx), .aclk (1'bx),
   .s_axis_tdata         (rocdc_rot_0_axis_tdata),
   .s_axis_tvalid        (rocdc_rot_0_axis_tvalid),
   .s_axis_tready        (rocdc_rot_0_axis_tready),
   .m_gen_v6_axis_tready (), .m_gen_v6_axis_tvalid (), .m_gen_v6_axis_tdata (),
   .m_int4_axis_tdata    (), .m_int4_axis_tvalid   (), .m_int4_axis_tready  (),
   .m_mux4_axis_tdata    (), .m_mux4_axis_tvalid   (), .m_mux4_axis_tready  (),
   .m_readout_axis_tready (rot_ro_0_axis_tready),
   .m_readout_axis_tvalid (rot_ro_0_axis_tvalid),
   .m_readout_axis_tdata  (rot_ro_0_axis_tdata)
);

wire        axis_ro_avg_tready, axis_ro_avg_tvalid;
wire [31:0] axis_ro_avg_tdata;
wire        axis_ro_mrbuf_tvalid;
wire [8*2*16-1:0] axis_ro_mrbuf_tdata;

axis_dyn_readout_v1 u_axis_dyn_readout_v1_0 (
   .aresetn        (s_ps_dma_aresetn  ),
   .aclk           (ro_clk            ),
   .s0_axis_tready (rot_ro_0_axis_tready),
   .s0_axis_tvalid (rot_ro_0_axis_tvalid),
   .s0_axis_tdata  (rot_ro_0_axis_tdata),
   .s1_axis_tready (axis_adc_ro_tready ),
   .s1_axis_tvalid (axis_adc_ro_tvalid ),
   .s1_axis_tdata  (axis_adc_ro_tdata  ),
   .m0_axis_tready (1'b1               ),
   .m0_axis_tvalid (axis_ro_mrbuf_tvalid),
   .m0_axis_tdata  (axis_ro_mrbuf_tdata),
   .m1_axis_tready (axis_ro_avg_tready ),
   .m1_axis_tvalid (axis_ro_avg_tvalid ),
   .m1_axis_tdata  (axis_ro_avg_tdata  )
);

wire  [5:0]  s_axi_avg_araddr;   wire [2:0]  s_axi_avg_arprot;
wire         s_axi_avg_arready;  wire        s_axi_avg_arvalid;
wire  [5:0]  s_axi_avg_awaddr;   wire [2:0]  s_axi_avg_awprot;
wire         s_axi_avg_awready;  wire        s_axi_avg_awvalid;
wire         s_axi_avg_bready;   wire  [1:0] s_axi_avg_bresp;
wire         s_axi_avg_bvalid;   wire [31:0] s_axi_avg_rdata;
wire         s_axi_avg_rready;   wire  [1:0] s_axi_avg_rresp;
wire         s_axi_avg_rvalid;   wire [31:0] s_axi_avg_wdata;
wire         s_axi_avg_wready;   wire  [3:0] s_axi_avg_wstrb;
wire         s_axi_avg_wvalid;

// Avg buffer register offsets
xil_axi_ulong AVG_START_REG    = 4 * 0;
xil_axi_ulong AVG_ADDR_REG     = 4 * 1;
xil_axi_ulong AVG_LEN_REG      = 4 * 2;
xil_axi_ulong AVG_DR_START_REG = 4 * 3;
xil_axi_ulong AVG_DR_ADDR_REG  = 4 * 4;
xil_axi_ulong AVG_DR_LEN_REG   = 4 * 5;
xil_axi_ulong BUF_START_REG    = 4 * 6;
xil_axi_ulong BUF_ADDR_REG     = 4 * 7;
xil_axi_ulong BUF_LEN_REG      = 4 * 8;
xil_axi_ulong BUF_DR_START_REG = 4 * 9;
xil_axi_ulong BUF_DR_ADDR_REG  = 4 * 10;
xil_axi_ulong BUF_DR_LEN_REG   = 4 * 11;

axi_mst_0 u_axi_mst_avg_0 (
   .aresetn       (s_ps_dma_aresetn  ),
   .aclk          (s_ps_dma_aclk     ),
   .m_axi_araddr  (s_axi_avg_araddr  ),
   .m_axi_arprot  (s_axi_avg_arprot  ),
   .m_axi_arready (s_axi_avg_arready ),
   .m_axi_arvalid (s_axi_avg_arvalid ),
   .m_axi_awaddr  (s_axi_avg_awaddr  ),
   .m_axi_awprot  (s_axi_avg_awprot  ),
   .m_axi_awready (s_axi_avg_awready ),
   .m_axi_awvalid (s_axi_avg_awvalid ),
   .m_axi_bready  (s_axi_avg_bready  ),
   .m_axi_bresp   (s_axi_avg_bresp   ),
   .m_axi_bvalid  (s_axi_avg_bvalid  ),
   .m_axi_rdata   (s_axi_avg_rdata   ),
   .m_axi_rready  (s_axi_avg_rready  ),
   .m_axi_rresp   (s_axi_avg_rresp   ),
   .m_axi_rvalid  (s_axi_avg_rvalid  ),
   .m_axi_wdata   (s_axi_avg_wdata   ),
   .m_axi_wready  (s_axi_avg_wready  ),
   .m_axi_wstrb   (s_axi_avg_wstrb   ),
   .m_axi_wvalid  (s_axi_avg_wvalid  )
);

wire        m0_axis_buf_avg_tvalid;
wire [63:0] m0_axis_buf_avg_tdata;
wire        m1_axis_buf_dec_tvalid;
wire [31:0] m1_axis_buf_dec_tdata;

axis_avg_buffer #(.N_AVG(13), .N_BUF(12), .B(16)) u_axis_avg_buffer_0 (
   .s_axi_aclk    (s_ps_dma_aclk    ),
   .s_axi_aresetn (s_ps_dma_aresetn ),
   .s_axi_araddr  (s_axi_avg_araddr ),
   .s_axi_arprot  (s_axi_avg_arprot ),
   .s_axi_arready (s_axi_avg_arready),
   .s_axi_arvalid (s_axi_avg_arvalid),
   .s_axi_awaddr  (s_axi_avg_awaddr ),
   .s_axi_awprot  (s_axi_avg_awprot ),
   .s_axi_awready (s_axi_avg_awready),
   .s_axi_awvalid (s_axi_avg_awvalid),
   .s_axi_bready  (s_axi_avg_bready ),
   .s_axi_bresp   (s_axi_avg_bresp  ),
   .s_axi_bvalid  (s_axi_avg_bvalid ),
   .s_axi_rdata   (s_axi_avg_rdata  ),
   .s_axi_rready  (s_axi_avg_rready ),
   .s_axi_rresp   (s_axi_avg_rresp  ),
   .s_axi_rvalid  (s_axi_avg_rvalid ),
   .s_axi_wdata   (s_axi_avg_wdata  ),
   .s_axi_wready  (s_axi_avg_wready ),
   .s_axi_wstrb   (s_axi_avg_wstrb  ),
   .s_axi_wvalid  (s_axi_avg_wvalid ),
   .trigger       (trigger_0         ),
   .s_axis_aresetn(s_ps_dma_aresetn  ),
   .s_axis_aclk   (ro_clk            ),
   .s_axis_tready (axis_ro_avg_tready),
   .s_axis_tvalid (axis_ro_avg_tvalid),
   .s_axis_tdata  (axis_ro_avg_tdata ),
   .m_axis_aclk   (s_ps_dma_aclk     ),
   .m_axis_aresetn(s_ps_dma_aresetn  ),
   .m0_axis_tready(1'b1                   ),
   .m0_axis_tvalid(m0_axis_buf_avg_tvalid ),
   .m0_axis_tdata (m0_axis_buf_avg_tdata  ),
   .m0_axis_tlast (),
   .m1_axis_tready(m1_axis_buf_dec_tready ),
   .m1_axis_tvalid(m1_axis_buf_dec_tvalid ),
   .m1_axis_tdata (m1_axis_buf_dec_tdata  ),
   .m1_axis_tlast (),
   .m2_axis_tready(1'b1),
   .m2_axis_tvalid(),
   .m2_axis_tdata ()
);

//============================================================
// TEST STIMULI — QickEmu replay
//============================================================

initial begin
   // Create and start VIP agents
   axi_mst_tproc_agent = new("axi_mst_tproc VIP Agent",  tb_qick_emu.u_axi_mst_tproc_0.inst.IF);
   axi_mst_sg_agent    = new("axi_mst_sg_0 VIP Agent",   tb_qick_emu.u_axi_mst_sg_0.inst.IF);
   axi_mst_avg_agent   = new("axi_mst_avg_0 VIP Agent",  tb_qick_emu.u_axi_mst_avg_0.inst.IF);
   axi_mst_qemu_agent  = new("axi_mst_qemu_0 VIP Agent", tb_qick_emu.u_axi_mst_qemu_0.inst.IF);
   axi_mst_tproc_agent.set_agent_tag("axi_mst_tproc VIP");
   axi_mst_sg_agent.set_agent_tag("axi_mst_sg_0 VIP");
   axi_mst_avg_agent.set_agent_tag("axi_mst_avg_0 VIP");
   axi_mst_qemu_agent.set_agent_tag("axi_mst_qemu_0 VIP");
   axi_mst_tproc_agent.start_master();
   axi_mst_sg_agent.start_master();
   axi_mst_avg_agent.start_master();
   axi_mst_qemu_agent.start_master();

   // Initialize all control signals
   qnet_dt_i              = '{default:'0};
   rst_ni                 = 1'b0;
   axi_dt                 = 0;
   s1_axis_tvalid         = 1'b0;
   port_1_dt_i            = 0;
   qcom_rdy_i             = 0;
   qp2_rdy_i              = 0;
   periph_dt_i            = '{default:'0};
   qnet_rdy_i             = 0;
   proc_start_i           = 1'b0;
   proc_stop_i            = 1'b0;
   core_start_i           = 1'b0;
   core_stop_i            = 1'b0;
   time_rst_i             = 1'b0;
   time_init_i            = 1'b0;
   time_updt_i            = 1'b0;
   offset_dt_i            = 0;
   tb_load_mem            = 1'b0;
   tb_load_mem_done       = 1'b0;
   sg_s0_axis_tvalid      = 0;
   sg_s0_axis_tdata       = 0;
   m1_axis_buf_dec_tready = 1'b1;
   m_dma_axis_tready_i    = 1'b1;
   s_dma_axis_tdata_i     = 0;
   s_dma_axis_tlast_i     = 0;
   s_dma_axis_tvalid_i    = 0;
   #10ns;

   // Assert then release reset
   repeat(16) @(posedge s_ps_dma_aclk); #0.1ns;
   rst_ni = 1'b1;

   #100ns;

   // Load tproc memories AFTER reset (BRAM init is complete)
   tproc_load_mem_emu(EMU_DIR);

   #1us;

   // Load signal generator envelope table (if any shaped pulses used)
   sg_load_mem_emu(EMU_DIR, 0);

   #1us;

   // Replay all AXI-Lite transactions
   begin
      string replay_path;
      replay_path = {EMU_DIR, "/axi_replay.txt"};
      $display("### %t - Replaying AXI transactions from %s ###",
               $realtime(), replay_path);
      replay_axi_writes(replay_path);
   end

// Wait for program execution to complete.
   #(TEST_RUN_TIME);

   // ===== READ CAPTURED DATA FROM AVG BUFFER =====
   $display("### %t - Reading avg/dec buffers ###", $realtime());

   // Read averaged data
   @(posedge s_ps_dma_aclk); #0.1;
   axi_mst_avg_agent.AXI4LITE_WRITE_BURST(AVG_DR_LEN_REG, prot, 32'h00000001, resp);
   #100ns;
   @(posedge s_ps_dma_aclk); #0.1;
   axi_mst_avg_agent.AXI4LITE_WRITE_BURST(AVG_DR_START_REG, prot, 32'h00000001, resp);
   #100ns;
   @(posedge s_ps_dma_aclk); #0.1;
   axi_mst_avg_agent.AXI4LITE_WRITE_BURST(AVG_DR_START_REG, prot, 32'h00000000, resp);
   #1us;

   // Read decimated data
   @(posedge s_ps_dma_aclk); #0.1;
   axi_mst_avg_agent.AXI4LITE_WRITE_BURST(BUF_DR_LEN_REG, prot, 32'h0000039A, resp);
   #100ns;
   @(posedge s_ps_dma_aclk); #0.1;
   axi_mst_avg_agent.AXI4LITE_WRITE_BURST(BUF_DR_START_REG, prot, 32'h00000001, resp);
   #100ns;
   @(posedge s_ps_dma_aclk); #0.1;
   axi_mst_avg_agent.AXI4LITE_WRITE_BURST(BUF_DR_START_REG, prot, 32'h00000000, resp);

   // Wait for data to drain
   #50us;
   // ===== END READ =====

   $display("*** End Test ***");
   // Close CSV files before finishing
   $fclose(dac_csv_fd);
   $fclose(avg_csv_fd);
   $fclose(dec_csv_fd);
   $finish();
end


//============================================================
// CSV Output Logging
//============================================================

// File descriptors — opened at time 0
integer dac_csv_fd;   // DAC output samples (one row per sg_clk when valid)
integer avg_csv_fd;   // Averaged IQ from avg_buffer m0 (one row per word)
integer dec_csv_fd;   // Decimated IQ from avg_buffer m1 (one row per word)

initial begin
   string dac_csv_path, avg_csv_path, dec_csv_path;
   dac_csv_path = {EMU_DIR, "/dac_out.csv"};
   avg_csv_path = {EMU_DIR, "/avg_out.csv"};
   dec_csv_path = {EMU_DIR, "/dec_out.csv"};
   dac_csv_fd = $fopen(dac_csv_path, "w");
   avg_csv_fd = $fopen(avg_csv_path, "w");
   dec_csv_fd = $fopen(dec_csv_path, "w");

   // Write headers
   $fwrite(dac_csv_fd, "time_ps");
   for (int i = 0; i < N_DDS; i++) $fwrite(dac_csv_fd, ",s%0d", i);
   $fwrite(dac_csv_fd, "\n");

   $fwrite(avg_csv_fd, "time_ps,I,Q\n");
   $fwrite(dec_csv_fd, "time_ps,I,Q\n");
end

// DAC samples: N_DDS=16 parallel samples per sg_clk when the SG is active.
// Columns: time_ps, s0..s15  (signed 16-bit each)
always @(posedge sg_clk) begin
   if (axis_sg_dac_tvalid) begin
      $fwrite(dac_csv_fd, "%0t", $time);
      for (int i = 0; i < N_DDS; i++)
         $fwrite(dac_csv_fd, ",%0d", $signed(axis_sg_dac_tdata[16*i +: 16]));
      $fwrite(dac_csv_fd, "\n");
   end
end

// Averaged IQ: 64-bit word, [31:0]=I  [63:32]=Q  (32-bit signed each).
// One accumulated sum per trigger window.
always @(posedge s_ps_dma_aclk) begin
   if (m0_axis_buf_avg_tvalid)
      $fwrite(avg_csv_fd, "%0t,%0d,%0d\n", $time,
              $signed(m0_axis_buf_avg_tdata[31:0]),
              $signed(m0_axis_buf_avg_tdata[63:32]));
end

// Decimated IQ: 32-bit word, [15:0]=I  [31:16]=Q  (16-bit signed each).
// Raw downconverted stream at readout clock rate.
always @(posedge s_ps_dma_aclk) begin
   if (m1_axis_buf_dec_tvalid)
      $fwrite(dec_csv_fd, "%0t,%0d,%0d\n", $time,
              $signed(m1_axis_buf_dec_tdata[15:0]),
              $signed(m1_axis_buf_dec_tdata[31:16]));
end


//----------------------------------------------------
// TASKS
//----------------------------------------------------

// Load tproc program and wave memories from QickEmu-generated files.
task tproc_load_mem_emu(string emu_dir);
   string pmem_file, wmem_file;
   pmem_file = {emu_dir, "/pmem.mem"};
   wmem_file = {emu_dir, "/wmem.mem"};
   $display("### Loading tproc memories from: %s ###", emu_dir);
   $display("### pmem_file: %s ###", pmem_file);
   $display("### wmem_file: %s ###", wmem_file);
   $readmemh(pmem_file, AXIS_QPROC.QPROC.CORE_0.CORE_MEM.P_MEM.RAM);
   $readmemh(wmem_file, AXIS_QPROC.QPROC.CORE_0.CORE_MEM.W_MEM.RAM);
   $display("### VERIFY P_MEM[1] = %h ###", AXIS_QPROC.QPROC.CORE_0.CORE_MEM.P_MEM.RAM[1]);
   $display("### tproc memories loaded ###");
endtask

// Load signal generator envelope table via AXIS streaming.
// sg_ch: channel index (used to select sgmem_ch{sg_ch}.mem).
// If the file doesn't exist (e.g., const-style pulse with no envelope), prints a
// message and returns without driving the AXIS interface.
task sg_load_mem_emu(string emu_dir, int sg_ch);
   string sg_file;
   integer fd, vali, valq;
   bit signed [15:0] ii, qq;

   sg_file = $sformatf("%s/sgmem_ch%0d.mem", emu_dir, sg_ch);
   fd = $fopen(sg_file, "r");
   if (fd == 0) begin
      $display("### %t - SG ch%0d: no envelope file %s (const pulse or not used) ###",
               $realtime(), sg_ch, sg_file);
      return;
   end

   $display("### %t - Loading SG ch%0d envelope from %s ###",
            $realtime(), sg_ch, sg_file);

   // Set envelope table start address to 0 and enable write
   @(posedge s_ps_dma_aclk); #0.1;
   axi_mst_sg_agent.AXI4LITE_WRITE_BURST(SG_ADDR_START_ADDR, prot, 0, resp);
   #100ns;
   axi_mst_sg_agent.AXI4LITE_WRITE_BURST(SG_ADDR_WE, prot, 1, resp);
   #100ns;

   tb_load_mem = 1;
   wait(sg_s0_axis_tready);

   while ($fscanf(fd, "%d,%d", vali, valq) == 2) begin
      ii = vali;
      qq = valq;
      @(posedge sg_s0_axis_aclk);
      sg_s0_axis_tvalid = 1;
      sg_s0_axis_tdata  = {qq, ii};
   end
   $fclose(fd);

   @(posedge sg_s0_axis_aclk);
   sg_s0_axis_tvalid = 0;
   tb_load_mem_done  = 1;

   $display("### %t - SG ch%0d envelope loaded ###", $realtime(), sg_ch);
endtask


// Replay all AXI-Lite write transactions from a text file.
// File format (generated by QickEmu.export_vivado_files()):
//   # comment lines are ignored
//   XXXXXXXX YYYYYYYY   (8-hex-digit addr, space, 8-hex-digit data)
// Each transaction is routed to the correct VIP agent based on address range.
task replay_axi_writes(string replay_file);
   integer fd;
   string  line;
   integer addr_val, data_val;
   integer n_routed, n_skipped;

   fd = $fopen(replay_file, "r");
   if (fd == 0) begin
      $display("ERROR: Cannot open AXI replay file: %s", replay_file);
      $display("       Run QickEmu.export_vivado_files() to generate it.");
      return;
   end

   n_routed  = 0;
   n_skipped = 0;

   while ($fgets(line, fd)) begin
      if (line.len() < 2)        continue;
      if (line.substr(0,0) == "#") continue;  // comment
      if ($sscanf(line, "%h %h", addr_val, data_val) == 2) begin
         route_and_write(addr_val, data_val);
         n_routed++;
      end
   end
   $fclose(fd);

   $display("### AXI replay done: %0d transactions replayed ###", n_routed);
endtask


// Route an absolute-address AXI write to the correct VIP agent.
// Strips the base address to get the IP register offset.
task route_and_write(integer addr, integer data);
   integer offset;

   if (addr >= TPROC_BASE && addr < TPROC_BASE + 32'h10000) begin
      offset = addr - TPROC_BASE;
      @(posedge s_ps_dma_aclk); #0.1;
      axi_mst_tproc_agent.AXI4LITE_WRITE_BURST(offset, prot, data, resp);
   end
   else if (addr >= SG_BASE_LO && addr < SG_BASE_HI) begin
      // All gen IPs share the same VIP in this testbench.
      // The offset (low 16 bits) selects the register within the IP.
      offset = addr & 32'h0000FFFF;
      @(posedge s_ps_dma_aclk); #0.1;
      axi_mst_sg_agent.AXI4LITE_WRITE_BURST(offset, prot, data, resp);
   end
   else if (addr >= AVG_BASE_LO && addr < AVG_BASE_HI) begin
      offset = addr & 32'h0000FFFF;
      @(posedge s_ps_dma_aclk); #0.1;
      axi_mst_avg_agent.AXI4LITE_WRITE_BURST(offset, prot, data, resp);
   end
   else begin
      $display("WARNING: Unrouted AXI write addr=0x%08X data=0x%08X", addr, data);
   end
endtask

endmodule


//----------------------------------------------------
// DAC-ADC RF frontend model (loopback)
// Identical to model in tb_qick.sv.
//----------------------------------------------------
module model_DAC_ADC #(
   parameter integer DAC_W       = 16,
   parameter integer ADC_W       = 16,
   parameter integer BUFFER_SIZE = 16
)(
   input  wire clk_DAC,
   input  wire [DAC_W-1:0] dac_sample,
   input  wire clk_ADC,
   output logic [ADC_W-1:0] adc_sample,
   input  int  mode   // 0 = ZOH, 1 = linear interpolation
);
   real buffer_samples[BUFFER_SIZE];
   real buffer_times  [BUFFER_SIZE];
   int  wr_ptr = 0;
   real signal_in, sampled_ADC;

   initial begin
      for (int i = 0; i < BUFFER_SIZE; i++) begin
         buffer_samples[i] = 0.0;
         buffer_times  [i] = 0.0;
      end
   end

   always @(posedge clk_DAC) begin
      real t_now = $realtime * 1e-9;
      signal_in = $signed(dac_sample) / 2.0**(DAC_W-1);
      buffer_samples[wr_ptr] = signal_in;
      buffer_times  [wr_ptr] = t_now;
      wr_ptr = (wr_ptr + 1) % BUFFER_SIZE;
   end

   always @(posedge clk_ADC) begin
      real t_adc = $realtime * 1e-9;
      real val;
      case (mode)
         0: begin
            int idx_last = (wr_ptr + BUFFER_SIZE - 1) % BUFFER_SIZE;
            val = buffer_samples[idx_last];
         end
         1: begin
            int idx_curr = (wr_ptr + BUFFER_SIZE - 1) % BUFFER_SIZE;
            int idx_prev = (wr_ptr + BUFFER_SIZE - 2) % BUFFER_SIZE;
            real t1 = buffer_times  [idx_prev], t2 = buffer_times  [idx_curr];
            real y1 = buffer_samples[idx_prev], y2 = buffer_samples[idx_curr];
            if (t2 != t1) val = y1 + (t_adc - t1) * (y2 - y1)/(t2 - t1);
            else          val = y2;
         end
         default: val = 0.0;
      endcase
      if      (val >  1.0) sampled_ADC =  1.0;
      else if (val < -1.0) sampled_ADC = -1.0;
      else                 sampled_ADC =  val;
      adc_sample = sampled_ADC * $signed(2**(ADC_W-1)-1);
   end
endmodule
