part: XC7Z035
speed_grade: '-2I'
ps_in_freq_mhz: 50
cpu:
  ratio_mode: '6:2:1'
  freq_mhz: 667
io_pll:
  freq_mhz: 1000.0
ddr:
  type: DDR3
  data_rate_mbps: 1066
  speed_bin: 1066F
  data_bus_bits: 16
  part_geometry:
    bit_width: 16
    mbits: 4096
    bank_bits: 3
    row_bits: 15
    col_bits: 10
  timing:
    cl: 7
    cwl: 6
    t_rcd_cycles: 7
    t_rp_cycles: 7
    t_rc_ns: 48.75
    t_ras_min_ns: 35.0
    t_faw_ns: 40.0
mio:
  voltage_bank0: "3.3V"
  voltage_bank1: "3.3V"
uarts:
  uart0:
    rx_pin: MIO 14
    tx_pin: MIO 15
    baud_rate: 115200
qspi:
  freq_mhz: 200.0
sdio:
  sdio0:
    ck_pin: MIO 40
    cmd_pin: MIO 41
    io0_pin: MIO 42
    io1_pin: MIO 43
    io2_pin: MIO 44
    io3_pin: MIO 45
    detect_pin: MIO 47
usb:
  usb0:
    reset_pin: MIO 46
ps_pl:
  m_axi_gp0: yes
  m_axi_gp1: yes
  fclk0:
    freq_mhz: 100.0
  fclk1:
    freq_mhz: 30.0
  fclk2:
    freq_mhz: 50.0
  fclk3:
    freq_mhz: 70.0
  frst0: yes
  frst1: yes
  frst2: yes
  frst3: yes
